### ISSUE TITLE
Request: add a release tag for a recent version

### ISSUE THREAD

**Issue by tchajed** [ProofGeneral/PG#109]
Could PG officially release a new numbered version? Ideally this would be a git tag of the form `v4.4`, for example.

I'm asking because this would facilitate distributing PG through Homebrew, a widely used OS X package manager. Currently the naive installation `brew install proof-general` installs v4.2, which is terribly out of date (October 2012!) and doesn't really work - you have to run `brew install --HEAD proof-general` to replicate the recommended PG installation instructions. Homebrew discourages formulae that require installation from Git sources.

For what it's worth, Arch Linux also [considers v4.2 to be the latest PG](https://aur.archlinux.org/packages/proofgeneral/), and it is not flagged out of date. You need to install proofgeneral-git to get a good version.

If PG pushes a release tag for a recent version I'll take care of updating the Homebrew proof-general formula to reference and correctly build the new release. PG should also periodically release new versions (by tagging them) so Homebrew can stay up-to-date.

**Comment by cpitclaudel** [comment]
+1 for this.  Objections?

**Comment by zmwangx** [comment]
It's not just a Homebrew issue; ask any packager in the world and no one likes the idea of the always stable master branch without tagged releases. Even courtesy cuts once in a while would be nice.

**Comment by cpitclaudel** [comment]
@zmwangx I'm not sure how familiar you are with the history of this project :) The lead developer stepped down more or less 4 years ago (2012), and we've just recently managed to put together a stable-ish new team (until then we had one contribtuon.  We'll cut a release soon, and we don't like the "always stable master branch" model more than you do, I'm sure :) (Heck, speaking of master branch: until the beginning of this year, we were on CVS :P)

**Comment by zmwangx** [comment]
> I'm not sure how familiar you are with the history of this project :)

With due respect, I'm from the Homebrew team, and I'm not familiar with the history at all 😅 

> We'll cut a release soon

Cool, thanks.

> Heck, speaking of master branch: until the beginning of this year, we were on CVS :P

Congrats on migrating out of hell!

**Comment by psteckler** [comment]
Linux Mint 18 distributes version 4.3~pre131011-0.2, which, as version
numbers go, is slightly worrying.

-- Paul

**Comment by Matafou** [comment]
No objection.
P.

Le vendredi 16 septembre 2016, psteckler <notifications@github.com> a
écrit :

**Comment by erikmd** [comment]
Same for me.
Erik

**Comment by cpitclaudel** [comment]
@erikmd, can you push a new tag, then? Since the last one was 4.4pre, 4.4 sounds reasonable. What do you think?  We should probably also update at least the readme.

**Comment by erikmd** [comment]
Hi @cpitclaudel, yes 4.4 looks good to me. So I'm going to update the version number in the readme and in the doc, and push a tag with latest master. Also, I'll try to include the userman.pdf and the adaptingman.pdf within the GItHub release, to be able to update both pdf links in https://proofgeneral.github.io/doc/ ...

**Comment by erikmd** [comment]
Hi all, I've just done the documentation update and pushed a new tag `v4.4`.
The doc in pdf (and tarballs) are available at https://github.com/ProofGeneral/PG/releases/tag/v4.4
and from the website https://proofgeneral.github.io/doc
Best regards

**Comment by Matafou** [comment]
Thanks Erik.
P.

2016-09-18 22:32 GMT+02:00 Erik Martin-Dorel <notifications@github.com>:

**Comment by zmwangx** [comment]
Thanks for the tag, I'll update our Homebrew package to 4.4. I noticed a problem with your sh and perl scripts though (they are not executable) and have opened a PR #112. Hopefully you could address that, thanks.

**Comment by cpitclaudel** [comment]
Thanks Erik! :+1: :clap:
