### ISSUE TITLE
Debug output is broken

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#110]
In generic/proof-useropts.el, if you set `proof-general-debug' to something non-nil, recompile PG, then start processing a script, you get a backtrace:

```
Debugger entered--Lisp error: (error "Don't know how to make a let-bound variable an alias")
  defvaralias(log-warning-minimum-level warning-minimum-log-level)
  byte-code(...)
  display-warning(proof-general "Unregistering file /home/steck/foo.v (not registered, no action)." 
  proof-debug("Unregistering file /home/steck/foo.v (not registered, no action).")
  proof-unregister-buffer-file-name(tell-the-prover)
  proof-activate-scripting(nil advancing)
  proof-assert-until-point()
  proof-toolbar-next()
  call-interactively(proof-toolbar-next nil nil)
  command-execute(proof-toolbar-next)
```

**Comment by psteckler** [comment]
This may be an Emacs bug, since the call to display-warning looks OK.

**Comment by cpitclaudel** [comment]
Hmm. Did you remove parts of that backtrace?

**Comment by psteckler** [comment]
Yes, I intentionally elided the contents of the byte-code, which I indicated by an ellipsis, and accidentally, at the end of the call to display-warning, I edited out the arguments :debug and "*PG Debug*".

**Comment by cpitclaudel** [comment]
My guess is that this is a PG bug. Can you try either of the following changes and see if it fixes it?

* Add `(require 'warning)` to the beginning of the `proof-debug` function
* Change `log-warning-minimum-level` to `warning-minimum-log-level` in `proof-debug`

**Comment by psteckler** [comment]
Only the second change was needed to fix the bug.

**Comment by cpitclaudel** [comment]
Neat. I think either of them would have worked.  Can you make a PR?

**Comment by psteckler** [comment]
PR #111 created.
