### ISSUE TITLE
Parallel background compliation fails to execute some imports

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#123]
I occasionally stumble upon the issue that when using parallel background compilation, Coq will complain about some identifiers or notations not being defined even though they have clearly been imported. Switching to sequential background compilation fixes this. I haven't seen this in a while, but now it surfaced again... unfortunately, the only file I can see this behavior with has quite a lot of dependencies. Maybe you can spot the issue by just looking at the bad file: https://gitlab.mpi-sws.org/FP/iris-atomic/blob/129cd4e8bd8687c2818cda2c30581c8f8faada49/atomic_incr.v

Steps to reproduce:
* Needs Coq 8.5 pl{2,3} and ssreflect 1.6
* Clone https://gitlab.mpi-sws.org/FP/iris-coq.git at commit bb5e21f21
* `make && make install`
* Clone https://gitlab.mpi-sws.org/FP/iris-atomic.git at commit 129cd4e8bd
* `make` (this should succeed)
* Open `atomic_incr.v` with parallel background compilation enabled, and do `C-c C-b` to step over the entire buffer.

It will complain in the definition of `incr_triple` that `atomic_triple` is not defined, even though this was imported by `From iris_atomic Require Import atomic` and the previous `make` proved that the file is all right.

Maybe it's something with the underscore?

**Comment by hendriktews** [comment]
This sounds strange, because the background compilation does not
influence the running coqtop process about where to load required
files.

I have not tried to reproduce myself yet, but I trust you have
tried the steps in a fresh directory to avoid stale vo's?

Have you verified that there are no stale vo's left in the
iris-coq installation directory?

It sounds like there is actually no recompilation happening,
because of the make. Could you verify that there is indeed no
recompilation by checking that *Message* only contains ``Check''
lines and no ``Recompile'' lines?

When you have started processing atomic_incr.v, could you verify
that the coqtop background process has the right command line
arguments, eg by ps -A -o pid,args | grep coqtop?

Does iris_coq also contain a module atomic somewhere? 

> Maybe it's something with the underscore?

The relevant regular expressions in Proof General all contain
underscores.

**Comment by RalfJung** [comment]
> I have not tried to reproduce myself yet, but I trust you have tried the steps in a fresh directory to avoid stale vo's?

No, I did not. Will do.
(Still, considering that both `make` and sequential background compilation work fine, this sounds like a bug to me.)

> Does iris_coq also contain a module atomic somewhere?

It used to, but doesn't any more. But even when it used to, the import clearly selects the one in iris_atomic, not the one in iris proper.

**Comment by RalfJung** [comment]
I deleted all stale files in the iris_atomic folder (`git clean -xfd`), and I removed the folder iris proper is installed to before installing again. This should guarantee that there are no stale `.vo` files. The issue persists.

The `coqtop` run my emacs looks all right:
```
/home/r/bin/coq-8.5/bin/coqtop -emacs -Q /home/r/.../iris/iris-atomic iris_atomic
```

The emacs message buffer only says:
```
Loading coq...done
Coq project file detected: /home/r/.../iris/iris-atomic/_CoqProject. [2 times]
The Coq Proof Assistant, version 8.5pl3 (October 2016)
compiled on Oct 27 2016 12:38:38 with OCaml 4.02.3
Starting: /home/r/bin/coq-8.5/bin/coqtop -emacs -Q /home/r/.../iris/iris-atomic iris_atomic
M-x proof-prf for goals; M-x proof-layout-windows refreshes [2 times]
Starting coq process... done.
(No files need saving)
Check /home/r/.../iris/iris-atomic/atomic.v
Library compilation finished
```

**Comment by hendriktews** [comment]
Ralf Jung <notifications@github.com> writes:

> (Still, considering that both make and sequential background
> compilation work fine, this sounds like a bug to me.)

Sure, I am not questioning it's a bug, The question is what
component the bug is in.

**Comment by hendriktews** [comment]
Ralf Jung <notifications@github.com> writes:

> again. This should guarantee that there are no stale .vo files. The
> issue persists.

Thanks for checking.

> The coqtop run my emacs looks all right:
>
> /home/r/bin/coq-8.5/bin/coqtop -emacs -Q /home/r/.../iris/iris-atomic iris_atomic

Do you have a directory "...", or have you shortened the path?

**Comment by RalfJung** [comment]
I shortened the path. All `...` are actually the same, proper name of the folder everything is happening in.

**Comment by hendriktews** [comment]
I can reproduce the issue - thanks for the detailed report.

The From iris_atomic Require Import atomic. is not sent to
coqtop, as you can see in the *coq* buffer. There must be an
error in the logic that handles several requires that causes one
require to be dropped.

If you single-step through the require section it does work - I
guess you know this.

**Comment by RalfJung** [comment]
> If you single-step through the require section it does work - I guess you know this.

I actually did not (otherwise I would have mentioned it). This may be a better work-around than switching to sequential background compilation ;)

**Comment by hendriktews** [comment]
Ralf Jung <notifications@github.com> writes:

> The coqtop run my emacs looks all right:
>
> /home/r/bin/coq-8.5/bin/coqtop -emacs -Q /home/r/.../iris/iris-atomic iris_atomic
>
> The emacs message buffer only says:
>
> Starting: /home/r/bin/coq-8.5/bin/coqtop -emacs -Q /home/r/.../iris/iris-atomic iris_atomic

I see two -Q options in both cases, apparently corresponding to
the two -Q lines in _CoqProject. Am I doing something wrong?

**Comment by RalfJung** [comment]
Oh, right, the `-Q iris iris`. You can remove that line, it didn't make any difference here. Sorry, forgot about this.

**Comment by hendriktews** [comment]
The problem is that require commands that do not generate a
compilation job (because they import only from stdlib or user
contrib) overwrite queued commands from preceding require's that
did generate a compilation job.

I am polishing a fix now.

**Comment by hendriktews** [comment]
> * Clone https://gitlab.mpi-sws.org/FP/iris-coq.git at commit bb5e21f21 
> * make && make install 

I understand that the make install is necessary to reproduce the
bug. But do you actually develop like this?

In principle Proof General should support a development model
where you have iris-coq and iris-atomic checked out in separate
directories such that processing something in iris-atomic may
trigger a recompilation inside iris-coq. I doubt this is
currently working, but it should be relatively easy to fix for
the case where you have proper _CoqProject files in both
directories.

When you install iris-coq in user-contrib, coqdep will not report
dependencies into iris-coq and Proof General cannot check
whether the files are up-to-date there.

**Comment by RalfJung** [comment]
> I understand that the make install is necessary to reproduce the bug. But do you actually develop like this?

So far, I did. I actually don't usually want automatic recompilation across repositories, but treat iris (the dependency) as a library  in iris_atomic. Unfortunately iris is moving fast enough that we really have to pin dependencies to a particular commit, so we are currently transitioning to submodules for this purpose -- and then `coqdep` will catch these dependencies and automatically re-build parts of Iris as needed. I am not yet sure I like the latter. (And it seems to be actively harmful for the `vio` toolchain, where suddenly we can only build `vio` for iris-atomic if we have `vio` for iris -- which is not the case if iris is installed in user-contrib.)

Thanks a lot for fixing this!

**Comment by hendriktews** [comment]
Ralf,

> (And it seems to be actively harmful for the vio toolchain,
> where suddenly we can only build vio for iris-atomic if we have
> vio for iris -- which is not the case if iris is installed in
> user-contrib.)

I am not sure I fully understand: You mean that make in
iris-atomic insists on building all .vo's in iris, right? But if
you write the coqc commands into bash by hand, then coq will
happily build a .vo even if there are only .vio files in the iris
directory?

Would you agree that the problem is only that make cannot deal
with prerequisites of the form ``at least one of .vo or .vio''?

Hendrik

**Comment by RalfJung** [comment]
Just to be clear, this is not a PG issue I am talking about. Also, I haven't actually experienced it myself as I have yet to play around with `make quick`. But from what I understood, the problem seems to be indeed that even though `make quick` would work fine with just the `.vo` files of the dependencies, it builds the `.vio` files as well *if* the dependent-on module is "local" (as opposed to be in some global search path). So indeed the problem seems to be that the actual dependency is disjunctive, but there is no (nice?) way to express that in a makefile.

**Comment by hendriktews** [comment]
Thanks for confirming that we are talking about the same problem.

> Just to be clear, this is not a PG issue I am talking about.

Sure, I understood this.

> (as opposed to be in some global search path).

coqdep makes the difference there, it ignores dependencies from
the coq library or user contrib path.
