### ISSUE TITLE
admit/Admitted highlighting disappears inside locked reagion

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#135]
coq-cheat-face sets the background color, but when an item with this face (eg. admit) is inside the locked region, the asserted span takes precedence and the highlighting disappears.

**Comment by Matafou** [comment]
I have already tried many times to solve this issue with no success. The locked region color always takes priority. One can set a foreground color but it is less "scary" imho.

**Comment by psteckler** [comment]
I added a somewhat different priority system for PG/xml. I'll see if I can
make it work there.

-- Paul

**Comment by cpitclaudel** [comment]
I don't expect we can fix this: the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overlay-Properties.html) says:

> Currently, all overlays take priority over text properties.

**Comment by hendriktews** [comment]
I agree that a proper fix would be far too complicated for this
little issue. But maybe we can collect a few ideas about how to
mitigate? 

How about a scary combination of foreground/background color,
such that we at lease retain the foreground color in the asserted
region? Maybe bold read on yellow?

Hendrik

**Comment by cpitclaudel** [comment]
I like the idea of changing the foreground.  Alternatively, we could make it inverse video (I think that would survive despite the overlay)

**Comment by psteckler** [comment]
In the Elisp docs, it says:

  "all overlays take priority over text properties"

So an alternative to setting a text property here would be to create a span
with a high priority.

**Comment by psteckler** [comment]
Changing the face spec to use:

`(:foreground "red" :background "black" :inverse-video t)`                                                                                                                                                           

may be good enough. If the locked region doesn't cover the text, it looks as before. If the locked region covers the text, the background remains red, although the text is colored like the locked region.

**Comment by cpitclaudel** [comment]
> Changing the face spec to use:
> (:foreground "red" :background "black" :inverse-video t)

That won't really do — it'll work only if the user's background is already black, which is uncommon, I think.  We could dynamically read the default background, but this sounds like a lot of work for a small issue.

We could simply underline, or embolden, or italicize the "admitted" keyword, if we want to make it more visible.

**Comment by psteckler** [comment]
My default background is not black, as far as I know.

**Comment by cpitclaudel** [comment]
Sorry, I read that wrong.  It should have been that:

> That won't really do — it'll work only if the user's setup is already black on white, I think. We could dynamically read the default background and invert it, but this sounds like a lot of work for a small issue.

**Comment by psteckler** [comment]
You can omit the :background in the above, and then you'll get the default background as the text color and red as the displayed background. On my machine, the text is white, since that's the default background. A little odd-looking, though.

**Comment by cpitclaudel** [comment]
Yup, this is what I had in mind with the inverse-video comment above.

**Comment by Matafou** [comment]
Just did that (inverse-video). I also tried :box attribute which is prettier but makes the line height change in a irritating way imho.

**Comment by cpitclaudel** [comment]
You can use -1 as the box width to prevent it from enlarging the line

**Comment by Matafou** [comment]
Nice! It is prettier like this imho: when unlocked we see the red background, and when locked we only see the surrounding red box.
