### ISSUE TITLE
doc: Coq electric terminator is wrongly documented

### ISSUE THREAD

**Issue by RBKreckel** [ProofGeneral/PG#138]
Electric terminator C-c . works when using Coq, but the documented C-c C-. does not.
I think this patch should be applied:
diff --git a/doc/ProofGeneral.texi b/doc/ProofGeneral.texi
index 40c0ef87..442ce6d5 100644
--- a/doc/ProofGeneral.texi
+++ b/doc/ProofGeneral.texi
@@ -920,7 +920,7 @@ example in Isabelle with semi-colons, but these will not appear in the
 final text.
 
 Coq, on the other hand, requires a full-stop terminator at the end of
-each line, so @kbd{C-c C-.} is the key binding used to turn on
+each line, so @kbd{C-c .} is the key binding used to turn on
 electric terminator.  If you don't know what the terminator character
 is, you can find the option anyway on the menu:
 @code{Proof-General -> Quick Options -> Processing -> Electric Terminator}

**Comment by erikmd** [comment]
Thanks for reporting this!
EMD
