### ISSUE TITLE
How does one require proof-shell?

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#14]
I'm writing a plugin that depends on variables in `proof-shell.el`. Unfortunately, `require`ing causes an error:

`mapcar: Symbol’s value as variable is void: nil-completion-table`

I found this bit in the source:

``` lisp
;; NB: completion table is expected to be set when proof-script
;; is loaded!  Call `proof-script-add-completions' to update.

(unless noninteractive ; during compilation
  (eval-after-load "completion"
  '(proof-add-completions)))
```

What’s the proper procedure?

**Comment by Matafou** [comment]
Dunno.

**Comment by DavidAspinall** [comment]
Some prover-specific variable names are generated from the proof 
assistant name in a convoluted way.  You probably want to do something 
like this:

    (require 'proof-site)
    (proof-ready-for-assistant 'coq)
    (require 'proof-shell)

- D.

On 24/11/2015 02:58, Clément Pit--Claudel wrote:
> I'm writing a plugin that depends on variables in |proof-shell.el|.
> Unfortunately, |require|ing causes an error:
>
> |mapcar: Symbol’s value as variable is void: nil-completion-table|
>
> I found this bit in the source:
>
> ;; NB: completion table is expected to be set when proof-script
> ;; is loaded! Call `proof-script-add-completions' to update.
>
> (unless noninteractive; during compilation
>    (eval-after-load"completion"
>    '(proof-add-completions)))
>
> What’s the proper procedure?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProofGeneral/PG/issues/14>.
>

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by cpitclaudel** [comment]
Thanks David!

**Comment by cpitclaudel** [comment]
@DavidAspinall This only works partially, actually. My setup code is the following:

```elisp
(require 'proof-site nil t)
(proof-ready-for-assistant 'coq) ;; Required by proof-shell
(require 'pg-vars)      ;; `proof-shell-proof-completed'
(require 'proof-config) ;; `proof-fly-past-comments'
(require 'proof-shell)  ;; `proof-shell-available-p'
(require 'coq-syntax)   ;; `coq-tactics-db'
(require 'coq)          ;; `coq-insert-match'
```

With this, the byte-compiler still complains:

```
company-coq.el:1368:36:Warning: reference to free variable
    ‘coq-hyp-name-in-goal-or-response-regexp’
company-coq.el:3590:1:Warning: the function ‘coq-insert-match’ is not known to
    be defined.
```

I tried adding an eval-and-compile around that block, but I get plenty of surprising errors:

```
Wrong type argument: keymapp, nil
```

**Comment by cpitclaudel** [comment]
@DavidAspinall Another issue with this is that it displays the splash screen, so users putting `(require 'company-coq) in their `.emacs` will always see the splash screen.

**Comment by DavidAspinall** [comment]
That sounds undesirable/wrong, I suspect some dependencies have been 
broken somewhere.  Can you run the autotest script "make test.coq"? 
These tests used to work smoothly...   - D.


On 07/01/2016 23:12, Clément Pit--Claudel wrote:
> @DavidAspinall <https://github.com/DavidAspinall> Another issue with
> this is that it displays the splash screen, so users putting |(require
> 'company-coq) in their|.emacs` will always see the splash screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProofGeneral/PG/issues/14#issuecomment-169836925>.
>


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by cpitclaudel** [comment]
Indeed, the tests fail: they open an Emacs window with the following message: 

```
Welcome to  Proof General!
mapcar: Symbol’s value as variable is void: nil-completion-table
```

**Comment by cpitclaudel** [comment]
This was fixed a while ago
