### ISSUE TITLE
better apps icons support

### ISSUE THREAD

**Issue by RBKreckel** [ProofGeneral/PG#141]
ProofGeneral's PNG icons should go into an apps subdirectory of the hicolor theme's resolution-specific subdirectories, i.e. into directory /usr/share/icons/hicolor/48x48/apps/ and not into /usr/share/icons/hicolor/48x48/. This is how hicolor's index.theme file specifies it! (As a reference, c.f. [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).) ProofGeneral's current install location lacks this subdirectory, which is why they won't be picked up from there. Instead, the proofgeneral.png icon is picked up from /usr/share/pixmaps/. (This location is for compatibility with applications not looking in $XDG_DATA_DIRS/icons/hicolor/, I'm not aware which applications need this.)

Here is a patch for ProofGeneral's top-level Makefile:
```
--- a/Makefile
+++ b/Makefile
@@ -163,14 +163,12 @@ INFODIR=${PREFIX}/share/info
 install: install-desktop install-elisp install-bin install-init
 
 install-desktop:
-       mkdir -p ${DESKTOP}/icons/hicolor/16x16
-       cp etc/desktop/icons/16x16/proofgeneral.png ${DESKTOP}/icons/hicolor/16x16
-       mkdir -p ${DESKTOP}/icons/hicolor/32x32
-       cp etc/desktop/icons/32x32/proofgeneral.png ${DESKTOP}/icons/hicolor/32x32
-       mkdir -p ${DESKTOP}/icons/hicolor/48x48
-       cp etc/desktop/icons/48x48/proofgeneral.png ${DESKTOP}/icons/hicolor/48x48
-       mkdir -p ${DESKTOP}/pixmaps
-       cp etc/desktop/icons/48x48/proofgeneral.png ${DESKTOP}/pixmaps
+       mkdir -p ${DESKTOP}/icons/hicolor/16x16/apps
+       cp etc/desktop/icons/16x16/proofgeneral.png ${DESKTOP}/icons/hicolor/16x16/apps
+       mkdir -p ${DESKTOP}/icons/hicolor/32x32/apps
+       cp etc/desktop/icons/32x32/proofgeneral.png ${DESKTOP}/icons/hicolor/32x32/apps
+       mkdir -p ${DESKTOP}/icons/hicolor/48x48/apps
+       cp etc/desktop/icons/48x48/proofgeneral.png ${DESKTOP}/icons/hicolor/48x48/apps
        mkdir -p ${DESKTOP}/applications
        cp etc/desktop/proofgeneral.desktop ${DESKTOP}/applications
        mkdir -p ${DESKTOP}/mime-info

```
And while at it, could we, please, get some higher-res icons as well? The default one is 48x48 and looks quite blurry. I suggest to add sizes 64x64 and 128x128 in order for it to look pretty on modern desktop environments. Pretty please.   ;-)

**Comment by cpitclaudel** [comment]
This all looks good, thanks!  Do you want to open a pull request?

**Comment by RBKreckel** [comment]
Must I open a pull request? Hmm, I'ld prefer to read up on how to use GitHub later on... (I only recently joined.)   ;-)

**Comment by cpitclaudel** [comment]
No need for a github style pull request, if you don't feel comfortable with those :) If you can push changes to another repo, I can easily merge them.

**Comment by cpitclaudel** [comment]
That's fine too; do you want to send patches to the PG mailing list?

**Comment by RBKreckel** [comment]
Not really. Is my issue report in any way unclear?

**Comment by erikmd** [comment]
@RBKreckel thanks for your report!

> Is my issue report in any way unclear?

I think it is very OK.

@cpitclaudel feel free to assign me to the issue if you want me to prepare a PR.

Best wishes!

Erik

**Comment by cpitclaudel** [comment]
> Is my issue report in any way unclear?

No, it's quite clear :) I just don't have much time these days, so the fastest way to get things fixed is to send patches :)

> @cpitclaudel feel free to assign me to the issue if you want me to prepare a PR.
Thanks!

**Comment by hendriktews** [comment]
I generated the 64 and 128 icons simply with gimp. I believe the quality of the icons could be improved if we simplify the original picture a bit.

@cpitclaudel @yoshihiro503 Do you have contact to the original author of the new Proof General image? Maybe he would be interested in improving the icons?

@RBKreckel thanks for the patch and the hints.

**Comment by erikmd** [comment]
Thank you @hendriktews!

**Comment by RBKreckel** [comment]
Thanks for applying!
