### ISSUE TITLE
coq-compile-before-require too zealous

### ISSUE THREAD

**Issue by vbgl** [ProofGeneral/PG#145]
When evaluating the following snippet, proofgeneral (only when `coq-compile-before-require` is set) fails with the following error:
> Cannot find library True in loadpath

```coq
Definition Require := True.
```

ProofGeneral 4.4, Coq 8.5pl3.

**Comment by hendriktews** [comment]
> Definition Require := True.

Thanks for the report. This problem has been fixed recently.

Hendrik
