### ISSUE TITLE
Indentation of (foo := bar) lists is unfortunate

### ISSUE THREAD

**Issue by Ptival** [ProofGeneral/PG#147]
The following snippet is indented thusly by PG:

```
apply Foo with
(v1 := e1)
  (v2 := e2)
  (v3 := e3).
```

It'd be nice if the last three lines were aligned with each other (I don't care where).

Sorry for the nitpicking!

**Comment by Matafou** [comment]
Should be fixed by f8a4f52. Hopefully I didn't break anything else...
