### ISSUE TITLE
Unused regexps in coq/coq.el

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#151]
These regexp definitions appear to be unused:

`(defvar coq-shell-outline-regexp coq-goal-regexp)`
`(defvar coq-shell-outline-heading-end-regexp coq-goal-regexp)`

**Comment by Matafou** [comment]
Hi,
This is part of an experience that I did not finish yet. You can remove it.
The idea is to pilot outline regex in goals buffer from the scripting buffer.

**Comment by psteckler** [comment]
Thanks, I'll remove it from my fork; someone may want to do the same in PG master.
