### ISSUE TITLE
example-utf8.v doesn't load

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#159]
The file `coq/ex/example-utf8.v` doesn't appear to load as is.

The `Load` command near the beginning can be changed to:

  `Require Import Utf8.`

and things go well thereafter. That works for PG master and xml-protocol.

**Comment by cpitclaudel** [comment]
Do you want to push a fix to master?

**Comment by psteckler** [comment]
Oh, I'd forgotten I have privileges here. 

Sure, I can do that.

**Comment by cpitclaudel** [comment]
Thank you :)

**Comment by psteckler** [comment]
Done.
