### ISSUE TITLE
cursor is covering up my code when used in the terminal

### ISSUE THREAD

**Issue by adnelson** [ProofGeneral/PG#16]
When I'm using emacs in windowed mode, everything seems fine. However, when in the terminal, Proof General's cursor (indicating where it is in the code) covers up the first two characters of the line it's on.

![screen shot 2015-12-08 at 4 24 00 pm](https://cloud.githubusercontent.com/assets/5091511/11670601/74d64fb8-9dc8-11e5-9004-ccb559c53e54.png)

This looks like a bug, but perhaps it's some sort of setting?

**Comment by cpitclaudel** [comment]
It's an Emacs setting (`overlay-arrow-string`). You can get rid of the arrow with `(setq overlay-arrow-string "")`. Does that help?

**Comment by adnelson** [comment]
That's helpful! Thanks :)
