### ISSUE TITLE
Feature request: different key-binding for electric terminator mode

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#160]
I'm relaying a feature request given to me by INRIA.

Apparently, the default key-binding for electric-terminator-mode, `C-c .`, is too easy to enter by mistake. The request is to choose some other key-binding.

**Comment by erikmd** [comment]
@psteckler
Indeed, I sometimes found myself with electric-terminator-mode toggled not on purpose.
Do you think `C-c C-a .` would be OK?
Cc @cpitclaudel @Matafou

**Comment by cpitclaudel** [comment]
Do we have other state-changing keybindings on C-c C-a? If not, 'd just vote for getting rid of that keybinding.  I'd expect people to use it either always, or never.

**Comment by erikmd** [comment]
> Do we have other state-changing keybindings on C-c C-a?

No.

> If not, 'd just vote for getting rid of that keybinding. I'd expect people to use it either always, or never.

Indeed, that makes sense. (and if need be, users that would really use this key-binding on a regular basis could re-enable the key-binding in their own config)

If you want I can commit this removal.

**Comment by cpitclaudel** [comment]
:+1:, though let's wait for @Matafou

**Comment by erikmd** [comment]
BTW, I've just realized there's another alternative to electric terminator: double-hit (see documentation excerpt below). Even if it is still tagged as experimental, it appears to be a nice feature!

> coq-double-hit-enable is a variable defined in `coq.el'.
>
> Documentation:
> * Experimental: Whether or not double hit should be enabled in coq mode.
> A double hit is performed by pressing twice a key quickly. If
> this variable is not nil, then 1) it means that electric
> terminator is off and 2) a double hit on the terminator act as
> the usual electric terminator. See `proof-electric-terminator'.

**Comment by Matafou** [comment]
I have no idea if people do switch electric-terminator often. If yes they
have or should probably change this shortcut Imho. The other users of this
option have set it permanently.

Yes double hit is useful to me (didn't use it for some time though). I
guess it is one of the numerous little tricks I never took time to
advertise...

P


Le jeu. 2 mars 2017 à 22:18, Erik Martin-Dorel <notifications@github.com> a
écrit :

**Comment by erikmd** [comment]
@Matafou
> I have no idea if people do switch electric-terminator often. If yes they have or should probably change > this shortcut Imho. The other users of this option have set it permanently.

So to recap (just to be sure ;), do you also vote for removing the `C-c .` shortcut?

> Yes double hit is useful to me (didn't use it for some time though). I guess it is one of the numerous little tricks I never took time to advertise...

Yes Indeed! Maybe we could post such tips and tricks in PG's blog https://proofgeneral.github.io/news/ and/or in the user manual https://proofgeneral.github.io/doc/userman/ProofGeneral_10/ ...

**Comment by Matafou** [comment]
2017-03-03 9:43 GMT+01:00 Erik Martin-Dorel <notifications@github.com>:

> @Matafou <https://github.com/Matafou>
>
> I have no idea if people do switch electric-terminator often. If yes they
> have or should probably change > this shortcut Imho. The other users of
> this option have set it permanently.
>
> So to recap (just to be sure ;), do you also vote for removing the C-c .
> shortcut?
>

Yes.


> Yes double hit is useful to me (didn't use it for some time though). I
> guess it is one of the numerous little tricks I never took time to
> advertise...
>
> Yes Indeed! Maybe we could post such tips and tricks in PG's blog
> https://proofgeneral.github.io/news/ and/or in the user manual
> https://proofgeneral.github.io/doc/userman/ProofGeneral_10/ ...
>

I am not sure which one is the most popular reading... It must be close! :-)

Kidding apart maybe we can start a "tip" section in github's wiki? Once it
is filled with some content we can advertise on coq-club.

Pierre

**Comment by erikmd** [comment]
OK so I'll take care of this little key-binding change.

> maybe we can start a "tip" section in github's wiki? Once it is filled with some content we can advertise on coq-club.

Yes, that's a pretty good idea!

**Comment by erikmd** [comment]
Done; I've also updated the CHANGES file.

**Comment by cpitclaudel** [comment]
Thanks Erik!
