### ISSUE TITLE
Lack for proof refresh after clicking on menu Coq > Options > [Un]Set modifiers.

### ISSUE THREAD

**Issue by erikmd** [ProofGeneral/PG#161]
When we are doing a proof needing "implicit arguments inspection" or so, the PG menu Coq > Options > etc. is not very user-friendly as we need to type `C-c C-p` i.e. `(proof-prf)` to update the goal accordingly.
I propose to integrate the call to `(proof-prf)` after processing these options.
As a result, this menu would be as handy as CoqIDE's "View" menu.

**Comment by Matafou** [comment]
Did you try C-u <your shortcut for Print, Check or Show>?

I find it more useful than setting options on and off all the time.

P

Le jeu. 2 mars 2017 à 22:28, Erik Martin-Dorel <notifications@github.com> a
écrit :

When we are doing a proof needing "implicit arguments inspection" or so,
the PG menu Coq > Options > etc. is not very user-friendly as we need to
type C-c C-p i.e. (proof-prf) to update the goal accordingly.
I propose to integrate the call to (proof-prf) after processing these
options.
As the result, this menu would be as handy as CoqIDE's "View" menu.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ProofGeneral/PG/issues/161>, or mute the thread

**Comment by erikmd** [comment]
Hi @Matafou,
Thanks for the tip! I didn't know we can do `C-u C-c C-a C-p` `C-u C-c C-a C-c`, `C-u C-c C-a C-s` 👍 
However, I keep thinking that the Options menu (which provides more settings than just "Set Printing All") is not user-friendly enough due to the need for an extra keystroke `C-c C-p`.
Still, I realize that the patch to address this cannot consist in merely calling `(proof-prf)`, because if there is no proof in progress, sending `Show.` will lead to "Error: No focused proof (No proof-editing in progress)". Do you have some idea to overcome this? Maybe by adapting part of your PR #156 ?
Cheers, Erik

**Comment by Matafou** [comment]
2017-03-03 9:30 GMT+01:00 Erik Martin-Dorel <notifications@github.com>:

> Hi @Matafou <https://github.com/Matafou>,
> Thanks for the tip! I didn't know we can do C-u C-c C-a C-p C-u C-c C-a
> C-c, C-u C-c C-a C-s 👍
> However, I keep thinking that the Options menu (which provides more
> settings than just "Set Printing All") is not user-friendly enough due to
> the need for an extra keystroke C-c C-p.
>
You are right, but my point is that we almost never want to really set
these options permanently. We want to see the goal or the result of one
query with this options on and then go back to normal view.

Anyway you are right it would be better to update the goals buffer when the
option is set.

Still, I realize that the patch to address this cannot consist in merely
> calling (proof-prf), because if there is no proof in progress, sending
> Show. will lead to "Error: No focused proof (No proof-editing in
> progress)". Do you have some idea to overcome this? Maybe by adapting part
> of your PR #156 <https://github.com/ProofGeneral/PG/pull/156> ?
> Cheers, Erik
>
Insert a "Show." each time we see a "Set Printing foo." command and we are
in proof mode? This is probably possible yes. One more list-action hook...

P.

**Comment by Matafou** [comment]
Was a two-liner.

**Comment by erikmd** [comment]
Neat! Thank you @Matafou :-) I've tested your patch in the [official-master](https://github.com/ProofGeneral/PG/tree/official-master) branch and it works smoothly, so feel free to merge it in master!

**Comment by erikmd** [comment]
Wait... shouldn't the "u" of unset be capitalized?

**Comment by erikmd** [comment]
Hi @Matafou,
I confirm that `(string-match "\\(S\\|uns\\)et\\s-+Printing" "Unset Printing All)` does not work if the user has run `(setq case-fold-search t)` beforehand... so we need an upper-case "U" here.
Kind regards, Erik

**Comment by erikmd** [comment]
@Matafou 
I've just pushed a small commit in branch official-master that fixes this remaining issue.
If you are OK with this you can merge in master.

**Comment by Matafou** [comment]
Thanks for the fix!
P.

2017-03-03 16:55 GMT+01:00 Erik Martin-Dorel <notifications@github.com>:
