### ISSUE TITLE
Text from Coq with "Error" overwrites preceding text in *response* buffer

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#173]
This issue arises in bug 5148 on the Coq Bugzilla:
  https://coq.inria.fr/bugs/show_bug.cgi?id=5418

Coq produces this text:

> In nested Ltac calls to "g", "f" and "intro (ident)", last call failed.
> Error: No product even after head-reduction.

In the response buffer, we see only the second line. There is a call the `pg-response-display` with the entire text, but then there's a subsequent call to `pg-response-display-with-face` with just the second line containing `Error`, so the user never sees the full message.

In `proof-shell-handle-error-or-interrupt`, the default case for the `cond` contains calls to both `proof-shell-handle-delayed-output` and `proof-shell-handle-error-output`. Both seem to be called in this example.

Since the first of these prints the entire message, the second one should not be called. I'm unsure of the logic needed to make that happen, tho.

**Comment by psteckler** [comment]
Maybe it's as simple as only making the call to `proof-shell-handle-error-output` in the else-branch of the preceding `if` (which should be a `when`, otherwise).

**Comment by Matafou** [comment]
The usual fix on pg side is to add the start of the message in regexp coq-error-regexp. I will fix this in pg master.

I consider coq should format error messages in more uniform way. I usually fix this kind of thigs directly in coq but since there is a bug report I will ask there if it is ok. The pg fix is needed anyway for people using coq8.6.

**Comment by Matafou** [comment]
Done on pg side.

**Comment by psteckler** [comment]
I applied the fix to PG/xml for consistency, even though that regexp is not used for identifying error output. The regexp is still used in a couple of other places.

**Comment by ejgallego** [comment]
> I consider coq should format error messages in more uniform way. I usually fix this kind of thigs directly in coq but since there is a bug report I will ask there if it is ok. The pg fix is needed anyway for people using coq8.6.

Indeed as I commented in the Coq bug report, there used to be a non-uniformity on the Coq side, due to duplicated error printing paths. I resolved this uniformity in a recent PR, however it took the wrong side. Working on a fix, in 8.7 all errors in `-emacs` mode will be reported with the markers.

**Comment by ejgallego** [comment]
Ok, after coq/coq#530 is merged, all error should have the proper error markers, it not, let me know.

**Comment by Matafou** [comment]
Thanks!

2017-03-31 20:49 GMT+02:00 Emilio Jesús Gallego Arias <
notifications@github.com>:
