### ISSUE TITLE
Expansion triggers at unfortunate times when using Evil-mode

### ISSUE THREAD

**Issue by mmalvarez** [ProofGeneral/PG#174]
When exiting insert mode in evil-mode, PG's abberviation-expansion triggers automatically, which can be inconvenient (e.g. if the last character I typed was an A it will always get expanded to AUTO).

The issue is also discussed [here](https://github.com/cpitclaudel/company-coq/issues/160) in the issues for company-coq, but appears to be a PG problem. One workaround presented there was to disable the abbreviation expansion entirely, but it would be great to have a way to keep the abbreviation expansion at more appropriate times.

**Comment by cpitclaudel** [comment]
Ok, I got to investigate this further with @tchajed :) This is an issue with Evil, and it was made customizable in https://github.com/emacs-evil/evil/commit/c42dd5bed9fa400cd54de7236b4483b041554e4c

**Comment by cpitclaudel** [comment]
So basically just putting `(setq evil-want-abbrev-expand-on-insert-exit nil)` before loading evil should work.

**Comment by tchajed** [comment]
@mmalvarez: apologies if you already knew this, but you'll have to put that snippet in `dotspacemacs/user-init`; you can customize `evil-want-abbrev-expand-on-insert-exit` but evil won't pick up the customized value (which is a bug in evil, they shouldn't load the variable once and then not respond to changes, especially if they allow it to be customized).

**Comment by sindikat** [comment]
@tchajed Is there a justification why this variable is explicitly loaded only once? Maybe tracking it reduces performance or something. Anyway, should we open an issue then? [Evil](https://github.com/emacs-evil/evil) lives on GitHub now, not Bitbucket anymore.
