### ISSUE TITLE
/usr/bin/proofgeneral is not executable by default?

### ISSUE THREAD

**Issue by wilbowma** [ProofGeneral/PG#177]
When I build using `make PREFIX=/usr install`, the executable for `proofgeneral` is not make executable. Of course, I could change this myself, but it seems like something `make install` should do. Is this by design or am I missing something?

**Comment by cpitclaudel** [comment]
I don't think many people use this installation medium any more; instead, we'd like to move to making Proof General a proper Emacs package (you can help! https://github.com/ProofGeneral/PG/pull/157).  That could be why you're running into this issue. (I'd be happy to merge a fix for the problem you describe, though, of course :)

**Comment by wilbowma** [comment]
Aha! I'm maintaining the ArchLinux package for proofgeneral and a user reported this as a bug: https://aur.archlinux.org/packages/proofgeneral. I'll try to send a PR

**Comment by hendriktews** [comment]
The proofgeneral shell script in the Proof General repo is
leftover from ancient days. I don't think you want to install
this for your users. For Debian I substituted this with a simple
script that only starts emacs:

    #!/bin/sh

    if emacs --version | grep -q 'Emacs 2[45]' ; then 
        emacs -f proof-splash-display-screen $*
    else 
        if emacs25 --version | grep -q 'Emacs 2[45]' ; then 
            emacs25 -f proof-splash-display-screen $*
        else 
            emacs24 -f proof-splash-display-screen $*
        fi
    fi

Hendrik

**Comment by wilbowma** [comment]
What's the downside of installing it? It seems to work just fine.

**Comment by wilbowma** [comment]
I'm pretty confused; it looks like `bin/proofgeneral` is executable in the repo and the `Makefile` uses `cp -p`. It seems like it should be installed executable by `make install`.

**Comment by hendriktews** [comment]
> What's the downside of installing it? It seems to work just fine.

I don't know any real reason why you should not install it. It's
just that it contains quite a bit of unnecessary code that is not
maintained anymore ...

**Comment by hendriktews** [comment]
> It seems like it should be installed executable by make
> install.

IMHO, instead of fixing make install, we should remove
bin/proofgeneral from the repository.

Hendrik

**Comment by Matafou** [comment]
I agree with @hendriktews we should remove it.
