### ISSUE TITLE
compile-before-require does not use _CoqProject options or Makefile

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#18]
I have been experimenting with modularizing a large Coq source file into multiple smaller source files.  In conjunction with this, I would like to use the Coq->Settings->Compile Before Require option, but this always fails because my files require -impredicative-set, which is present at the head of my _CoqProject file, but which PG does not notice.  How can I get PG to either pick up the proper settings from _CoqProject, or use the coq_makefile-generated Makefile to handle compile-before-require properly?

Relatedly - when editing a file that is Required by another, where that requirer is in proof mode in PG, PG asks to retract the requirer file and then starts up proof mode in the requiree file.  Is there a way I can control this more precisely?  One side-effect is that, since I am using 3 separate panes/frames/windows for proof mode, a retract and restart of Coq (because there is no way to save pane/frame/window size and position info) throws things out of wack such that I have to then spend some time reconfiguring things.  Could PG just revert the other file to just prior to the problematic Require, leaving the panes/frames/windows as they are already configured, and allow me to edit the requiree file?  In most cases, I don't really want to enter proof mode in the requiree file - I'm just making some trivial fix.  If I want to enter proof mode in that requiree file, I can do something like PG toolbar Goto in that file.

**Comment by cpitclaudel** [comment]
The whole compile-before-require code is a contribution of Hendrik Tews. @Matafou, do you have any experience with this code? Otherwise, one of us should ping him about this.

**Comment by Matafou** [comment]
Hi, Iit should work as it is. I will have a look at it.

In principle,_CoqProject is read and interpreted by pg. The code for
checking it is shared I believe.

Be careful That if you change the _CoqProject you need to reload files (the
project file is read when open a file).

P.

2015-12-12 19:06 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by jonleivent** [comment]
I would have thought it would work as well, because PG is certainly picking up my _CoqProject settings for proof mode files (passing them to the coqtop subprocess).  Just not for (re)compiles.

I typically do not change the _CoqProject during a single PG session.

**Comment by jonleivent** [comment]
I found a workaround to the fact that compile-before-require is not picking up the _CoqProject settings: set coq-compile-command to "make %o".  This will unfortunately ask me every time if that is the command I want and pop up the *compilation* buffer, but is still better than the alternative.

I also noticed that if the compilation fails due to an error (in this case, it couldn't even find coqc because the subshell wasn't using my .bashrc PATH settings), PG will not notice, and instead process the Require using the old file.  Perhaps Coq should check the exit value of the compile subshell?

**Comment by Matafou** [comment]
Mmh are you using the prallel compilation? I have not testes this for some
time. It may be broken.

I don't have these bugs in sequential compilation.

P.

2015-12-13 0:08 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by jonleivent** [comment]
No - sequential only - Coq->Settings ->Compile Parallel in Background is not set.  I do have Coq->COQ PROG (ARGS)->Use Project File set.

**Comment by jonleivent** [comment]
Could it be that the particular args lines at the top of my _CoqProject file is causing the problem?  I actually have two:

-R . Wavl
-arg -impredicative-set

**Comment by Matafou** [comment]
Hi, indeed there was a bug. Should be fixed. Please test. I will refactor
part of it soon though.
P.



2015-12-13 17:52 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by Matafou** [comment]
Refactoring done. Feel free to reopen.
thanks!
P.

**Comment by jonleivent** [comment]
Just tried it, and it works!  Thanks again, Pierre!

Interestingly, I still had Coq->Settings->Confirm External Compilation checked, but PG never bothered to confirm.  Not that I mind - it did the right thing, after all.
