### ISSUE TITLE
Tab completion in proof-prog-name-ask is broken

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#187]
When set proof-prog-name-ask and tab-complete a binary, there's a trailing space if there are no binaries with the same name as a prefix.  PG then rejects this name-with-a-trailing-space as invalid.  I think PG should instead strip trailing spaces from the program name (and just not support the case where someone renames their Coq binary to have a trailing space).

**Comment by Matafou** [comment]
Fixed. Thanks!
P.
