### ISSUE TITLE
Proof General Stuck 

### ISSUE THREAD

**Issue by mukeshtiwari** [ProofGeneral/PG#206]
Today I updated my proof general after one year. I accidentally wrote this wrong code, and pressed C-c C-n.  Proof General is stuck rather that showing parse error. The situation is even worse with company-coq so I had to uninstall it. 
  
Instance showColor : Show color :=
  {
    show :=
      fun (c : color) =>
        match c with
        | Red => "Red"
        | Blue => "Blue"
        | _ => "Green"
        end. 

![coq_error](https://user-images.githubusercontent.com/1135077/31537696-c668baf6-b04e-11e7-9cd1-f943a4cec6e7.png)

**Comment by cpitclaudel** [comment]
Indeed, that can happen — Coq waits for a complete sentence, and we think we sent one, so we wait for it to respond.
You can break the deadlock using `C-c C-c`.

Feel free to reprot the company-coq issue — it shouldn't make things worse.

**Comment by mukeshtiwari** [comment]
@cpitclaudel Thank you for the reply.
