### ISSUE TITLE
Some notations conflict with SMIE.

### ISSUE THREAD

**Issue by Mbodin** [ProofGeneral/PG#209]
Hi,
I am experiencing slowness from Coq. I used M-x toggle-debug-on-quit to understand where it comes from, and it seems to come from SMIE. It was previously disabled in my emacs.el using (setq coq-use-smie nil), but it seems that some changes in Proof General are now ignoring this option.

I am using the TLC library, which introduces the following notation:
```coq
Notation "'ifb' P 'then' v1 'else' v2" :=
  (if decide P then v1 else v2)
  (at level 200, right associativity) : type_scope.
```
But every time I am typing the “n” of “then” or the second “e” of “else”, Emacs freezes for a second. My hypothesis is that it looks for a “if”-token, but there is none in my code (only “ifb”). This unfortunately makes Emacs unusable in practice in my case. Is there an option to disable nonetheless this behaviour?

I guess that a side question would be to look wether it is possible for SMIE to cope with Coq notations? I imagine that this would be very difficult to do… ☹

Regards,
Martin Bodin.

**Comment by Matafou** [comment]
Done in master branch.

update pg and put this in your .emacs (notice the subtle change, it is an alist):

(setq coq-smie-user-tokens '(("ifb" . "if")))

Tell me if this solves your problem. It should also allow to use indetation correctly too.

**Comment by cpitclaudel** [comment]
Oooh, very nice!

**Comment by Mbodin** [comment]
Thank you very much! I confirm that it works right now.

To answer your questions, I am only a user of TLC, and I didn’t want to change the introduced notations. This makes my opinions on this particular notation choice not really relevant, I think. But I guess you are right and I should suggest Arthur to change his notation in the next release.

The file is ~1700 line long: there was a freeze of approximately one second each time I used such a token… which was frustrating enough. :-\

**Comment by Matafou** [comment]
Can you post the file please? I will try to see why it is slow.

Indentation is difficult for a language like Coq, even without dynamic notation...

I should also add a configuration disabling smie completely I guess.

**Comment by Mbodin** [comment]
Sure. The problematic file was this one: https://github.com/Mbodin/proveR/blob/master/low/Reval.v#L1419 I was working on one of the ifb/then/else of the function findVarInFrame3.
There are a lot of nested notations in this file: if smie is trying to parse it all without knowing the notations, I can imagine its difficulties. :-\

But it seems to work fine now with the new version of PG (and the added line in my .emacs.el) ☺
