### ISSUE TITLE
Incorrect indentation for tactics ending in ?

### ISSUE THREAD

**Issue by ichung** [ProofGeneral/PG#211]
Expected behavior: the two following proofs indent exactly the same way.

```
Goal forall m n : nat, n = n.
  intros m n.
  reflexivity.
Qed.

Goal forall m n : nat, n = n.
  intros m ?.
         reflexivity.
Qed.
```

Actual behavior: `reflexivity` in the second gets indented to the level of `m`, not to the level of `intros`.

Similar indentation misbehavior occurs for any tactic which ends in a `?`:

```
Goal True.
Proof.
  assert True as ?.
                auto.
                assumption.
Qed.
```

Putting a space between the `?` and period gives the correct indentation.

```
Goal forall m n : nat, n = n.
  intros m ? .
  reflexivity.
Qed.
```

**Comment by Matafou** [comment]
I don't see this bug. What version are you using please?

**Comment by ichung** [comment]
My mistake, I failed to run `make` after updating PG.
