### ISSUE TITLE
Coq warnings should not block evaluation

### ISSUE THREAD

**Issue by cstolze** [ProofGeneral/PG#219]
Example code:
```
Structure foo := mkFoo { a : Set; b : a -> a -> a }.
Canonical Structure foonat := mkFoo nat (fun x y => x + y).
Print foonat.
```
The second line triggers a warning:
```
<warning>
Warning: Projection value has no head constant: fun x y : nat => x + y in
canonical instance foonat of b, ignoring it.
[projection-no-head-constant,typechecker]</warning>
```
Note that coq does not fail and creates internally `foonat`, but proofgeneral acts as if the command failed, so it does not want to go further and it cannot process the third line. This problem does not occur in either coqtop or coqide.

**Comment by cpitclaudel** [comment]
Which version of Coq are you using? It works for me with 8.6.

**Comment by cstolze** [comment]
I am using Coq 8.7.0

**Comment by cstolze** [comment]
nvm I installed the github repo (I was using the Fedora package for proof general, v4.4), and now the bug is gone.
