### ISSUE TITLE
Support upcoming "bracket with goal selector" Coq feature

### ISSUE THREAD

**Issue by Zimmi48** [ProofGeneral/PG#220]
In coq/coq#6551, I'm introducing the possibility to use single-goal selectors, like `2:` in front of focusing brackets `{`. This requires support in editors as the sentence `2: {` doesn't end with a dot but should be considered as complete nonetheless. Fortunately, the change required to support this should be pretty small. For CoqIDE, it was a two-line change: https://github.com/coq/coq/pull/6551/files#diff-9e771f90bde949b1561c3caf201b4166.

**Comment by Matafou** [comment]
Thanks for submitting. It is less simple in PG because this has also an effect in indentation code but it seems doable.

**Comment by Matafou** [comment]
Please test current master branch. It seems to work.

**Comment by psteckler** [comment]
I will add this to PG/xml, once it's verified to work.

**Comment by Zimmi48** [comment]
It does. Thanks a lot! And the indentation looks better as well.

**Comment by Matafou** [comment]
travis failed on this commit but it seems to be dude to emacs compilation.

**Comment by psteckler** [comment]
I cherry-picked the commit in the PG/xml fork.

**Comment by psteckler** [comment]
With this change, does PG's undo (`C-c C-u`) work on a goal selector?

**Comment by Zimmi48** [comment]
If you mean on a goal selector + a bracket, yes, it works correctly.

**Comment by psteckler** [comment]
I tried the test-suite file in coq/coq#6551, and it doesn't quite work in PG/xml, after adding the commit here. I'll have to make some additional changes, it seems.

**Comment by Zimmi48** [comment]
The test-suite file example is a bit extreme as it also tests stuff that is failing. That being said, it works both with legacy PG and CoqIDE (although it allowed me to discover https://github.com/coq/coq/issues/6587 while cooking it).

**Comment by Zimmi48** [comment]
@psteckler Is there still an issue or should this be closed?

**Comment by psteckler** [comment]
@Zimmi48 The feature is supported in PG and PG/xml, so the issue can be closed.
