### ISSUE TITLE
Support new Printing All

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#226]
If coq/coq#6698 is merged, the Coq menu items with show all will no longer work, because the semantics of `Set Printing All` and `Unset Printing All` will have changed.

To make those menu items work, PG would have to store the current printing options, run `Set Printing All`, and restore those options. That may be more trouble than it's worth.

**Comment by Matafou** [comment]
Probably not worth indeed.

But I like the C-u prefix on Type/Check/About/Show which sets printing all just for the time of the command. Is there a simpler way of doing this?

**Comment by psteckler** [comment]
@Matafou I just proposed an idea in the PR: add commands `Save Printing Options` and `Restore Printing Options` on the Coq side, which would make the `C-u` functionality easy to implement in PG.

**Comment by psteckler** [comment]
It looks like PG won't require any changes due to the PR mentioned.
