### ISSUE TITLE
Is there a way to make Double Hit Electric Terminator do an indent after the newline?

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#23]
I am experimenting with ways of speeding up my Coqing (such as using company-coq) - and Double Hit Electric Terminator seems worth a try.  But, now I have to hit Tab to indent after the newline.  Is there a setting to get Double Hit to do the indent?

Also, speaking of indents - I know I mentioned this once before, but the extra indenting after the first line after a let/match clause is really bugging me - is there a way I can turn that off?

**Comment by cpitclaudel** [comment]
Indeed, it should probably indent.

It probably happens in coq.el (`coq-terminator-insert`) and proof-script.el (`proof-assert-electric-terminator`). Do you want to have a look?

Clément.

**Comment by jonleivent** [comment]
It looks like proof-assert-electric-terminator does the newline at its end - but only when proof-next-command-on-new-line or coq-one-command-per-line is set.  So, if I turn these both off (the first is off by default, but not the second) - then I can use the electric terminator (with or without double hit), and I have to do my own newline - which will do the indenting I want.  Great!  That way, if I want "tac1. tac2. tac3." on one line, I can do that, too.

I shall customize coq-one-command-per-line to nil.

**Comment by cpitclaudel** [comment]
Cool. I'll close this, and it'll serve as a reference for future visitors :)
