### ISSUE TITLE
Upon error, PG/xml stops at the end of the last succeeding proof command?

### ISSUE THREAD

**Issue by jwiegley** [ProofGeneral/PG#232]
@psteckler When evaluating code with `C-c C-RET`, I'm used to the cursor coming to rest at the point where an error has been detected. With the new PG/xml code, it seems to stop at the end of the last completed proof command, which may take the cursor a fair distance from where the error occurred, requiring that it be relocated after every attempt.

**Comment by psteckler** [comment]
This behavior is meant to be a feature. With async, if PG encounters an error, it continues processing the script so it can send the next proof to coqtop. CoqIDE works the same way, I believe.

The header line shows errors in red, and PG supports the Emacs next-error keystrokes, so it should be not too difficult to navigate to the error locations.

Can you think of a better interaction?

**Comment by jwiegley** [comment]
I think that point should be located to the beginning of the first detected error, so that I can fix it without having to manually move point to that location after each attempt.

**Comment by psteckler** [comment]
> I think that point should be located to the beginning of the first detected error

I'll have to think about that. In general, I'm not so fond of auto-warping the editor point, or similarly, the mouse cursor, especially when one keystroke or mouse-click will get me there.

Maybe others have ideas here.

**Comment by jwiegley** [comment]
Well, it's already moving point from where it was. That is, if I'm halfway into a function (where I was editing), and I hit `C-c C-RET`, and the function fails to type check, it moves my point to the end of the preceding Proof block, taking my cursor away from where it was.

It's never one keystroke to get back to where I was, and I don't ever use the mouse.

Best approach then would be to have a customizable variable for the behavior:

 1. Leave point alone (never move it).
 2. Move point to beginning or end of first error.
 3. Move point to beginning or end of nearest preceding error.
 4. Move point to end of nearest succeeding proof (current behavior).

**Comment by psteckler** [comment]
In `async`, I'm actually seeing (1). If I introduce an ill-typed expression in an earlier proof, then proof-goto-point in a later proof, the point doesn't move, and processing continues. In `master`, I see (2) (and processing stops).

**Comment by erikmd** [comment]
I'm not 100% sure but I guess that your observations differ because you don't speak of the same feature.

Namely: John speaks of the behavior of `C-c C-RET` when only one Coq phrase is evaluated;
while Paul speaks of the beahvior of `C-c C-RET` when at least to Coq phrases (including a wrong one if you want) is evaluated.

**Comment by erikmd** [comment]
To be more specific, consider the following excerpt:

```
Definition f (n : nat) := n. (* first, evaluate this line *)

Definition bug1 := f false. (* point 1 *)

Definition bug2 := f false. (* point 2 *)
```

I think @jwiegley typed `C-c C-RET` at point 1, while @psteckler did it at point 2.

As described above, towards point 1, the behavior is (4) w.r.t. https://github.com/ProofGeneral/PG/issues/232#issuecomment-369696762; but towards point 2, the behavior is (1)

Does it make sense?

**Comment by psteckler** [comment]
> Does it make sense?

Yes, but what actually happens in this example is that going to point 2 results in a fail-value with state id 3, which is the state after `Definition f` has been defined.

What happens with the point depends on how Coq notifies PG of the error. If it's just a feedback, then PG just marks the error. If it's a fail-value with an earlier state, such that no subsequent state is valid, PG retracts to that earlier state. It's that second case that moves the point.

In the case that there's just a feedback, that's when you could have a choice whether to move the point. It's made more complicated by the fact that a fail-value is usually preceded by an error feedback.

So

**Comment by jwiegley** [comment]
Well, all I can say right now is that the current PG/xml is extremely undesirable. I find myself having to relocate point constantly. I've switched back to `master` for the time being, in order to get work done.

**Comment by erikmd** [comment]
Indeed that's true than when a single Coq phrase is sent (cf. point 1 in [my example](https://github.com/ProofGeneral/PG/issues/232#issuecomment-369717634)), it would be much more natural to bump to (the beginning of) the first error raised (cf. behavior (2) in [John's comment](https://github.com/ProofGeneral/PG/issues/232#issuecomment-369696762)). And I would even say that customizing this behavior is unneeded.

@psteckler, could you take a look at this change? This would have the benefit to increase usability, and restore some compatibility w.r.t. the behavior of `master` (proof-shell) PG. Feel free to open a PR.
Kind regards, Erik

**Comment by psteckler** [comment]
Let's see, if I simply set the Emacs point on an error feedback, other code seems to move the point away.

How about if I treat an error feedback as a fail-value, so that there's a retraction to where the error occurs? That moves the point, but also stops the processing of script lines below. That is, you lose the  async processing when an error occurs.

That's different than what CoqIDE does. So I think this should be an option.

**Comment by jwiegley** [comment]
Hmm... I think that during development I wouldn't mind if asynchronous process suddenly halts, because the fixes I apply might invalidate later work, and it conserves battery to avoid extra async processing for work beyond `(point)` that I may not want (it really becomes a kind of speculation at that point).

**Comment by psteckler** [comment]
Great, I'm working on it.

**Comment by psteckler** [comment]
Created #238.

This needs testing, and sometimes I saw some odd behavior if I ran examples twice. I'm here for only a couple more days, so I wanted to submit something to work with.

**Comment by erikmd** [comment]
> Created #238.
> This needs testing, and sometimes I saw some odd behavior if I ran examples twice. I'm here for only a couple more days, so I wanted to submit something to work with.

After the tests Paul and I performed up to now, PR #238 seems to fully solve #232, regarding the reported issues about retraction and error messages. The user experience should be enhanced in both configs (with new option `coq-errormsg-as-failure` set or unset).
I thus plan to merge this PR tomorrow in `async`.

**Comment by erikmd** [comment]
Done; closing #232 (auto-close did not work as `async` is not the default-HEAD branch for the moment)
