### ISSUE TITLE
PG gets confused when there is another frame visible at start

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#25]
I am trying out using the speedbar (Emacs->Options->Show/Hide->Speedbar) with PG, and noticed that when the speedbar is visible, PG can't start (as when doing a process-next-proof-command to start it up) properly - it gets an error about "Attempt to delete a surrogate minibuffer frame".   I'm using PG in 3-windows/panes (but one one frame) mode.

At other times, when there are multiple Emacs frames, I have noticed that PG gets confused about which frame to use - sometimes preferring the frame not in focus when it is started (and deleting the other frame).  I think this occurs when PG is started (as above) in the non-first frame.

This is using emacs 24.4.1, with PG e0e2cea and company-coq (although I am pretty sure it happens without company-coq as well).

**Comment by Matafou** [comment]
I have this bug too with speedbar. Probably a bug in the code that splits
the frame at start.

Concerning the frame to use, currently pg is supposed to chose the frame
where *response* and *goals* are already displayed. This is not very
convenient in some situations but it is in some others.

Reusing the frame from which pg was started is not necessarily better. The
user may have change the scripting buffer/frame several times, close the
intitial frame, etc.

P.




2016-01-05 1:03 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by Matafou** [comment]
Bug with speedbar should be fixed. And less frames should be disappearing mysteriously.
This was an old bug in generic code.
Thanks!
