### ISSUE TITLE
Indentation is wrong after [exists]

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#29]
This is the default indentation (on `TAB`ing the document).  The proof script should be indented by 2 spaces.

```coq
Goal exists x, x = true.
                 evar (a : bool).
                 exists a.
                 refine (unit_rec (fun s => unit_rec _ _ s = _) _ tt).
                 exact true.
```

**Comment by cpitclaudel** [comment]
I think that's a known issue with any `Goal` form following a quantifier actually:

```
Goal forall t: bool, t = t.
                    reflexivity.
Qed.
```

**Comment by Matafou** [comment]
Yes it is known and a bit hard to fix in general.

Workaround: put Proof at start of a proof.

The reason it is hard to fix is that it needs to detect if a command is a
proof start or not. It is not trivial.

P

**Comment by Matafou** [comment]
But I will try to have something less wrong anyway.

FYI if you don't like indentation induced by "Proof" you can set

(setq coq-indent-proofstart 0)

P.

2016-01-13 22:36 GMT+01:00 Pierre Courtieu <pierre.courtieu@gmail.com>:

> Yes it is known and a bit hard to fix in general.
>
> Workaround: put Proof at start of a proof.
>
> The reason it is hard to fix is that it needs to detect if a command is a
> proof start or not. It is not trivial.
>
> P
>
>
> Le mercredi 13 janvier 2016, Clément Pit--Claudel <

**Comment by Matafou** [comment]
Should be fixed.
Notice that in some ugly cases the "goal starting" property of a command will not be detected and indentation may be broken. Use "Proof" to workaround.
