### ISSUE TITLE
warning building latest version d3d7622

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#32]
jil@jess:~/git/PG$ make
****************************************************************
 Byte compiling... 
****************************************************************
make elc
make[1]: Entering directory '/home/jil/git/PG'
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (concat "/home/jil/git/PG/" (symbol-name d))) (quote (acl2 ccc coq hol98 isar lego hol-light phox pgshell pgocaml pghaskell generic lib contrib/mmm))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile coq/coq-par-compile.el
Source file `/home/jil/git/PG/coq/coq-system.el' newer than byte-compiled file

In coq-par-coqdep-arguments:
coq/coq-par-compile.el:463:11:Warning: coq-coqdep-prog-args called with 3
    arguments, but accepts only 0-2

In coq-par-coqc-arguments:
coq/coq-par-compile.el:471:11:Warning: coq-coqc-prog-args called with 3
    arguments, but accepts only 0-2

In end of data:
coq/coq-par-compile.el:1367:1:Warning: the function `coq--pre-v85' is not
    known to be defined.
Wrote /home/jil/git/PG/coq/coq-par-compile.elc
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (concat "/home/jil/git/PG/" (symbol-name d))) (quote (acl2 ccc coq hol98 isar lego hol-light phox pgshell pgocaml pghaskell generic lib contrib/mmm))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile coq/coq-seq-compile.el
Source file `/home/jil/git/PG/coq/coq-system.el' newer than byte-compiled file

In coq-seq-get-library-dependencies:
coq/coq-seq-compile.el:77:18:Warning: coq-include-options called with 3
    arguments, but accepts only 2

In coq-seq-compile-library:
coq/coq-seq-compile.el:116:12:Warning: coq-coqc-prog-args called with 3
    arguments, but accepts only 0-2

In end of data:
coq/coq-seq-compile.el:407:1:Warning: the function `coq--pre-v85' is not known
    to be defined.
Wrote /home/jil/git/PG/coq/coq-seq-compile.elc
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (concat "/home/jil/git/PG/" (symbol-name d))) (quote (acl2 ccc coq hol98 isar lego hol-light phox pgshell pgocaml pghaskell generic lib contrib/mmm))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile coq/coq-system.el
Wrote /home/jil/git/PG/coq/coq-system.elc
make[1]: Leaving directory '/home/jil/git/PG'
****************************************************************
 Finished.
****************************************************************

**Comment by cpitclaudel** [comment]
Hmm. Can you try `make clean; make`? I'm not seeing these.

**Comment by jonleivent** [comment]
Make clean does indeed change things, and perhaps also gives the reason.  Is there a cycle in the makefile?  Note the warnings of the attached file.
[makeout.txt](https://github.com/ProofGeneral/PG/files/92945/makeout.txt)

**Comment by cpitclaudel** [comment]
Good, at least my patch wasn't entirely broken :) Yes, there are circular dependencies between some of PGs files; I'm not sure when they started cropping up.

It's not that bad though; the cycles only matter when trying to do macroexpansion, which can be delayed. I'll open a separate report, thanks Jonathan!
