### ISSUE TITLE
Cyclic dependencies

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#33]
It would look better to get rid of this dependency :)

```
  … => (load "proof-tree.el") => (macroexpand-all …) => (macroexpand (eval-when …)) => (load "proof-shell.el") => (load "proof-tree.el")
```

Connects with #32

**Comment by Matafou** [comment]
These warning are there since proof-tree was developped. They are harmless AFAIU, but indeed we should try to fix them.

**Comment by hendriktews** [comment]
Could somebody tell me what the warning is and how to reproduce it?

proof-tree requiring proof-shell seems natural to me, the other way around does not seem so natural, but is necessary because of the calls in proof-shell to the proof-tree functions.

**Comment by cpitclaudel** [comment]
Running make should be enough to reproduce the warning :)
