### ISSUE TITLE
Byte compilation fails on Mac OSX

### ISSUE THREAD

**Issue by knepley** [ProofGeneral/PG#348]
Using the master branch

  master:~/MacSoftware/ProofGeneral$ git describe
  v4.4-148-g315b704

I run

  make clean; make EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs

and fail

  /Applications/Emacs.app/Contents/MacOS/Emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (expand-file-name (symbol-name d))) (quote (acl2 ccc coq easycrypt hol-light hol98 isar lego pghaskell pgocaml pgshell phox twelf generic lib))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile coq/coq-system.el

In toplevel form:
coq-system.el:309:1:Warning: !! The file uses old-style backquotes !!
This functionality has been obsolete for more than 10 years already
and will be removed soon.  See (elisp)Backquote in the manual.

In coq-option-of-load-path-entry:
coq-system.el:309:55:Warning: `(or (and (pred stringp) dir) (\` (ocamlimport
    (\, dir))))' is a malformed function
coq-system.el:309:55:Error: Wrong number of arguments: #[(structure) "\30!A\207" [structure backquote-process] 2 1719914], 2
make[1]: *** [coq/coq-system.elc] Error 1
make: *** [compile] Error 2

**Comment by Matafou** [comment]
@cpitclaudel I am not competent enough for this. I can't reproduce the bug.
It seems to be linked to the pcase patterns. Can you have a look please?

**Comment by cpitclaudel** [comment]
The problem seems to be that pcase isn't loaded — this is surprising, because pcase is supposed to be autoloaded... @knepley, can you tell us which version of Emacs you're using?

**Comment by cpitclaudel** [comment]
(FWIW, I can't reproduce either, neither in 24.3 nor on master)

**Comment by knepley** [comment]
I am using Mac Emacs Version 23.2 (9.0).

**Comment by cpitclaudel** [comment]
OK, this makes sense. That version is 8 years old, and we don't support it.  Can you try with a more recent Emacs?

**Comment by erikmd** [comment]
Hi @knepley, indeed as shown by [this file](https://github.com/ProofGeneral/PG/blob/master/.travis.yml), ProofGeneral is only tested by Travis CI for Emacs >= 24.3; older versions are not supported.

I'm not a macOS user but I guess you could try installing a recent Emacs using [Brew](https://brew.sh/) for example (or another package manager...)

Hoping this helps.

**Comment by knepley** [comment]
Okay, I finally got around to trying a newer Emacs. Everything works fine. Thanks!
