### ISSUE TITLE
Cannot open load file: No such file or directory, cl-extra on Emacs 26

### ISSUE THREAD

**Issue by mituharu** [ProofGeneral/PG#355]
Steps to Reproduce:
1. Invoke Emacs 26.1 Release Candidate 1.
2. C-x C-f .../SomeCoqFile.v RET.
3. C-c C-n

Expected Result:
The first command is processed.

Actual Result:
proof-activate-scripting: Cannot open load file: No such file or directory, cl-extra

This is because the function `coq-include-options` uses the name `load-path` as its first argument, and the global value of the variable is hidden (because of dynamic binding) when trying to autoload `cl-every` in `coq-load-path-safep`.

The following functions also use the name `load-path`.  Probably this name should be avoided for arguments.
- coq-coqdep-prog-args
- coq-coqc-prog-args
- coq-coqtop-prog-args

**Comment by Hexadecimaaal** [comment]
Temp solution: choose "Start Coq" from menu manually.

**Comment by corwin-of-amber** [comment]
@Hexadecimaaal nope, still the same error.

**Comment by Matafou** [comment]
Please try on last master branch and reopn if this still bugs.
Thanks for reporting.

**Comment by cpitclaudel** [comment]
Thanks @Matafou. Do we know why this popped up in Emacs 26?

**Comment by Matafou** [comment]
I don't know, maybe because cl-every was not an autoload before this version of emacs?

**Comment by gasche** [comment]
I hit this issue today (I'm using a distro-packaged version of proof-general that may be out of date). In case anyone with the same issue looks here in the future, the work-around I used is to execute `(load-library "cl-extra")` before processing the Coq script, which can be done simply by writing

```
(* (load-library "cl-extra") *)
```

anywhere in the `.v` file, placing the cursor on the closing parenthesis `extra")`, and running `eval-last-sexp` on it (shortcut `C-x C-e` on my config).

**Comment by moyodiallo** [comment]
> (load-library "cl-extra")

Works for me thanks

**Comment by monnier** [comment]
>> (load-library "cl-extra")
> Works for me thanks

Please don't:
- `load-library` is a command, i.e. it's meant for `M-x`.  In Elisp code
  you're better off using just `load`, or better yet `require` if you
  just want to make sure that it's been loaded rather than to force
  (re)loading it right now.
- `cl-extra` is an internal detail of the CL/cl-lib libraries so you
  should load either `cl` or `cl-lib` instead.

IOW, please use

    (require 'cl-lib)

instead.
