### ISSUE TITLE
Dedicated Gitter channel for PG?

### ISSUE THREAD

**Issue by anton-trunov** [ProofGeneral/PG#363]
Hi folks, do you think it would make sense to create a such a channel? E.g. I'd like to contribute to PG but I'm an Elisp newbie and would appreciate some guidance.

**Comment by cpitclaudel** [comment]
That sounds nice, but I can't commit to maintaining a presence on gitter :/

**Comment by Matafou** [comment]
Good idea. I don’t think the traffic would be very high.

**Comment by erikmd** [comment]
Actually we had created a private Slack for PG (but did not used it that much), and I have the impression that Slack's interface has more features than Gitter... so another possibility could just be to make that Slack group public for the use case @anton-trunov is mentioning?
@cpitclaudel @Matafou what do you think?

**Comment by Matafou** [comment]
Indeed, we could have a special thread in slack for people willing to contribute.
It needs a registration from one of the admin though. So it is less open that a gitter.

And we should use slack more...

**Comment by anton-trunov** [comment]
I'm fine with using slack. So, if you folks could add me to slack to have some more silly questions from me, it would be great :)

**Comment by Matafou** [comment]
@anton-trunov please give your usual slack login.

**Comment by anton-trunov** [comment]
@Matafou `anton-trunov`

**Comment by Matafou** [comment]
@erikmd can you add Anton to the group please? I can't.
Then I will create the new thread.

**Comment by erikmd** [comment]
@Matafou

> It needs a registration from one of the admin though. So it is less open that a gitter.

Yes but this can be customised as well AFAIK.

> @erikmd can you add Anton to the group please? I can't.

Sure! I'm doing this ASAP (I'm currently away from my PC keyboard :)

(Actually I believe I'm the only admin of the Slack PG group currently but of course I'll be able to add Clément and you as well, so the admins of the Slack will match the owners of the GitHub org)

See you, Erik

**Comment by Matafou** [comment]
To my knowledge in the free version of slack there is no public or shared thread.

Yes please make us admi too. So that we can help you manage that.
Thanks!

**Comment by erikmd** [comment]
Hi, sorry for the delay :)

@Matafou and @cpitclaudel you're now admins of https://proofgeneral.slack.com/ as well.

I was not able to invite @anton-trunov because what is actually needed is the e-mail address.

> To my knowledge in the free version of slack there is no public or shared thread.

I think so. Or more exactly, the channels are public by default to the members of the Slack group (it is possible to create private channels as well in the free version, I've just checked this) and one can only become a member of the Slack group by accepting an invitation (but it is possible to create an invitation link in the free version, so that interested people can just subscribe to the group by themselves).

**Comment by erikmd** [comment]
@anton-trunov I've just create one such link:
https://join.slack.com/t/proofgeneral/shared_invite/enQtMzc4MzM0NzczMDU5LTVhZDkwNjRhOTUyMmM4ZDc4NTk2YmFmYjUyYTYzYTJiMDdmYzczOWJmMGVlMGQ5MjFiOGFmY2JkYWQ2NGRiZjM
Can you please test it?
If it works, we'll be able to mention this in the doc, e.g. in the website https://proofgeneral.github.io/

**Comment by erikmd** [comment]
@Matafou feel free to create an additional channel for discussing on (elisp) internals of PG.
For example it could be named `emacs`, `emacs-lisp`, `elisp`, `contributing`, `contribute`, `contribs` ?
Kind regards, Erik

**Comment by anton-trunov** [comment]
@erikmd It works! Thanks a lot!
