### ISSUE TITLE
error in process filter: Wrong number of arguments: #[(string &optional separators omit-nulls) 

### ISSUE THREAD

**Issue by hfehrmann** [ProofGeneral/PG#368]
This is the emac error that occurs in the middle of a proof in Coq for the current commit in master. Version of emac: 24.3.1
Coq: 8.7.2

Here is the error in *Messages*
```
error in process filter: Wrong number of arguments: #[(string &optional separators omit-nulls) "		Æ?
ÇÈ
É
6
ÇU6
GW6
T7
#`
GW`ÆQ
ÇWZ
ÇOBÇm
GWu
ÈOB-" [separators omit-nulls split-string-default-separators list notfirst start t 0 nil string-match rexp keep-nulls string] 5 1648341], 4
```

**Comment by Matafou** [comment]
Hi
Thanks for reporting. 
Is it possible to have the file on which this happens please?

**Comment by hfehrmann** [comment]
This code produce the error for every auto tactic execution (intros also generates the error)
```
Theorem test: forall n, n >= 0.
Proof. induction n. auto. auto. Qed.
```
I noticed also that the proof context is not refreshing when the error occurs. The async branch does not have this problem.

**Comment by Matafou** [comment]
I can't reproduce, what version of emacs do you have?

**Comment by Matafou** [comment]
ho sorry the emacs version is in you initial message.

**Comment by Matafou** [comment]
Can you test this please? I removed the use of the 4th arg of this function.

**Comment by Matafou** [comment]
By the way @erikmd @cpitclaudel can you remind me what versions of emacs we support please?

**Comment by hfehrmann** [comment]
Now does not compile
```
****************************************************************
 Byte compiling... 
****************************************************************
make elc
make[1]: Entering directory `/home/hans/.emacs.d/lisp/PG'
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (expand-file-name (symbol-name d))) (quote (acl2 ccc coq easycrypt hol-light hol98 isar lego pghaskell pgocaml pgshell phox twelf generic lib))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile acl2/acl2.el
Wrote /home/hans/.emacs.d/lisp/PG/acl2/acl2.elc
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (expand-file-name (symbol-name d))) (quote (acl2 ccc coq easycrypt hol-light hol98 isar lego pghaskell pgocaml pgshell phox twelf generic lib))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile ccc/ccc.el
Wrote /home/hans/.emacs.d/lisp/PG/ccc/ccc.elc
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (expand-file-name (symbol-name d))) (quote (acl2 ccc coq easycrypt hol-light hol98 isar lego pghaskell pgocaml pgshell phox twelf generic lib))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile coq/coq-abbrev.el

In toplevel form:
coq/coq-abbrev.el:23:1:Error: Cannot open load file: subr-x
make[1]: *** [coq/coq-abbrev.elc] Error 1
make[1]: Leaving directory `/home/hans/.emacs.d/lisp/PG'
make: *** [compile] Error 2

```

**Comment by Matafou** [comment]
ops some part of my experiments was remaining in the file. Should be ok now.

**Comment by hfehrmann** [comment]
Good! Now the error does not exists!

**Comment by Matafou** [comment]
cool. Thx again for reporting.

**Comment by erikmd** [comment]
> By the way @erikmd @cpitclaudel can you remind me what versions of emacs we support please?

According to the [.travis.yml file](https://github.com/ProofGeneral/PG/blob/master/.travis.yml), the supported versions of GNU Emacs are 24.3, 24.4, 24.5, 25.1, 25.2, 25.3

But I just noticed that in the [front page of the doc](https://proofgeneral.github.io/doc/userman/) and in the MELPA-related [proof-general-pkg.el file](https://github.com/ProofGeneral/PG/blob/master/proof-general-pkg.el), the minimal version of GNU Emacs that is mentioned is 24.4…

It happens that emacs 24.3 is the standard [version of emacs packaged in Ubuntu 14.04 LTS](https://packages.ubuntu.com/trusty/emacs24), which is still [supported until April 2019](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions), so I guess it would make sense to update the front page of the doc and the `proof-general-pkg.el` file to officially support emacs downto version 24.3, in line with what is tested by Travis CI ? @Matafou @cpitclaudel do you agree?

**Comment by Matafou** [comment]
Agreed.
