### ISSUE TITLE
Proof general fails to start coqtop because of unkown flag -emacs-U

### ISSUE THREAD

**Issue by fferreira** [ProofGeneral/PG#373]
Proof General fails to start coqtop with the following message:

Don't know what to do with -emacs-U
See -help for the list of supported options

Running:
GNU Emacs 24.5.1
PG:  Version 4.4.1~pre (installed from git, I have the current head of master)
Coq: The Coq Proof Assistant, version 8.8.0 (June 2018)
OS: Ubuntu 16.04.4 LTS

I found and old bug report (http://proofgeneral.inf.ed.ac.uk/trac/ticket/233) with a similar problem. But I don't have makefiles in my directory and it still fails

**Comment by cpitclaudel** [comment]
I suspect you're not actually running the latest proof-general.  Can you open a .v file and run `M-x find-function RET coq-goals-mode` and see which file that opens?  You might have a stale copy of PG somewhere.

**Comment by fferreira** [comment]
Yes, you are absolutely right. I removed that version and now it works.
Thank you very much!

**Comment by wonhyukchoi** [comment]
I'm getting this output:
```
(define-derived-mode coq-goals-mode proof-goals-mode
  "Coq Goals" nil
  (coq-goals-mode-config))
```
Where do I go from here?

**Comment by cpitclaudel** [comment]
> My files compile fine if I just run coqc, but I can't seem to run them on proof general.

Can you give more details?

> Using coqc version 8.4.6 on Spacemacs on emacs 26

That version of Coq is 5 or 6 years old btw

**Comment by wonhyukchoi** [comment]
Actually, I'm not sure why I commented on this version; I will open up a different issue
