### ISSUE TITLE
Feature request: coq-insert-hypothesis and coq-insert-name

### ISSUE THREAD

**Issue by siddharthist** [ProofGeneral/PG#376]
Most of the `coq-insert-*` commands are for inserting keywords/syntax, this is a different sort of functionality.

I think it'd be useful to be able to insert the names of the current hypotheses using something like fuzzy search in `helm`. Consider the following scenario:
```
  myLongHypothesisName : X -> Y
  ============================
  Y
```
I can use `coq-insert-tactic` to insert `apply`, but in order to get `myLongHypothesisName` typed quickly, I have to type a prefix of it and wait for `company` to kick in. Instead, I'd like to call `coq-insert-hypothesis` to fuzzily search in `helm`.

The second, less straightforward suggestion is the ability to insert *any* name currently in scope. This would be useful for, say, `unfold`ing in the following goal:
```
  x : X
  ============================
  myLongPredicateName x
```

**Comment by cpitclaudel** [comment]
> but in order to get myLongHypothesisName typed quickly, I have to type a prefix of it and wait for company to kick in.

You could also reduce company-idle-delay to get company to kick in faster, or define a key binding for `company-manual-begin`; would either of these work?

> The second, less straightforward suggestion is the ability to insert any name currently in scope. 

Do you use company-coq? It does that, mostly.

**Comment by siddharthist** [comment]
@cpitclaudel Fair points, my main hurdle is that to take advantage of `company-coq` I am always typing prefixes of things, whereas I'd like to use fuzzy search (as I can with the `coq-insert-*` functions).

**Comment by siddharthist** [comment]
I made an attempt to roll my own version, but it isn't working:
```elisp
  (defun siddharthist/company-coq-helm-symbols ()
    (interactive)
    (require 'company-coq)
    (require 'helm)
    (message "(company-coq-init-symbols) = (%s)" (company-coq-init-symbols))
    (when (company-coq-init-symbols t)
      (helm :sources 'company-coq-dynamic-symbols
                :buffer "*helm blah*")))
```
It seems that `(company-coq-init-symbols)` is always `nil`. Is there a way to call this function from outside of `company-coq` proper and have it work? Is it clear what I'm trying to do?

**Comment by cpitclaudel** [comment]
>  Is there a way to call this function from outside of company-coq proper and have it work? Is it clear what I'm trying to do?

Yup, it looks fine, in fact.
What does `(company-coq-feature-active-p 'dynamic-symbols-backend)` return?
(You shouldn't need to refresh the list every time, by the way; using `company-coq-dynamic-symbols` directly or just calling `…-init-symbols` without the `t` argument should be enough)

**Comment by siddharthist** [comment]
@cpitclaudel When in an actively-processing Coq buffer, that returns `nil` as well.

I don't see [any reason in particular](https://github.com/syl20bnr/spacemacs/blob/9af8e1564d5bb80c01a2f4a8de68247ef621f155/layers/%2Blang/coq/packages.el#L23) for that to be disabled, is it enabled by default? `company-coq` works just fine completing typed text, where could it be getting completions from if not the `dynamic-symbols-backend`?

I appreciate your pointers :smile:

**Comment by siddharthist** [comment]
Oh, it seems like I need to be "living on the edge". From `company-coq-available-features`:
```
 (dynamic-symbols-backend . "Completion of global definitions [experiental, slow].\nAutocompletes theorem names by querying the prover.\nUse `company-coq-live-on-the-edge' to enable this feature.")
```
@cpitclaudel Is there a better, faster, less experimental list from which I could draw identifiers into `helm`? Again, it seems that `company-coq` has some list which is working fine for normal completion, what might that be?

**Comment by cpitclaudel** [comment]
Ah, I see :)

> less experimental

Well, it was experimental back in the days of Coq 8.4 and 8.5 :)
Here's the list of all completion backends used by company-coq:

```
(defcustom company-coq-sorted-backends 
                            '(company-coq-reserved-keywords-backend
                              company-coq-block-end-backend
                              company-coq-user-snippets-backend
                              company-coq-modules-backend
                              company-coq-context-backend
                              company-coq-refman-ltac-abbrevs-backend
                              company-coq-refman-tactic-abbrevs-backend
                              company-coq-refman-vernac-abbrevs-backend
                              company-coq-refman-scope-abbrevs-backend
                              company-coq-pg-backend
                              company-coq-local-definitions-backend
                              company-coq-search-results-backend
                              company-coq-dynamic-tactics-backend
                              company-coq-dynamic-symbols-backend)
  "All completion backends, ordered by display priority.
Do not remove entries from this list (but feel free to reorder
them).  To disable backends, customize `company-coq-disabled-features'."
  :group 'company-coq
  :type '(repeat function))
```

I think you probably want local definitions and hypotheses, so `(company-coq-collect-local-definitions)` and `company-coq--hyp-names`.

**Comment by siddharthist** [comment]
I've figured out how to do this, I'll submit some PRs to `company-coq` with related functionality this weekend :)
