### ISSUE TITLE
A problem with autoloads

### ISSUE THREAD

**Issue by mrkkrp** [ProofGeneral/PG#386]
Thanks for adding PG to MELPA! I tried to install it yesterday but it looks like there is a problem with autoloads.

A bit of background: I use a bit of custom Emacs lisp that installs missing packages on startup thus taking care of my setup e.g. on new machines. I also have CI and a script that tests startup:

https://travis-ci.org/mrkkrp/dot-emacs/jobs/423066997#L3053

This is what happens when it tries to install PG. This code seems to be executed:

https://github.com/ProofGeneral/PG/blob/master/generic/proof-autoloads.el#L17

For some reason `(error "Already loaded")` fires and stops the party.

The code (the check in particular) seems non-standard (from the packages I inspected only PG does this), autoloads are usually auto-generated I think (not sure).

Anyway, can we somehow prevent this? All other packages work fine.

**Comment by cpitclaudel** [comment]
Can you see what happens if you remove the code that triggers the error ? That bit was added way back, possibly at a time when reloading autoloads wasn't safe.

**Comment by cpitclaudel** [comment]
Thanks for the report, btw

**Comment by cpitclaudel** [comment]
Also, it would help to understand why that file is loaded twice - even if it should work, it's not the best for performance

**Comment by mrkkrp** [comment]
> Can you see what happens if you remove the code that triggers the error ?

I'm not sure how to check this. You see, if I just do `package-install` it works is both cases. So I need to edit PG and then adjust loading code so it installs it from a local copy and I don't know how to do that. `package-install-file` doesn't work for some reason.

Is there anything that prevents us from dropping that check and seeing if that fixes the issue?

**Comment by cpitclaudel** [comment]
Oh, I see, ok. I think dropping the check, yes, but I'd really like to understand why the double-loading happens.

The reason I worry is that the original PG didn't like being loaded twice, and despite my efforts I'm not 100% sure it's safe now.

I need to study the backtrace from your build log. Can you show the snippet that installs missing packages ?

**Comment by cpitclaudel** [comment]
OK, I think I understand a bit better: package.el reloads any file that was already loaded to ensure that compiling in a dirty session doesn't break macros. (Thanks for the trace; it was very useful)

I've dropped the check.  I don't see why it's useful, and the original commit doesn't help:

```diff
commit 2c6dded0f96ebcb1a9807af29d2a469cbc54f116
Author: David Aspinall <da@inf.ed.ac.uk>
Date:   Tue May 9 10:11:22 2000 +0000

    New files

diff --git a/generic/proof-autoloads.el b/generic/proof-autoloads.el
--- /dev/null
+++ b/generic/proof-autoloads.el
@@ -0,0 +1,2 @@
+;;; DO NOT MODIFY THIS FILE
+(if (featurep 'proof-autoloads) (error "Already loaded"))
```
