### ISSUE TITLE
Proof General interprets warnings as errors

### ISSUE THREAD

**Issue by Mjiig** [ProofGeneral/PG#394]
The following warning appears to be interpreted as an error 

```
Toplevel input, characters 0-50:
> Require Export UniMath.Foundations.NaturalNumbers.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<warning>
Warning: Notation _ ≠ _ was already
used in scope nat_scope.
[notation-overridden,parsing]
</warning>
```

as "Toplevel input," is red highlighted and the fraction of the proof accepted does not advance. This seems to be caused by [this](https://github.com/ProofGeneral/PG/blob/master/coq/coq-syntax.el#L1218) regex?

**Comment by Matafou** [comment]
this sounds like an ssreflect bug to me. But I will have a look. Thanks for reporting.

**Comment by Matafou** [comment]
Ho sorry. Does it use another ml plugin?

**Comment by Mjiig** [comment]
Hmm, uninstalling the apt version of proof general appears to have fixed the issue. Sorry to waste your time.
