### ISSUE TITLE
Color “lavender” is not defined in emacs-nox

### ISSUE THREAD

**Issue by Mbodin** [ProofGeneral/PG#395]
In `coq/coq.el`, there is this definition:
``` lisp
(defun coq-highlight-hyp-aux (h)                                                                                                                                          
  "Auxiliary function, use `coq-highlight-hyp' for sticky highlighting.                                                                                                   
Unless you want the highlighting to disappear after the goals                                                                                                             
buffer is updated."                                                                                                                                                       
  (let ((hyp-overlay (coq-find-hyp-overlay h)))                                                                                                                           
    (when hyp-overlay                                                                                                                                                     
      (overlay-put hyp-overlay 'face '(:background "lavender")))))
```
The issue is that I am using emacs-nox and that the color “lavender” is not defined in it. Instead, emacs then choses the color white as a replacement… making all highlighted hypotheses appear white on white, making them disappearing in practice. This is not optimal.

A quick fix is to replace “lavender” by “magenta”, which is defined. A better fix would be to make this face customisable. I have no idea how difficult this would be.

**Comment by Matafou** [comment]
Thanks for reporting. It should not be difficult to have both a correct color in box mode and a customizable color.

**Comment by cpitclaudel** [comment]
Also, we should change the color to respect `frame-background-mode`; his is how it looks in my Emacs after pulling the latest PG:

![screenshot](https://user-images.githubusercontent.com/8181630/47966533-85e94500-e021-11e8-9247-c2af04b8e9da.png)

**Comment by cpitclaudel** [comment]
And we should probably have a setting to turn the whole thing off, too, since it conflicts with some company-coq bits

**Comment by Matafou** [comment]
Yes sorry I don’t use much company coq so yes we need to deal with bad interaction or overlaps. Maybe these features are overlapping with company coq and I should remove them?
P

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cpitclaudel** [comment]
> Maybe these features are overlapping with company coq and I should remove them?

No no, it's a great feature! I'll make the required fixes on my side, no worries. It's just that in general it's good to have a way to turn off UI additions, I think.

**Comment by co-dan** [comment]
I have to confirm that those highlighted hypothesis also look unreadable on my screen.
I would appreciate if there would be a setting to turn this feature off.
I have "discovered" this feature when my emacs has highlighted a hypothesis without any intervention from me.

**Comment by Matafou** [comment]
Done. It is transient by default, and the default background color is "gray".

**Comment by co-dan** [comment]
@Matafou thank you!
