### ISSUE TITLE
Please improve integration with `use-package`

### ISSUE THREAD

**Issue by ejgallego** [ProofGeneral/PG#398]
When loading proof general using [use-package](https://github.com/jwiegley/use-package) the extra `:no-require t`  has to be passed to the init function:

```elisp
(use-package proof-general
  :no-require t
  :ensure t)
```

otherwise, `use-package` will error: https://github.com/jwiegley/use-package#prevent-a-package-from-loading-at-compile-time

Please either fix or document this requirement for Proof General

**Comment by erikmd** [comment]
Hi @ejgallego, thanks for your report!

We're aware PG's MELPA package still has a few glitches w.r.t. `use-package` support, but we weren't able to polish this yet by lack of time.

BTW I've recently experimented a fully `use-package`-bootstrapped `.emacs` config with PG and `company-coq` in https://github.com/erikmd/coq-init.el (*in French*) which solves the issue you raise by doing a slightly different workaround, using `:defer t` − so I guess your workaround is better than mine.

Anyway this `use-package` config should be simplified after fixing that issue, then we could officially document that PG is `use-package`-compliant in the `README.md` and on https://proofgeneral.github.io/ … I can look at this soon (hopefully next week)

**Comment by ejgallego** [comment]
Thanks @erikmd ! I am not sure which one is the right workaround; I guess you experts will have to tell :)

**Comment by erikmd** [comment]
Indeed that's better; I've updated the repo of my `use-package` config example.
