### ISSUE TITLE
Mode line disappears

### ISSUE THREAD

**Issue by Chobbes** [ProofGeneral/PG#401]
Let's say I have a file, even just with this:

```
Definition blah {A : Type} (a : A) : list A :=
  cons a nil.
```

Then I hit `C-c C-n` and then `M->` to go to the beginning of the file, and then hit `<C-return>`, then the modeline on the response buffer disappears.

I've also seen the modeline for tho goals buffer randomly disappear as well, and it's pretty weird and jarring when this happens, especially if you resize these buffers with a mouse, or get confused without the mode line separating them.

Executing this is the buffer fixes the problem:

```
(kill-local-variable 'mode-line-format)
```

I think it might have something to do with: https://github.com/ProofGeneral/PG/blob/733cd24a7368ee186884da488da0f59bbedb627e/generic/proof-utils.el#L283

**Comment by cpitclaudel** [comment]
Thanks for opening this issue. I think that code should just go. I don't think hiding the modeline is particularly useful.

**Comment by Chobbes** [comment]
I kind of agree. I'm not really sure why it would ever hide the modeline. I was honestly a little surprised that you *could* hide the modeline :).

**Comment by Matafou** [comment]
This is an old and debatable feature of pg. To save place on small screens I guess. Not fond of it too.

**Comment by Chobbes** [comment]
@Matafou ah okay. I mean, it could always be a toggle, but I think people with small screens (myself included) might want something a bit more predictable, like just deleting the modeline ourselves?

**Comment by Matafou** [comment]
It was more predictable before: there was no modeline at all for the goals and response buffers. At some point it went unpredictable, I don't know why. I think we can remove it.

**Comment by Chobbes** [comment]
Should be fixed now. https://github.com/ProofGeneral/PG/pull/402
