### ISSUE TITLE
Use -topfile

### ISSUE THREAD

**Issue by SkySkimmer** [ProofGeneral/PG#407]
Coq 8.10 will have an option -topfile to set -top correctly according to the filename and -R/-Q settings (see coq/coq#8991). 
When running a coq which supports this option on a file visiting buffer PG should pass -topfile, unless -top or -topfile are already in coq-prog-args.

**Comment by Matafou** [comment]
Hi thanks!
Does the - have the same syntax as _CoqProject? Does it serve the same purpose? I must admit the thread you cite is a bit obscure to me.

**Comment by SkySkimmer** [comment]
I don't understand what you mean by "the -".

**Comment by Matafou** [comment]
The option -topfile takes a filename as argent I suppose. In what format is supposed to be this file?

**Comment by Matafou** [comment]
“As argument” sorry I type on my phone.

**Comment by Matafou** [comment]
Sorry I don't understand. It must point to what kind of file? the toplevel executable? Directory of the "Top" module? What does buffer-file-name has to be with it?

**Comment by SkySkimmer** [comment]
Suppose you have files `_CoqProject`
~~~
-R theories Bla
theories/foo.v
~~~
and `theories/foo.v`
~~~coq
Definition hello := Prop.
Check Bla.foo.hello.
~~~
This will compile, but if you run it in PG it will fail. That's because PG runs `coqtop -emacs -R /absolute/path/to/theories Bla` with no information regarding which file it's about, so Coq uses the default name `Top` and hello's full name is `Top.hello`.

Currently the user can workaround that by setting `coq-prog-args` to `-top Bla.foo` locally to the file, but 
- then they also have to copy the stuff from _coqproject to the local variable as otherwise they get overriden
- they have to do that for every file which is a pain

If by default PG passes `-topfile /path/to/theories/foo.v` Coq will run with the same name as when compiling, and everything will be nice.

**Comment by Matafou** [comment]
I see now. But would it be simpler to always launch coqtop with -topfile

**Comment by Matafou** [comment]
Ho nice I understand now. Thanks!

**Comment by SkySkimmer** [comment]
Why close?

**Comment by Matafou** [comment]
misclick sorry.

**Comment by Matafou** [comment]
This should work now.

**Comment by SkySkimmer** [comment]
It doesn't work when using a custom coq path (ie `proof-prog-name-ask t` then input a path to some coq).
Maybe coq-autodetect-version should use `proof-prog-name` instead of `coq-prog-name`.

**Comment by SkySkimmer** [comment]
Also it may be better to test for the capability by grepping for -topfile in the output of coq -h. For instance there's a PR waiting to add -topfile to 8.9 (https://github.com/coq/coq/pull/9111)

**Comment by Matafou** [comment]
> It doesn't work when using a custom coq path (ie `proof-prog-name-ask t` then input a path to some coq).
> Maybe coq-autodetect-version should use `proof-prog-name` instead of `coq-prog-name`.

Indeed the whole coq detection machinery is broken. It is done too early, in coq-mode-hook,  instead of coq-shell-mode.

**Comment by Matafou** [comment]
This should make things better. Please tell me if not.

I am not completely happy with the code as explained in the commit.

**Comment by SkySkimmer** [comment]
Looks like it works, although for some reason coq is invoked with doubled -topfile: `ps aux | grep coq` => `/home/gaetan/dev/coq/coq/bin/coqtop -topfile /tmp/foo.v -emacs -topfile /tmp/foo.v`

**Comment by Matafou** [comment]
Coming back on this.
Does someone have a opinion on the current way we detect coq version? I think it is fundamentally broken for at least two reason:
1) coq-prog-name may change during the life of the coq buffer (for instance if with prof-prog-name-ask is t the prog name is asked each time we start the coq process. So detecting coq version when opening 
 the file (hack-local-variable in coq-mode-hook) is incorrect.
2) coq-prog-name is not synchronized with proof-prog-name except at the moment of coq-mode-config.

I have started fixing 1) by adding a hook just before the prover process is called, but it leads to several questions: how to not overwrite user forced options (local variables)? I suggests that user options are also interpreted at the last moment before calling the process.

**Comment by JasonGross** [comment]
Note the current tip of PG is broken on versions of Coq master between 8.9.0 and coq/coq#8991; either 8.10+alpha should *not* get `-topfile`, or else (probably better) PG should do genuine feature detection and look at the output of `-help`.
