### ISSUE TITLE
"error in process filter: Symbol’s function definition is void: caddr"

### ISSUE THREAD

**Issue by Lysxia** [ProofGeneral/PG#409]
GNU Emacs 25.3.1
PG master

Processing this single line:

```
Lemma f (P : Prop) : P.
```

generates the following errors in the `*Messages*` buffer, and then hangs unresponsively for a second before accepting the line:

```
apply: Symbol’s function definition is void: open-after-coq-command
error in process filter: proof-shell-filter-wrapper: Symbol’s function definition is void: caddr
error in process filter: Symbol’s function definition is void: caddr
```

This happens even after minimizing my `.emacs` to only mention PG:

```
(load-file "pathto/PG/generic/proof-site.el")
```

**Comment by cpitclaudel** [comment]
I think this is likely an oversight from a recent patch by @monnier.  The code should use cl-caddr instead of caddr. I just pushed a tentative fix.

**Comment by cpitclaudel** [comment]
Thanks! Pushed another commit. Let's see how good my regexp-fu is.

**Comment by Lysxia** [comment]
That's fixed! Thanks Clément!

**Comment by cpitclaudel** [comment]
Neat, thanks for testing so quickly.
