### ISSUE TITLE
query-replace inside the processed region selects the first match, rather than the next one

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#41]
If I use `query-replace`, and press `RET` to replace a match inside the processed region, the processed region (correctly) reverts, but then the next match selected is the first match of the document, rather than the subsequent match in the sequence.

**Comment by hendriktews** [comment]
This sounds like retraction is moving point around. We should
eventually fix this.

H.

**Comment by Matafou** [comment]
Strange bug. Retraction seems correctly protected against that. Strangely
enough it does not seem to got exactly to the top of the buffer (misses
first lines).

Looks like a specific bad interaction with query-replace.

P.


2016-01-25 11:59 GMT+01:00 hendriktews <notifications@github.com>:

**Comment by erikmd** [comment]
Hello,
I've just looked at this issue, and found that enclosing the end of function `proof-retract-before-change` in a `(save-match-data &rest BODY)` successfully protects retraction with respect to `query-replace` and `replace-string`. So I'm going to push my patch and close the issue.
Best regards, EMD
