### ISSUE TITLE
Section indentation broken

### ISSUE THREAD

**Issue by vzaliva** [ProofGeneral/PG#411]
During one of last of updates of PG via MELPA section indetation become broken. Here is what I got (complete example):

```
Section Foo.
  
  End Foo.
```

I would expect:

```
Section Foo.
  
End Foo.
```

Version: Version 4.5-git (installed via MELPA)

**Comment by HuStmpHrrr** [comment]
same problem here. latest melpa install as of Jan 22nd 2019.

**Comment by HuStmpHrrr** [comment]
I believe there are more indentations broken. For example, if we type `Proof` in the next time of a lemma with existential conclusion, then the indentation is also broken.

**Comment by Matafou** [comment]
Sorry for being not so reactive. I will try to have a look. I don’t think this part of the code has been touched recently so this is a bit strange.

**Comment by vzaliva** [comment]
I just noticed that the same problem exists with `Module` definitions. `End` part is not properly aligned.

**Comment by Matafou** [comment]
This should be fixed in current master. Thanks for reporting.

**Comment by vzaliva** [comment]
I just tested (from MELPA) and it seems to be fixed for both `Module` and `Section` indentation. Thank you!
