### ISSUE TITLE
Failed on-the-fly compilation dedicates goals window to compilation error message, confusing PG

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#42]
Originally reported by @vzaliva on https://github.com/cpitclaudel/company-coq/issues/66:

```
When one of the modules which is I am importing contains syntax error, after error 
message "Recompling binary failed with X status" company-coq (or proof general)
ends up in inconsistent state.
Attempting to step through any proofs leads to error message:

    "Window is dedicated to coq-compile response"

Even though I am focused in right buffer. The only solution is to restart Emacs.

Environment: 
  * Aquamacs 3.2
  * PG 4.3pre150313 (latest from git)
  *  Company-coq latest from MELPA
```

Does that ring a bell for anyone?

**Comment by Matafou** [comment]
It does ring a bell but I thought this was fixed.

**Comment by hendriktews** [comment]
@cpitclaudel @vzaliva Works for me without problems. I can either step through the errors with C-x ` or clicking on the error. Do you still see the problem?

**Comment by vzaliva** [comment]
I just checked with my current version of PG and company-coq and it is not happening again.
I must note that I am no longer using Aquamacs. Perhaps it was specific to it.

**Comment by hendriktews** [comment]
Then I am going to close the issue if nobody objects.

**Comment by hendriktews** [comment]
Nobody objected - please reopen if the issue appears again.
