### ISSUE TITLE
Do not use -topfile when it is not supported

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#422]
Note the current tip of PG is broken on versions of Coq master between 8.9.0 and coq/coq#8991; either 8.10+alpha should *not* get `-topfile`, or else (probably better) PG should do genuine feature detection and look at the output of `-help`.

_Originally posted by @JasonGross in https://github.com/ProofGeneral/PG/issues/407#issuecomment-494567244_

**Comment by Matafou** [comment]
Done the 2nd option. Thanks!
