### ISSUE TITLE
Backtrack -> BackTo

### ISSUE THREAD

**Issue by gares** [ProofGeneral/PG#433]
Since Coq 8.5 `Backtrack` has been deprecated in favour of `BackTo`.
The latter takes only one argument corresponding to the first one of `Backtrack`.
Even if `Backtrack` still works, the other arguments are ignored, so the transition is trivial and could also lead to some simplification on your side.

Concerned line:  https://github.com/ProofGeneral/PG/blob/6361916d4d80828fd0bcc92c575c59e831b3fa8f/coq/coq.el#L707

CC @maximedenes

**Comment by hendriktews** [comment]
@Matafou @cpitclaudel : Is there a policy for PG, how many old Coq versions it should support? Or do we only support the current Coq release?

**Comment by maximedenes** [comment]
> Is there a policy for PG, how many old Coq versions it should support? Or do we only support the current Coq release?

@hendriktews how does this question relate to this issue?

**Comment by gares** [comment]
> @hendriktews how does this question relate to this issue?

If you use `BackTo` you are compatible with old and new versions of Coq (since 8.4 actually, I was wrong in my previous message). So the change is *very* backward compatible.

**Comment by erikmd** [comment]
@hendriktews
> Is there a policy for PG, how many old Coq versions it should support? Or do we only support the 
current Coq release?

good question, I'd say the implicit assumption is that ProofGeneral is cross-compatible with several versions of Coq from at least 8.4 (cf. e.g. the [doc of coq-load-path](https://proofgeneral.github.io/doc/master/userman/Coq-Proof-General/#index-coq_002dload_002dpath)) but the exact range of officially supported versions of Coq is not mentioned in the doc AFAICT.

So I believe we could make it explicit in the doc that PG (currently) supports `coq >= 8.4`, which:
* is compatible with the `BackTo` command at stake
* is the same Coq version range as that of the [docker-coq images](https://hub.docker.com/r/coqorg/coq/tags) (which had been set like this especially because it wasn't possible to compile Coq 8.3 with the same OCaml version as for Coq 8.4…)

**Comment by hendriktews** [comment]
Maxime Dénès <notifications@github.com> writes:

> @hendriktews how does this question relate to this issue?

If the compatibility range is very big, Proof General needs to
use a conditional or maybe postpone the change, as long as
Backtrack is supported. If the compatibility range is small, we
can delete the old Backtrack code.

Personally, I would suggest, Proof General should only support
the current major version of Coq and the Coq github master
branch. At most the previous major release.

**Comment by cpitclaudel** [comment]
> Personally, I would suggest, Proof General should only support
the current major version of Coq and the Coq github master
branch. At most the previous major release.

I'd rather not :/

**Comment by erikmd** [comment]
@hendriktews 
> If the compatibility range is very big, Proof General needs to use a conditional or maybe postpone the change, as long as Backtrack is supported.

As mentioned in my [comment](https://github.com/ProofGeneral/PG/issues/433#issuecomment-515443528), no need for addition conditional, given that the `BackTo` command is supported by `coq >= 8.4`, which can de-facto be the minimal required version of Coq for PG.

> If the compatibility range is small, we can delete the old Backtrack code.

The old Backtrack code can precisely be removed/replaced, see #434.

> Personally, I would suggest, Proof General should only support the current major version of Coq and the Coq github master branch. At most the previous major release.

Like Clément I disagree with your suggestion, given that PG has always be compatible with a large range of Coq versions, thanks to appropriate conditionals, and I don't see the point to change this now.

@cpitclaudel, are you OK with #434 as well? ideally we could merge it today…

**Comment by cpitclaudel** [comment]
Yup, #434 looks good

**Comment by erikmd** [comment]
Hi Clement,
OK :+1: feel free to merge it if you want (I'll be away from my computer  for several hours :)

**Comment by cpitclaudel** [comment]
^^
