### ISSUE TITLE
Proof-general not found on melpa

### ISSUE THREAD

**Issue by QinxiangCao** [ProofGeneral/PG#440]
After M-x package-install RET proof-general RET, I was told [no-match].

**Comment by erikmd** [comment]
Hi @QinxiangCao, several questions:
1. Can you give more details about your config (OS and Emacs version)?
2. Did you closely follow the install instructions in [https://proofgeneral.github.io/](https://proofgeneral.github.io/#quick-installation-instructions) to setup MELPA? (or did you use `use-package`?)

Anyway, given the error message you get, I see two possible causes:
(i) Either the MELPA index has not been fetched (to fix this you need to do <kbd>M-x package-refresh-contents RET</kbd> before running <kbd>M-x package-install RET proof-general RET</kbd>)
(ii) Or a recent version of the proof-general might already be installed (in which case it would explain why `package.el` refuses to install it again :)

3. In any case, can you have a look at the *package.el index* itself?  
namely after doing <kbd>M-x package-list-packages RET</kbd>, do you see occurrences of "proof-general" in this buffer? (<kbd>C-s proof-general</kbd>)

**Comment by QinxiangCao** [comment]
Thank you very much for your reply. It actually happened when my student tries to install PG on a new MacBook Air. He has latest MacOS. He first installed emacs from home brew and successfully installed PG. But by doing that, he only got command line emacs and ugly PG.

I suggested him to use emacs with a better interface. Then he installed Emacs 26.3 from this webpage:
    https://emacsformacosx.com/
But this time, when he tried "M-x package-refresh-contents RET" + "M-x package-install RET proof-general RET", he got [no match]. The line in the bottom of emacs windows says:
    Install package: proof-general [no match]
Then I tried it on my MacBook (I have been using Coq, emacs, PG for years), I also got
    Install package: proof-general [no match]
That's why I reported this problem. After that, my student directly "git clone" this repository and manually "make" and gets PG installed.

From your explanation, the problem seems to be "a recent version of the proof-general might already be installed". However, if I "M-x package-list-packages RET" (at least on my own laptop), I cannot find proof-general.

**Comment by cpitclaudel** [comment]
Do you have MELPA set up on your (and your student's) laptop?
That is, do you have this in your .emacs?

```
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (add-to-list 'package-archives
               (cons "melpa" (concat proto "://melpa.org/packages/")) t))
(package-initialize)
```

If not, please add it, then restart Emacs and run M-x package-refresh.

**Comment by QinxiangCao** [comment]
I need to ask my student tomorrow. For me, I think I did follow that instruction when I installed PG. I am not 100% sure since it is at least one year ago. Now, I have the following lines in my .emacs.d/init.el:

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)
;; Open .v files with Proof General's Coq mode
(load "~/.emacs.d/lisp/PG/generic/proof-site")
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(coq-prog-name "/usr/local/bin/coqtop")
 '(proof-three-window-enable t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

**Comment by cpitclaudel** [comment]
One year ago PG wasn't on MELPA, so your .emacs is loading PG from a local clone.  Please remove the `(load …)` line and follow the instructions on the PG setup page.

**Comment by erikmd** [comment]
Indeed, Clément's advice is the way to go. Just to confirm the URL of the instructions at stake:
https://proofgeneral.github.io/#quick-installation-instructions
Cc @QinxiangCao

**Comment by cpitclaudel** [comment]
Closing this, since I think we identified the problem. Feel free to reopen this if the problem persists.

**Comment by QinxiangCao** [comment]
Yes. The problem is solved. Thank you very much for help.
