### ISSUE TITLE
Timeout Defined is misclassified resulting in strange parsing errors after backtracking into the middle of a proof 

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#446]
```
$ cat foo.v
(* -*- coq-prog-args: ("-q") -*- *)
Goal True = True.
  idtac.
  Timeout 1 reflexivity.
  Timeout 1 Defined.
BackTo 3.
Timeout 1 reflexivity.
(*
Error:
Syntax error: [located_vernac] expected after [prim:natural] (in [vernac:Vernac.vernac_control]).
*)
$ coqtop -q -emacs < foo.v
Welcome to Coq 8.10.0 (October 2019)
Skipping rcfile loading.

<prompt>Coq < 1 || 0 < </prompt>1 subgoal (ID 3)

  ============================
  True = True

<prompt>Unnamed_thm < 2 |branch| 0 < </prompt>
<prompt>Unnamed_thm < 3 |branch| 0 < </prompt>No more subgoals.

<prompt>Unnamed_thm < 4 |branch| 0 < </prompt><infomsg>Unnamed_thm is defined</infomsg>

<prompt>Coq < 5 || 0 < </prompt>1 subgoal (ID 3)

  ============================
  True = True

<prompt>Unnamed_thm < 6 || 0 < </prompt>Toplevel input, characters 10-21:
> Timeout 1 reflexivity.
>           ^^^^^^^^^^^
Error:
Syntax error: [located_vernac] expected after [prim:natural] (in [vernac:Vernac.vernac_control]).

<prompt>Unnamed_thm < 6 || 0 < </prompt>
```

Note that this situation can occur in interactive use when I end a proof with `Timeout Defined`.  By contrast, if I end a proof with `Time Defined` or `Defined`, then trying to retract the buffer automatically jumps to before the beginning of the proof.  I'm assuming this is a PG bug because the error from coqtop occurs whenever I use `BackTo` to go to the middle of the proof, and it seems that PG just issues different commands depending on how I end the proof.

**Comment by erikmd** [comment]
Hi @JasonGross, thanks for the report and the minimal working example!
I can reproduce it with both interactive mode (PG master) and `coqtop -emacs` (as in your example).
But doesn't this precisely mean that this is a coq(top) issue, not a PG one?

**Comment by JasonGross** [comment]
The error message is, in some sense, a coqtop issue, and occurs whenever I go `BackTo` the middle of a proof.  However, when using backtracking interactively, I can only get PG to emit a `BackTo` that refers the the middle of a proof if I end the proof with `Timeout <n> Defined`.  If I end it with `Defined` or `Time Defined`, then interactive backtracking emits a `BackTo` which refers to before the beginning of the proof.

**Comment by erikmd** [comment]
Indeed, you're right! the error is from PG side, given that the computed argument of `BackTo` is incorrect (the backtracking should undo the whole proof)
