### ISSUE TITLE
Broken indentation for `do` tactical

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#462]
The following snippet indents incorrectly (there should be no indentation under `do`)

```coq
Proof.
  do 2 split.
     - idtac.
     - idtac.
```

@Matafou is this related to monadic notations?

**Comment by Matafou** [comment]
I am afraid so. Will have look next week.
P

**Comment by Matafou** [comment]
This should be ok now. Detecting "do followed by an integer" as another token than "do", which is by default taken as a monadic term-level operator.
Please reopen if you find a problem.
