### ISSUE TITLE
Disable unicode tokens mode by default

### ISSUE THREAD

**Issue by hexchain** [ProofGeneral/PG#463]
Is there a way to disable unicode tokens mode by default, preferably by inserting some commands in `init.el`? I am using doom-emacs and the menu options are not helpful.

**Comment by hexchain** [comment]
Sorry for my mistake. It was `company-coq` that caused this problem, not PG. Disabled that package and the issue was gone.

**Comment by cpitclaudel** [comment]
Did you check M-x customize-group company-coq?  There's a setting called company-coq-features.

**Comment by hexchain** [comment]
That feature seems to be enabled by default. Disabling it makes the fancy symbols gone.

Thanks!
