### ISSUE TITLE
lazymatch with bullets confuses C-M-f

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#47]
Hey @Matafou,

This is in the indentation code, so I have no clue how to fix it :/

C-M-f on this bullet goes to `end` as expected:

    - match goal with
      | [ H: forall x, ?f x -> _, H': ?f ?x |- _ ] => learn (H x)
      end.

But it goes after `goal` on this one:

    - lazymatch goal with
      | [ H: forall x, ?f x -> _, H': ?f ?x |- _ ] => learn (H x)
      end.

**Comment by Matafou** [comment]
This was a bug in coq-smie-forward-token.

This function (contrary to its backward version) is actually not used by indentation code but only by navigation, and probably highly incomplete because highly untested. I fixed this issue but we will need more fixes.

Re-open when you find other bugs.

**Comment by cpitclaudel** [comment]
Thanks Pierre :)
I'm stretting it in Company-Coq. because I use it to find blocks to fold when collapsing bullets.

**Comment by Matafou** [comment]
expect other bugs...
