### ISSUE TITLE
Add support for Ltac2

### ISSUE THREAD

**Issue by tchajed** [ProofGeneral/PG#473]
There's a whole host of Ltac2 commands to add to Proof General, especially `Ltac2 foo := ...` and `Ltac2 Type bar := `. See https://coq.github.io/doc/master/refman/proof-engine/ltac2.html# for more.

I'd be happy to start adding these if somebody can point me towards what to change.

**Comment by erikmd** [comment]
Hi @tchajed, thanks for opening this; PRs that add syntax highlighting for missing commands are very welcome!

As `Ltac2` is a definition command, you'll just need to add some line(s) in `coq-syntax.el` after this one:

https://github.com/ProofGeneral/PG/blob/9196749d55413224355409d55003f7f8c8ba0f79/coq/coq-syntax.el#L492

(BTW @ProofGeneral/core do you know why [some entries](https://github.com/ProofGeneral/PG/blob/9196749d55413224355409d55003f7f8c8ba0f79/coq/coq-syntax.el#L493) are marked with a `careful` comment?)

Tej, for the syntax of these entries, see this docstring:
https://github.com/ProofGeneral/PG/blob/9196749d55413224355409d55003f7f8c8ba0f79/coq/coq-db.el#L31-L75
