### ISSUE TITLE
Documentation mistaken about Coq electric terminator

### ISSUE THREAD

**Issue by dunnl** [ProofGeneral/PG#475]
This is minor, but the [documentation](https://github.com/ProofGeneral/PG/blob/71748af5bc0f813d4c6a42f303d2c2cec85b3c9a/doc/ProofGeneral.texi#L926) indicates that Coq has a default keybinding for toggling electric terminator mode. This hasn't been true since #160. Not sure what the updated wording should say or I'd offer a PR.

**Comment by cpitclaudel** [comment]
Thanks. Let's fix the documentation by removing the mention of the keybinding (while keeping the documentation for the menu entry)

**Comment by cpitclaudel** [comment]
Do you want to make a PR?

**Comment by erikmd** [comment]
Fixed by #476
