### ISSUE TITLE
Feature: Improve `C-c C-a TAB` to conditionally insert `move=>` or `intros`

### ISSUE THREAD

**Issue by erikmd** [ProofGeneral/PG#479]
Currently, if we type <kbd>C-c C-a TAB</kbd> in a Coq buffer, it automatically inserts `intros …`:

```coq
Lemma test :
  forall A B C : Prop, (A -> B -> C) -> (A -> B) -> A -> C.
(* "C-c C-a TAB" ↓ *)
intros A B C H H0 H1.
```

It would be great if it could insert `move=> A B C H H0 H1` instead,
if the current file contains `Require…ssreflect` on the same line

**Comment by erikmd** [comment]
This will indeed be a nice first issue for @CyrilAnac that starts its internship on PG this week :+1:

(FYI next we'll also work together on improving the async support for Coq (while keeping compatibility with EasyCrypt and PhoX))

**Comment by anton-trunov** [comment]
Wow! This is huge, folks. Thanks for sharing it here. Feel free to ping me if you need testers :)

**Comment by erikmd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue feature `C-c C-a TAB`](https://trello.com/c/CNn1uXha/24-issue-feature-c-c-c-a-tab)
