### ISSUE TITLE
(proof-process-buffer) fails on file when there are no `Proof.` command

### ISSUE THREAD

**Issue by erikmd** [ProofGeneral/PG#485]
with @CyrilAnac we're working on adding integration tests to master (in branch [coq-tests-for-master](https://github.com/ProofGeneral/PG/commits/coq-tests-for-master)) and Cyril noticed there is an issue in the following corner case:

when opening [file "test_wholefile.v"](https://github.com/ProofGeneral/PG/blob/866a9da96a53c387050e7d8f7df9a0a3e35b435f/ci/test_wholefile.v) (which contains no `Proof.` command) and doing `C-c C-b`, we get the following warnings in **\*response\***:

```
Warning: Adding and removing hints in the core database implicitly is
deprecated. Please specify a hint database. [implicit-core-hint-db,deprecated]
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
Warning: Adding and removing hints in the core database implicitly is
deprecated. Please specify a hint database. [implicit-core-hint-db,deprecated]
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
Proof General: script management confused, couldn't find goal span for save.
```

then if we modify, say, the first line of the file, retract is broken…

(FYI the batch flavor of this test (running `./ci/test.sh`) leads to [this GitHub action log](https://github.com/ProofGeneral/PG/runs/642313094?check_suite_focus=true#step:5:1277))

But adding one `Proof.` command in *the last* proof make the two bugs vanish.

As `Proof.` is an optional command, this is a priori a non-minor bug…

@Matafou @cpitclaudel do you think this can easily be solved?

**Comment by Matafou** [comment]
oops this must come from my recent hacking ob "proof using" auto filling.
I will check this now.

**Comment by erikmd** [comment]
Hi @Matafou, thanks for looking into!

FYI I have tested just now the commit before, namely, 8273e22e6da7b20e51fa330116bee20964d5dab8, and I believe the bug was reproducible, so maybe it is not due to your latest hack 8273e22e6da7b20e51fa330116bee20964d5dab8 and the bug was already there for a long time?

**Comment by Matafou** [comment]
Yes, I think it is one of the several commits I made on this. Actually I had to fix it several times so there were a few previous commits.
I really need to stop committing things to fast.
I will push a fix in a few seconds, please test.

**Comment by erikmd** [comment]
Thanks a lot @Matafou, I confirm that your patch 23db83dc4141d89530f6381ba49f56399682d4e0 definitely fixes the issue :+1:

Maybe @CyrilAnac could add a small regression test in the test-suite?

anyway we'll be able to merge these integration tests in `master` soon.

**Comment by Matafou** [comment]
Please add as much regression tests as possible!
