### ISSUE TITLE
Improve PG support of Show Proof Diffs

### ISSUE THREAD

**Issue by erikmd** [ProofGeneral/PG#487]
Currently, PG supports `Show Proof Diffs.` regarding Diffs' syntax highlighting, but the command itself has to be triggered manually.

ToDo:

* Create a new branch `coq-show-proof` from `master`
* Add a `defcustom coq-show-proof` option
* After each proof step (do nothing if outside of a proof):
    * If `coq-show-proof` is non-nil:
        * If `coq-diffs = nil`:
            * Send `Show Proof.` to the prover using `proof-shell-invisible-command`
        * If `coq-diffs = 'on`:
            * Send `Show Proof Diffs.` to the prover
        * If `coq-diffs = 'removed`:
            * Send `Show Proof Diffs removed.` to the prover
    * Then (normally, no code to write) the **\*response\*** buffer should be automatically selected.

* Add a menu checkbox for `coq-show-proof` − see e.g. #421:
    https://github.com/ProofGeneral/PG/blob/7501326a228a5d0af1ad1d5bef4e8640cbd1e43f/coq/coq-abbrev.el#L223

* When that menu checkbox is checked, if `coq-diffs = nil`, display a message in the minibuffer suggesting to enable `Coq > Diffs` as well.

* Bonus(**optional**): add a small test regarding the **\*response\*** text with `coq-show-proof = t` and `coq-diffs = nil`, on a proof such as `Goal True -> True. intros H.`

**Comment by erikmd** [comment]
@jfehrle when #487 will be implemented in master and regarding the porting to the XML protocol, I've seen `Show Proof.` command is already supported, but will something be required on the Coq side to have `Set Diffs "on".` and `Show Proof Diffs` supported in the emacs←→coqidetop interaction?
(I don't know well how the `Show Proof Diffs` feature is implemented in Coq, but IINM the Goal Diffs are already available in CoqIDE, so maybe the overall architecture would already be compatible?)

**Comment by jfehrle** [comment]
Goal diffs are already supported in CoqIDE; that was done before I added them to PG.
The "Highlighting text" section in https://github.com/coq/coq/blob/master/dev/doc/xml-protocol.md describes how diff highlights are encoded.  Note that the tags are embedded in _string values_ in the XML; while they look like XML tags, they are handled differently.  The encoding is the same in XML and coqtop output.

`Show Proof Diffs` is not supported in CoqIDE at this time because the command is not accessible from CoqIDE--contrary to my wishes.  Perhaps now is a good time to revisit that on the Coq side so that PG could access that command, too.  I'd expect the other Coq developers would be more open to this change if it's part of an effort to complete and release a version of PG that uses the XML protocol rather than `coqtop`.

Perhaps you or Cyril could announce your intentions to coqdev?  I could then follow up with a separate discussion of `Show Proof Diffs` support.

**Comment by erikmd** [comment]
Hi @jfehrle, thanks for your feedback! yes I believe we could send an e-mail on this to coqdev, after our next meeting with Cyril (monday 11 may)

**Comment by CyrilAnac** [comment]
Hi, i'm facing an issue there. The purpose is to display the **goal** and the **response** in the same time, but I feel like only one buffer can show what we want. I tried something in the *coq.el* file [here](https://github.com/ProofGeneral/PG/commit/457a2714bc5137b4fd1a00f09db479b327da5271#diff-d8746cb18cdbee554220197c6627a519R1226), it doesn't work but the XML response seems OK. 
Maybe @Matafou, can you help me out by taking a look ? Thanks.

**Comment by Matafou** [comment]
I may be wrong but it seems you don't add the code at the right place here.
This function is currently one big (cond ...) so only one of the conditions will be triggered. So your ((or...)) may be preempted by a previous one.
Either you dispatch your code in each cases or you make your addition as an append to what the current (cond *..) already builds.

**Comment by erikmd** [comment]
Hi @Matafou, thanks for your comment; yes @CyrilAnac was aware that there are potentially three cases in the `coq-empty-action-list-command` function to update, but he had only updated one case (the case of a "regular" proof step, without considering backtracking etc.)

After debugging step-by-step, we notice that the `extra-item` variable at this line:

https://github.com/ProofGeneral/PG/blob/7389d43893569ff0e1eff892254901876fc8225e/generic/proof-shell.el#L1144

indeed gets the following value:

```
((nil
  ("Show Proof.")
  proof-done-invisible
  (invisible empty-action-list))
 (nil
  ("Show.")
  proof-done-invisible
  (invisible empty-action-list)))
```

so these two Coq commands are tagged in the same way with `'(invisible empty-action-list)`, but there are handled differently (the last command is taken into account in the goals/response buffer, but not the last-but-one command)… @Matafou would you have a suggestion regarding the change to perform so that both commands are taken into account w.r.t. goals/response?

BTW is it easy to summarize `'empty-action-list`'s semantics? as it's not documented here:)
https://github.com/ProofGeneral/PG/blob/7389d43893569ff0e1eff892254901876fc8225e/generic/proof-shell.el#L83-L87

**Comment by erikmd** [comment]
We made some progress after diving into `proof-shell.el`'s code, to sum up:

* the role of `'empty-action-list` appears to be a flag to ensure termination, according to this test:
https://github.com/ProofGeneral/PG/blob/7389d43893569ff0e1eff892254901876fc8225e/generic/proof-shell.el#L1138-L1140
* it seems the missing part in Cyril's first attempt is that some code detecting the `Show Proof…` command (maybe with a `'empty-action-list`, to differentiate w.r.t. a manual `Show Proof…`) should be added to the `proof-shell-filter-manage-output` (and/or `proof-shell-handle-delayed-output`) function.

**Comment by Matafou** [comment]
ASFAIU this is the flag of things that PG adds to the queue each time the queue becomes empty: they should not re-trigger themselves.

**Comment by Matafou** [comment]
I don't see why only one action is performed. Is it not rather that the first is done and hidden by the second action?
Anyway it seems we should combine things into only one action, which is rather unpleasant.

**Comment by erikmd** [comment]
Hi @Matafou, thanks for your comments.

> Anyway it seems we should combine things into only one action, which is rather unpleasant.

I'd prefer not to, given that (even if this is orthogonal to the question at stake), in some case we have to append `Show Proof.` **but not `Show.`**, notably as `Show.` does not support the "Proof Diffs" currently (there is an open issue for that in the coq tracker)

> I don't see why only one action is performed. Is it not rather that the first is done and hidden by the second action?

After further debugging I confirm that both actions are performed ("in the same (silent) way"), `proof-shell-last-goals-output` and `proof-shell-last-output` are updated as expected, but the machinery that runs in the end, relying on `proof-shell-last-output-kind`, seems to be just incomplete w.r.t. what we want to do.

**Comment by erikmd** [comment]
Anyway, I'm more optimistic regarding the feasibility of that feature without changing the codebase much, and hopefully @CyrilAnac could put all these things together by the end of the week… stay tuned!
