### ISSUE TITLE
Automatic compliation of dependencies does not work with Coq 8.5's "From ... Require Import..."

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#49]
When a file starts, for example, with
```
From program_logic Require Import ownership.
```
ProofGeneral fails to notice that it has to re-compile the file, and then immediately fails because of inconsistent assumptions about other modules.

**Comment by RalfJung** [comment]
This happens both with sequential and parallel background compilation.

**Comment by Matafou** [comment]
Should be fixed now. Please test. Thanks!

**Comment by cpitclaudel** [comment]
:+1: :)

**Comment by RalfJung** [comment]
Yes, seems like it's working. Thanks :)
