### ISSUE TITLE
PG Coq mode suggests "Proof using" for me even outside of sections

### ISSUE THREAD

**Issue by xuanruiqi** [ProofGeneral/PG#492]
As stated in the question, if I set "Proof using" mode to "highlight", then it suggests "Proof using" mode to me, even outside of sections. However, since I have no sectional variables, no section variables are suggested for me, so all I get is an annoying highlight that I can't remove.

**Comment by Matafou** [comment]
Hi, thanks for reporting. This feature is still experimental I guess.
I tested and indeed coq displays the warning even outside sections.
On one hand this is a coq warning so if you put to "highlight" it is quite justified to highlight imho.
On the other hand I don't understand why Coq does this. I thought `Proof using` were only for sections. I will ask the question as an answer to your first mail on coq-club.
It would be quite painful to have PG make this highlighting happen only inside sections.

**Comment by Matafou** [comment]
bug subitted to coq: https://github.com/coq/coq/issues/12447.

I will think about a workaround to deal inPG with the bugged versions of coq.

**Comment by gares** [comment]
As I said in the Coq issue I don't have time to track which version exactly lost the "if a section is open" test, I guess you'll have to try. But the many refactorings that probably introduces the bug a quite recent. @xuanruiqi which version of Coq are you using?

**Comment by Matafou** [comment]
V8.10 seems to not have the bug. Did not test v8.11.

**Comment by xuanruiqi** [comment]
> As I said in the Coq issue I don't have time to track which version exactly lost the "if a section is open" test, I guess you'll have to try. But the many refactorings that probably introduces the bug a quite recent. @xuanruiqi which version of Coq are you using?

@gares: I am using 8.11.1.

**Comment by tchajed** [comment]
To summarize in case anyone else runs into this issue: if you can, upgrade to a version of Coq after June 8th, 2020 to get the upstream fix for this issue (or 8.12+beta1 or later if using a release).
