### ISSUE TITLE
ProofGeneral being broken in melpa-stable is confusing

### ISSUE THREAD

**Issue by samontea** [ProofGeneral/PG#509]
This is a little bit of weird feedback. Because melpa stable has version 4.4 of proof general which is very old and is missing tons of features including #385 (which I believe fixed a major bug). I had to [reprioritize](https://github.com/samontea/.emacs/commit/c3cf22c00c12c806fcc35f9d1ba012de6be922ab) my package repositories so that I could get what I find to be a working version of proof general. I just wanted to let you know that I found it confusing that the current version of proof general in melpa's stable repositories is 4 years old, and (in my experience) broken. 

I just wanted to suggest updating or removing this version (4.4) from melpa stable.
Cheers,
Samuel

**Comment by erikmd** [comment]
Hi @samontea, thanks for opening this!

Indeed we didn't commit to supporting MELPA stable up to now (which is the reason why there is only the standard MELPA Markdown badge in the README, not that of MELPA stable), and I believe proof-general is not the only elisp package that follow this "rolling-release only" choice.

Regarding the two choices you suggest:
* on the one hand, I doubt it is feasible to "remove" an old version from MELPA stable (and if it were the case, IMHO it wouldn't be a reasonable choice, in the same way as it would be quite awkward to "remove an old git tag" in a given github repo)
* on the other hand, I don't object to adapting the release workflow and push new tags again (which would then be automatically propagated to MELPA stable), we could discuss this with @ProofGeneral/core in the upcoming weeks indeed? And maybe do a release in October? Before that anyway, I'd like to see a couple of issues/PRs addressed, especially https://github.com/ProofGeneral/PG/pull/506 (which spotted a possible major issue with Coq 8.12, that has been raised in the coq-club mailing list as well… I wasn't able to investigate this issue yet by lack of time, but it's on my todo-list!)

**Comment by samontea** [comment]
Hi @erikmd,

I appreciate that you want to be a primarily rolling release project. 

* I believed one could by setting the version regexp such that it doesn't match any version. E.g. forge tries to do this: https://github.com/melpa/melpa/blob/58c5ca46286712b2aa43e07bb5dcbc8b5eb321e8/recipes/forge#L10. However, it looks like they're unsuccessful. [It looks like this is the result of a bug which was never fixed.](https://github.com/melpa/melpa/commit/58c5ca46286712b2aa43e07bb5dcbc8b5eb321e8#commitcomment-33155358)

  Another alternative could be releasing a version that tells people to switch over to the MELPA unstable version because the MELPA stable builds are not being maintained.

  Obviously, one would have to make a decision about whether one wanted to do such a thing.

* It would be awesome if you could start pushing new tags!

Thanks for maintaining this software by the way I'm a big fan.

**Comment by erikmd** [comment]
Hi @samontea, thanks for your kind message and for opening melpa/melpa#7122 ;
I guess we'll close this issue #509 either when melpa/melpa#7122 is addressed, or when we happen to make a new PG release in the upcoming weeks (whichever comes first :)

**Comment by erikmd** [comment]
FYI @samontea (Cc @ProofGeneral/core): as a follow-up of the very last PG maintainer telco, we tagged proof-general [`v4.5`](https://github.com/ProofGeneral/PG/releases/tag/v4.5), implying [MELPA-Stable's package](https://stable.melpa.org/#/proof-general) is now fully up-to-date.

So I believe we can close this issue now.

− *Related: #637*
