### ISSUE TITLE
In Coq mode, "Proof using" mode corrupts "Proof with tac"

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#518]
In Coq, with Coq->"Proof using" mode -> ask or always set, and the proof is started with "Proof with tac.", PG will corrupt that Proof line by inserting the "using" before the "with" instead of after, and by deleting the "w" from "with".  One gets things like "Proof using ith tac." instead of the proper "Proof with tac using.".  Because PG allows this mode to alter locked regions, the proof is not undone and the corrupted line can go unnoticed until the file is reparsed.

This is using PG 4.5-git in Emacs 26.1 with Coq 8.12.

**Comment by Matafou** [comment]
Hi, indeed this is a bad bug. I will try to fix it.

**Comment by Matafou** [comment]
I think putting the `using before` before is better, think of:
```coq
Proof with auto using X.
```
Since auto accepts the keyword "using" this is ambiguous.

**Comment by Matafou** [comment]
Should be fixed in master. Please reopen if you see something wrong.

**Comment by jonleivent** [comment]
Unfortunately,
```coq
Proof using with tac.
```
is not accepted by Coq in this case where there is no list of section vars following `using`.  But you are correct that placing the using after tactics such as auto would be ambiguous.  So, perhaps this is a problem with both PG and Coq?

**Comment by erikmd** [comment]
@jonleivent Indeed; @Matafou what about this?

```coq
Proof with (tac) using.
```

**Comment by jonleivent** [comment]
That seems to work in the cases that I tried.  I don't think there are any ambiguities there, unless it is possible to have a tactic notation that captures the outer parens somehow.

**Comment by Matafou** [comment]
> Proof using with tac.

I was told that `Proof using Type.` Is equivalent to `Proof using.` so I implemented that in the case of empty list. I guess it is a matter of taste.

> Proof with (tac) using.

Yes this is a workaround but it is a bit more complex than the solution above imho. 

I was also told that the `using` annotation has become a true annotation so one day we may propose `#[using ""] Proof with bla.`.

**Comment by erikmd** [comment]
OK, so that's very OK with PR #519. Thanks @Matafou!
