### ISSUE TITLE
coq version detection breaks in emacs 27

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#525]
Hi,

this morning I got emacs 27 with Debian testing and this apparently breaks the automatic coq version detection in PG. AFAICS, it is the call of `shell-command` inside `coq-callcoq` inside `coq-system.el`. In emacs 26 this seems to return the process exit status. However in emacs 27 it seems to return always 1. Just try
```elisp
(with-temp-buffer
  (let ((ret (shell-command "/usr/bin/true" (current-buffer))))
    (cons ret (buffer-string))))
```
`shell-command` is not documented in the elisp manual and its docstring does not say anything about the return value. Therefore I would say we have been relying on unspecified behavior here.
@cpitclaudel : I believe you added those lines in 2016 - what is your opinion?
Hendrik

**Comment by monnier** [comment]
> (with-temp-buffer
>   (let ((ret (shell-command "/usr/bin/true" (current-buffer))))
>     (cons ret (buffer-string))))

This should use `call-process` since there's no need to spawn a shell
process to then spawn /usr/bin/true.

**Comment by cpitclaudel** [comment]
> This should use `call-process`

Right.  We should also report the bug to Emacs, since the return value of shell-command was consistent with shell-command-on-region.


The whole relevant bit of code is this:

```elisp
(defun coq-callcoq (option &optional expectedretv)
  "Call coqtop with the given OPTION and return the output.
The given option should make coqtop return immediately.
Optionally check the return code and return nil if the check
fails.
This function supports calling coqtop via tramp."
  (let* ((default-directory
           (if (file-accessible-directory-p default-directory)
               default-directory
             "/"))
         (coq-command (shell-quote-argument (or coq-prog-name "coqtop")))) 
    (with-temp-buffer
      ;; Use `shell-command' via `find-file-name-handler' instead of
      ;; `process-line': when the buffer is running TRAMP, PG uses
      ;; `start-file-process', loading the binary from the remote server.
      (let* ((shell-command-str (format "%s %s" coq-command (or option "")))
             (fh (find-file-name-handler default-directory 'shell-command))
             (retv (if fh (funcall fh 'shell-command shell-command-str (current-buffer))
                     (shell-command shell-command-str (current-buffer)))))
        (if (or (not expectedretv) (equal retv expectedretv))
            (buffer-string))))))
```

That's the result of Pierre refactoring the function introduced by this commit:

```
commit ac4f528a7797ffa2fcc0b46014ec15232bd8807e
Author: Clément Pit--Claudel <clement.pitclaudel@live.com>
Date:   Thu May 19 17:56:44 2016 -0400

    Fail silently if Coq's version can't be detected
    
    Rationale: if Coq isn't installed, we will detect it when trying to run
    it, and we don't need to duplicate the error logic.
    
    Additionally, change from using process-lines to using shell-command,
    possibly through file-name-handler. The reason for this change is that
    we want to do the version detection on the remote server if we're
    running in Tramp.

diff --git a/coq/coq-system.el b/coq/coq-system.el
index 2a803f36..8e0f9034 100644
--- a/coq/coq-system.el
+++ b/coq/coq-system.el
@@ -99,9 +99,20 @@ coq-autodetect-version
 Interactively (with INTERACTIVE-P), show that number."
   (interactive '(t))
   (setq coq-autodetected-version nil)
-  (let ((version-string (car (process-lines (or coq-prog-name "coqtop") "-v"))))
-    (when (and version-string (string-match "version \\([^ ]+\\)" version-string))
-      (setq coq-autodetected-version (match-string 1 version-string))))
+  (with-temp-buffer
+    ;; Use `shell-command' via `find-file-name-handler' instead of
+    ;; `process-line': when the buffer is running TRAMP, PG uses
+    ;; `start-file-process', loading the binary from the remote server.
+    (let* ((coq-command (shell-quote-argument (or coq-prog-name "coqtop")))
+           (shell-command-str (format "%s -v" coq-command))
+           (fh (find-file-name-handler default-directory 'shell-command))
+           (retv (if fh (funcall fh 'shell-command shell-command-str (current-buffer))
+                   (shell-command shell-command-str (current-buffer)))))
+      (when (equal 0 retv)
+        ;; Fail silently (in that case we'll just assume Coq 8.5)
+        (goto-char (point-min))
+        (when (re-search-forward "version \\([^ ]+\\)" nil t)
+          (setq coq-autodetected-version (match-string 1))))))
   (when interactive-p
     (coq-show-version))
   coq-autodetected-version)
```

@monnier do you know what the right tramp function to call is?

**Comment by hendriktews** [comment]
> Right. We should also report the bug to Emacs, since the return value of shell-command was consistent with shell-command-on-region.

I am not sure here, because the documentation of `shell-command` and `shell-command-on-region` does not say anything about the return value. But you are right, in emacs 27 `shell-command-on-region` seems to return the exit status.

> @monnier do you know what the right tramp function to call is?

`process-file`?

**Comment by cpitclaudel** [comment]
> I am not sure here, because the documentation of shell-command and shell-command-on-region does not say anything about the return value. But you are right, in emacs 27 shell-command-on-region seems to return the exit status.

It does, I think:
```
(shell-command-on-region START END COMMAND &optional OUTPUT-BUFFER REPLACE
ERROR-BUFFER DISPLAY-ERROR-BUFFER REGION-NONCONTIGUOUS-P)

[…] Return the exit code of COMMAND.
```

**Comment by hendriktews** [comment]
Right, I missed this.
Maybe the change of `shell-command` is unintended then, because there is an execution path where `shell-command` returns with `shell-command-on-region`.

**Comment by cpitclaudel** [comment]
> Maybe the change of `shell-command` is unintended then, because there is an execution path where `shell-command` returns with `shell-command-on-region`.

Almost certainly. Of course, we should still fix our stuff.  I'm a bit oversubscribed at the moment unfortunately.

> process-file?

Are you sure process-file will run remotely? The commit message above discusses changing to shell-command from process-file for tramp, but it could have been wrong.

**Comment by hendriktews** [comment]
Here the tramp manual says (in 6.5 Integration with other Emacs packages): "‘process-file’ and ‘start-file-process’ work on the remote host when the variable ‘default-directory’ is remote".

**Comment by cpitclaudel** [comment]
Then why the _ did I make that change?  Maybe reverting to process-file would fix the issue?

**Comment by monnier** [comment]
> Then why the _ did I make that change?  Maybe reverting to process-file would fix the issue?

The comment refers to `process-line`, and the code before the changes
used` process-lines`, so using `process-file` would not amount to
"reverting".

**Comment by hendriktews** [comment]
Wrt the return value, `shell-command` and `shell-command-on-region` were never really consistent. When you do
```elisp
(with-temp-buffer (shell-command "/usr/bin/true" t))
```
then you see the return value 1 also in emacs 26. Before emacs 27, the logic inside `shell-command` did not recognize `(current-buffer)` as the current buffer and took the code path for adding output to a different buffer. That code path returns the exit status of the process. Maybe in the cause of fixing emacs bug 39067, they also fixed recognizing `(current-buffer)` as current buffer, thus taking now the code path that returns the result of some `goto-char` instead.

**Comment by cpitclaudel** [comment]
> The comment refers to `process-line`, and the code before the changes used` process-lines`, so using `process-file` would not amount to "reverting".

Oh, of course! Thanks for spotting that.
