### ISSUE TITLE
Coqtop: Don't know what to do with -Q 

### ISSUE THREAD

**Issue by wonhyukchoi** [ProofGeneral/PG#528]
Hi, I'm using an old version of coq, `8.4.6`, for legacy reasons:

```
The Coq Proof Assistant, version 8.4pl6 (December 2020)
compiled on Dec 02 2020 23:06:36 with OCaml 4.02.0
```

On this version of `coqc`, the `-Q` flag is unintroduced.
However, when I try running proof-general with it, I get the following message:
```
Coqtop: Don't know what to do with -Q
```
Currently running Emacs 26.3 (on Spacemacs), Ubuntu 18.04.
I've tried rolling back to versions 4.4 and 4.3, but to no avail (same message).

Is this version of coq too old to be supported, or might there be some way to ameliorate this issue?

**Comment by cpitclaudel** [comment]
Are you sure this -Q isn't coming from a _CoqProject file?

**Comment by wonhyukchoi** [comment]
Ay, I couldn't be dumber. I had an old _CoqProject lying around from when I was using coq 8.6.
