### ISSUE TITLE
Compile Before Require not working anymore

### ISSUE THREAD

**Issue by viampietro** [ProofGeneral/PG#534]
Hello everyone,

I'm using emacs 25.2.2 with proof-general 20201219.1543 (installed through melpa). I'm working on a Coq project, with Coq version 8.12.

When I enable the "Compile Before Require" option in the menu bar and I hit "C-c Enter" to get all my required libraries compiled, then proof-general stalls at the first "Require Import" line.

In the Messages buffer, it says:

> Unexpected error during parallel compilation: (wrong-number-of-arguments (1 . 3) 4)
> proof-extend-queue: Wrong number of arguments: (1 . 3), 4

I don't if it comes from my set up (maybe my Emacs version is too old) or from proof-general.

Thanks,

Vincent

**Comment by hendriktews** [comment]
Hi,

thanks for the report. The problem is reproducible, right? Can
you share a set of files that show the problem and instructions
on how to reproduce?

> I don't if it comes from my set up (maybe my Emacs version is
> too old) or from proof-general.

We have emacs 24.3 in continuous integration running, therefore,
I would say, it's not too old.

Hendrik

**Comment by viampietro** [comment]
OK, I'll try to give you the minimal set up to reproduce the bug. As I was saying, I'm using Emacs 25.2.2 with Proof General 20201219.1543 (installed through melpa). I'm working with Coq version 8.12.

I attach my .emacs.d folder and my .emacs file here
[.emacs-setup.zip](https://github.com/ProofGeneral/PG/files/5736426/default.emacs-setup.zip)

Here is the procedure and the minimal amount of code to reproduce the bug. 

- Create a vernacular file, let's say `Lib.v` and put a "Require Import" instruction at the beginning of the file, e.g:

 `Require Import List.`

- Open `Lib.v` with Emacs (don't forget to replace your .emacs and .emacs.d folder with mine in your home directory)
> $ emacs Lib.v

- Select `Coq >> Auto Compilation >> Compile Before Require` in the Emacs menu bar.
- Then, hit `C-c n` to interpret the line `Require Import List.`

In my case, the nothing happens (as if coqtop was stalling on the first line) and the *Messages* buffer displays:

> Unexpected error during parallel compilation: (wrong-number-of-arguments (1 . 3) 4)
> proof-extend-queue: Wrong number of arguments: (1 . 3), 4

Is this enough to reproduce the bug? Which files do you need to try to get closer to my setup?

Thanks,

Vincent

**Comment by hendriktews** [comment]
Hi,

thanks for all the information. Right now I cannot reproduce with
the current Proof General master branch (which is identical to
what is contained in your
.emacs.d/elpa/proof-general-20201219.1543 directory). I have not
yet tried your .emacs.d directory - unfortunately this is more
untrusted code than I can quickly handle.

> * Create a vernacular file, let's say Lib.v and put a "Require
> Import" instruction at the beginning of the file, e.g:

Let me clearify - you create Lib.v in an empty directory with no
reference to any other coq code?

Your setup is quite big, it also contains Company-coq, maybe the
problem is there or in the interaction of different packages.
Have you tried with an elpa installation containing only Proof
General? Or with your current setup, but with deleting all .elc
files? These are just some guesses - I am still puzzled by the
error message that you report: I am not aware of any execution
path from inside the exception handler that prints "Unexpected
error during parallel compilation" to proof-extend-queue.

To obtain some more information: Can you add the line

    (setq coq--debug-auto-compilation t)

to you .emacs, follow your steps to reproduce the problem and
sent the whole content of the *Messages* buffer?

Hendrik

**Comment by viampietro** [comment]
Hi Hendrik,

Thanks for your answer.

Yes, the Lib.v file is in an empty directory without reference to any other Coq files.

I did the following things, before testing if the bug still exists:

- Unselected all my elpa packages at the exception of proof-general in the `package-selected-packages` variable (in my .emacs file).
- Set the `coq--debug-auto-compilation` variable to true in my .emacs file.
- Removed all .elc files from the .emacs.d/elpa/proof-general-20201219.1543 directory

Then, I opened the Lib.v file, selected the `Compile Before Require`, and hit C-c n again. Same error raised.
Here is the content of the *Messages* buffer:

> 
> Loading 00debian-vars...done
> Loading /etc/emacs/site-start.d/50asymptote.el (source)...done
> Loading /etc/emacs/site-start.d/50autoconf.el (source)...done
> Loading /etc/emacs/site-start.d/50cmake-data.el (source)...done
> Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
> Loading debian-ispell...
> Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...done
> Loading debian-ispell...done
> Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...done
> Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
> Loading /etc/emacs/site-start.d/50global.el (source)...done
> Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...
> Loading cjk-enc...done
> Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...done
> Loading /etc/emacs/site-start.d/50latex-cjk-thai.el (source)...done
> Loading /etc/emacs/site-start.d/50texlive-lang-english.el (source)...done
> Loading /home/iampietro/.emacs.d/lisp/config-proof-general.el (source)...done
> For information about GNU Emacs and the GNU system, type C-h C-a.
> Coq project file not detected.
> Quit
> Coq project file not detected. [2 times]
> Starting: coqtop -topfile /home/iampietro/Lib.v -emacs
> M-x proof-prf for goals; M-x proof-display-some-buffers rotates output; M-x proof-layout-windows refreshes [2 times]
> Starting coq process... done.
> 1 items were added to the queue, scan for require
> attach first 0 items directly to queue
> handle require command "Require Import List."
> job-1: create require job for Require Import List.
> job-1: this job is the last compilation job now
> Unexpected error during parallel compilation: (wrong-number-of-arguments (1 . 3) 4)
> emergency cleanup
> kill all jobs and cleanup state
> proof-extend-queue: Wrong number of arguments: (1 . 3), 4

And, voilà,

Thanks,

Vincent

**Comment by viampietro** [comment]
Okay, I managed to make `Compile Before Require` work by uninstalling Emacs (which I got from an obscure PPA repo) and upgrading it to version 27 from a more trusted PPA repo. Then, I recompiled all my elpa packages with Emacs 27 and that did the trick. 

Therefore, either the bug came from corrupted .elc files or from an incompatibility between PG and my former Emacs version (25.2.2).

Anyway, all set now!

Merry christmas,

Vincent

**Comment by hendriktews** [comment]
I can now reproduce with emacs 24.4 and coq 8.4pl4 - I am guessing the coq version is irrelevant.

**Comment by hendriktews** [comment]
The problem is `make-temp-file`, which has no 4th text parameter before emacs 26. The emacs documentation is not helpful here, it only states that the function was introduced in 21.1. Our CI is also not helpful here, because it runs the Coq tests only with emacs 26.1.

**Comment by Matafou** [comment]
Well spotted @hendriktews!

**Comment by viampietro** [comment]
Yes, thanks a lot @hendriktews!
