### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hargoniX** [ProofGeneral/PG#539]
I'm currently trying to set up Proof General on my machine, my (minimalized for debugging) config looks like this:
```
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("org"       . "http://orgmode.org/elpa/")
                         ("melpa"     . "https://melpa.org/packages/")
                         ("elpa"       . "http://elpa.gnu.org/packages/")
                         ))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package) ; unless it is already installed
  (package-refresh-contents) ; updage packages archive
  (package-install 'use-package)) ; and install the most recent version of use-package

(eval-when-compile
  (require 'use-package))

(setq use-package-always-ensure t) ; always download packages

(use-package quelpa)
(use-package quelpa-use-package)

(use-package proof-general
  :quelpa (proof-general :fetcher github :repo "ProofGeneral/PG")
  :mode ("\\.v\\'" . coq-mode))
```

However whenever I open a .v file I get the following error:
```
File mode specification error: (void-variable coq-show-proof-diffs-regexp)
```

After this one shows up the file gets no syntax highlighting and the additional UI widgest Proof General provides I've seen in screenshots don't show up either.

Would someone happen to know what is going on / how I could fix this?

EDIT:

I did check whether this was use-packages fault and installed PG as recommended here https://proofgeneral.github.io/doc/master/userman/Obtaining-and-Installing/#Obtaining-and-Installing but the error stayed the same. When using the `async` branch however it did actually work out without any errors so I'm quite sure this error is not because of use-package or some environmental stuff of mine.

**Comment by Matafou** [comment]
Hi
This sounds like the pg version you are using is not the current melpa one. Are you sure you are not using an old pg installed somewhere in your config path?

**Comment by Matafou** [comment]
@hargoniX do you still have this problem?

**Comment by hargoniX** [comment]
Nope, it did end up working out with the current melpa version, thank you.
