### ISSUE TITLE
PG may eval arbitrary elisp inside comments

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#557]
Just try to process this comment in PG: `(* ELISP: -- (kill-emacs) -- *)` - maybe save your files first!
Is anybody using this feature? Otherwise I suggest to delete this feature. See also `proof-script-evaluate-elisp-comment-regexp`.

**Comment by hendriktews** [comment]
@DavidAspinall Do you remember why you introduced this feature in 2009?

**Comment by cpitclaudel** [comment]
Yes, please remove that.  It doesn't matter why it's there.
Emacs already has a mechanism for this, with proper security. This needs to go, ASAP.

**Comment by DavidAspinall** [comment]
Eek!!  I suspect it was when we were doing experiments with supporting a middleware layer inside Isabelle which sent dynamic highlighting directions and other things to PG.  I agree with Clément!

**Comment by cpitclaudel** [comment]
I took the liberty of pushing the fix straight to master.
