### ISSUE TITLE
Never send two commands at once

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#563]
We should ***never*** send two commands at once to Coq as it is currently done here: https://github.com/ProofGeneral/PG/blob/56ee4ebc97e77da7d61eaa7b00580bf4ef5b87d9/coq/coq.el#L2157
Via `:setting`, `coq-search-blacklist` (search for `defpacustom search-blacklist`) appears in `proof-assistant-settings`, which causes to evaluate `coq-set-search-blacklist` when Coq starts at the end of `proof-shell-config-done`.

Sending two commands at once (of course) causes Coq to return two prompts. In rare cases in automated tests, `proof-shell-exec-loop` just sees the first prompt and sends the next command directly after the first prompt, such that there is one additional prompt pending for quite a while. While debugging a sporadic test error for a new test for #559, I captured the following content from `*coq*`:
```
Welcome to Coq 8.12.0 (November 2020)

<prompt>Coq < 1 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof". 

<prompt>Coq < 2 || 0 < </prompt>Set Suggest Proof Using. 

<prompt>Coq < 3 || 0 < </prompt>Set Diffs "off". 

<prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 . 

<prompt>Coq < 5 || 0 < </prompt>Remove Search Blacklist "Private_" "_subproof".  Add Search Blacklist "Private_" "_subproof". 

<prompt>Coq < 6 || 0 < </prompt>Set Printing Width 9.

<prompt>Coq < 7 || 0 < </prompt>Set Silent. 

<prompt>Coq < 8 || 0 < </prompt>Definition classical_logic : Prop := forall(P : Prop), ~~P -> P.

<prompt>Coq < 9 || 0 < </prompt>Lemma classic_excluded_middle :   (forall(P : Prop), P \/ ~ P) -> classical_logic.

<prompt>Coq < 10 || 0 < </prompt>Proof using.

<prompt>classic_excluded_middle < 11 |classic_excluded_middle| 0 < </prompt>intros H P H0.

<prompt>classic_excluded_middle < 12 |classic_excluded_middle| 0 < </prompt>specialize (H P).

<prompt>classic_excluded_middle < 13 |classic_excluded_middle| 0 < </prompt>destruct H.

<prompt>classic_excluded_middle < 14 |classic_excluded_middle| 0 < </prompt>trivial.

<prompt>classic_excluded_middle < 15 |classic_excluded_middle| 0 < </prompt>contradiction.

<prompt>classic_excluded_middle < 16 |classic_excluded_middle| 0 < </prompt>Unset Silent. 

<prompt>classic_excluded_middle < 17 |classic_excluded_middle| 0 < </prompt>Qed.

<prompt>classic_excluded_middle < 19 |classic_excluded_middle| 0 < </prompt>
```
Here the additional prompt is only processed 12 commands later! For this new test this happens in about 1 of 10 runs. In the other runs the additional prompt is processed directly after the blacklist command.
This effect is a very good candidate for causing #537.

**Comment by Matafou** [comment]
Well spotted!
I can fix that.

**Comment by hendriktews** [comment]
Pierre Courtieu ***@***.***> writes:

> I can fix that.

That would be nice. I thought about returning a list of strings
instead of a string from `coq-set-search-blacklist`, but this
would require changes where `proof-assistant-settings` is
processed.

**Comment by Matafou** [comment]
It is not worth it. There is already a command `coq-search-blacklist-stringset` also callable from menu: Coq/Settings/Search Blacklist, which deals with search blacklist. I will just change this to not use proof-assistant-settings at alls. I will still allow the customization of `coq-search-blacklist-string` via the defcustom but it will be only for the _default_  blacklist at pg start.

**Comment by hendriktews** [comment]
ok, fine with me, I don't even know what that feature is for

**Comment by Matafou** [comment]
Search is for listing currently imported lemmas by queries, by there names, type etc. The Blacklist thing is to systematically exclude things from the queries. I find it quite useful to set it to "Private_" "_subproof" "_ind" "_rec" "_rect", and during development I tend to make it grow while detecting things polluting my queries.
Another feature I would like is to have PG allow to set a similar mechanism for excluding entire modules from the query. Currently you have to put `outside UglyModule` at the end of each query.
