### ISSUE TITLE
Errors encountered when a Compile Before Require fails

### ISSUE THREAD

**Issue by YaZko** [ProofGeneral/PG#57]
Hi all,

I have been encountering a couple of times the following error: "wrong-type-argument overlayp nil"

Here is the context in which one it occurs as far as I can tell:
- In file B, I try to compile file A by processing a Require Import A (using the option Compile Before Require)
- The compilation fails due to an error of mine, I therefore switch to file A
- Trying to process anything in A, I get the error "wrong-type-argument overlayp nil"
- If I try to get back to A, PG seems to try to process the command but it remains red and I get another error : Assertion failed: (eq proof-shell-busy queuemode)

The only solution I found is to restart Emacs.

Encountered on Mac Os X (El Capitan), with Emacs 24.5, PG 4.4pre, Coq 8.4pl6.

Here is an example of the stack trace when occuring:

Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
  span-set-endpoints(nil 1 25)
  proof-extend-queue(25 ((#<overlay from 1 to 25 in logic.v> ("Require Import language.") proof-done-advancing nil)))
  proof-assert-semis(((cmd "Require Import language." 25)) nil)
  proof-assert-until-point()
  proof-assert-next-command-interactive()
  call-interactively(proof-assert-next-command-interactive nil nil)
  command-execute(proof-assert-next-command-interactive)

Does it make sense to anyone?
Thanks,
Best,
Yannick.

**Comment by Matafou** [comment]
Thanks for reporting, I will have a look at it.
P.

**Comment by Matafou** [comment]
It makes sense. Will try to fix this in a few days hopefully.
P.

**Comment by hendriktews** [comment]
Do you still have this issue? When I try with the latest git version, I see

  error in process filter: Cannot resize window #<window 10 on *response*>

but eventually, PG processes the content in file A.

**Comment by hendriktews** [comment]
@YaZko If nobody objects I am going to close this issue.
