### ISSUE TITLE
`field` is not a terminating tactic

### ISSUE THREAD

**Issue by proux01** [ProofGeneral/PG#579]
The field tactic is colored like other tactics such as ring that are terminating whereas it can left remaining subgoals. For instance
```Coq
Require Import Reals.

Open Scope R_scope.

Goal forall a b c : R, c <> 0 -> a / c + b / c = (a + b) / c.
intros a b c cn0.
field.
exact cn0.
Qed.
```

**Comment by Matafou** [comment]
Thanks for reporting! This is fixed.
