### ISSUE TITLE
Syntax highlighting when combining `{` and ssreflect's `tactic:`

### ISSUE THREAD

**Issue by proux01** [ProofGeneral/PG#581]
In the following example
```Coq
Require Import ssreflect.

Goal True /\ True.
split.
{ exact: I. }
exact: I.
Qed.
```
the first `exact:` tactic is strangely colored (the second is fine).

**Comment by cpitclaudel** [comment]
Presumably that's because of the syntax ambiguity with a record definition or instance; I'm not sure there's much we can do.

**Comment by erikmd** [comment]
Thanks @proux01 for opening this.

@cpitclaudel yes I was thinking about you at first sight, but it seems this font-lock was not intended for Records, but for Maximal implicit arguments: see the screenshot below of the following snippet:
```coq
Check forall {T : Type}, Type. (* intended *)

Require Import Floats.

Record cplx := {Re : float; Im : float}. (* partly highlighted! *)

Check {| Re := 0%float ; Im := 0%float |}.
```

![2021-06-03_17-32-18_Screenshot_PG_issue_581](https://user-images.githubusercontent.com/10367254/120671480-b6234980-c491-11eb-8f28-cd121856e5e6.png)

I will open a PR to fix this, so I assign.

**Comment by erikmd** [comment]
Also it appears the new [implicit argument binder `[ _ : _ ]`](https://coq.inria.fr/refman/language/extensions/implicit-arguments.html#implicit-argument-binders) is not recognized yet in PG; so I guess one can address both binders in one go.
