### ISSUE TITLE
How can I disable all decorations of program text forever?

### ISSUE THREAD

**Issue by kindaro** [ProofGeneral/PG#602]
There are some features that make the Coq program text appear what it is really not:

1. Some identifiers turn into symbols. For example, `Prop` turns into `ℙ`.
2. At the end of identifiers, an underscore followed by digits turns into something like a subscript, but ugly. For example, `x_1` turns into something like `x_₁`, except that the digit is still big — it is merely shifted down a little.

There are some drawbacks to this feature.

* [There is no easy way to copy these improved symbols.][1]
* I know how to type all the fancy symbols I need. _(As you can see above.)_
* The fake subscripts legit freak me out.

So, I should like to disable this feature. I figured out that:

1. Running the command `prettify-symbols-mode` solves the problem 1 above.
2. Running the command `company-coq-mode` solves the problem 2 above.

But it is tedious to run these commands in every buffer, every time. How can I disable this feature forever?

I tried to add some hooks, like say this:

    (add-hook 'coq-mode-hook (lambda (  ) (message "coq mode") (company-coq-mode -1) (message "coq mode again")))

However, it does not work — maybe because `coq-mode-hook` runs before the `company-coq-mode` gets switched on. I see the messages before and after, but `company-coq-mode` persists. I tried a bunch of other hooks but nothing does what I want.

I am not an Emacs hacker _(I wield Spacemacs and pray)_ so it is hard for me to solve this problem. Please help me.

[1]: https://www.reddit.com/r/emacs/comments/fn2enn/how_can_i_copy_or_save_a_buffer_with_prettified/

**Comment by erikmd** [comment]
Hi @kindaro, thanks for opening this issue!

Actually the two features you mention are not part of PG, but directly provided by company-coq;

I'm not a Spacemacs user but IINM, adding this line in your emacs should disable the two features at stake:

`(setq company-coq-disabled-features '(prettify-symbols)))`

Otherwise please tell us if this doesn't work for you :)

**Comment by erikmd** [comment]
On second thought, you should rather try:

`(setq company-coq-disabled-features '(prettify-symbols smart-subscripts)))`

**Comment by kindaro** [comment]
Thanks! This works great!

**Comment by cpitclaudel** [comment]
@kindaro I suggest running through the company-coq tutorial; it explains how to customize these features.  There's a message when you start company-coq that explains how to open it.

**Comment by cpitclaudel** [comment]
Oh, wait, if you're on Spacemacs, the devs turned that message off (…).  Use `M-x company-coq-tutorial`
