### ISSUE TITLE
Auto-indenting (hitting tab) does not work

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#613]
When I hit tab to auto-indent the current line, I just get an error in the status line at the bottom: "void-variable x". This worked until before I did `git pull` the last time. It still happens with current master (fd04605af1b07684da522c32d83ac346050926bb).

**Comment by Matafou** [comment]
Hi @RalfJun, can you elaborate please? I do have indentation with current master, a `noninit` emacs and you config.
How do you (try to) trigger indentation?

**Comment by Matafou** [comment]
does it also happen with `M-x indent-region` (after selecting the region you want to indent)?

**Comment by Matafou** [comment]
also: please retry with `emacs -q -no-site-file -l <pathtopg>/generic/proof-site.el`.
