### ISSUE TITLE
Feature request: indentation of Derive … SuchThat

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#618]
Our indentation doesn't support `Derive`, so instead of this:

```
Derive X SuchThat
  P
As U.
Proof.
```

we produce this:

```
  Derive X SuchThat
         P
         As U.
  Proof.
```

Here's another test:

```
  Derive X
  SuchThat P
  As U.
  Proof.
```

which we indent as

```
  Derive X
         SuchThat P
         As U.
  Proof.
```

(we should also add syntax highlighting for Derive)

**Comment by Matafou** [comment]
You can alter the lexer by defining new tokens and associate them to build-in tokens. In this case this works:

(setq coq-smie-user-tokens '(("SuchThat" . ":") ("As" . ":= def")))

although the "As" cannot be at the same level as the command start.

Is this a coq builtin command? In this case we could have it buitin too.

**Comment by cpitclaudel** [comment]
Thanks! Yes, it is built-in: you just need to `Require Import Derive.`
