### ISSUE TITLE
Hypothesis/goal separator not appearing

### ISSUE THREAD

**Issue by siraben** [ProofGeneral/PG#623]
Not sure what's causing the issue, but for me the hypothesis/goal separator is there but colorized to the background color, so it appears invisible. Issue is present on `master` and also on `8f609bd7`.

<img width="270" alt="Screen Shot 2021-11-15 at 12 09 20" src="https://user-images.githubusercontent.com/8219659/141832538-9003ea95-0f27-4d56-963a-6e07efc0825d.png">

**Comment by siraben** [comment]
`C-u C-x =` at the separator gives

```
             position: 33 of 83 (39%), column: 2
            character: = (displayed as =) (codepoint 61, #o75, #x3d)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x3D
               script: latin
               syntax: . 	which means: punctuation
             category: .:Base, a:ASCII, l:Latin, r:Roman
             to input: type "C-x 8 RET 3d" or "C-x 8 RET EQUALS SIGN"
          buffer code: #x3D
            file code: #x3D (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    mac-ct:-*-DejaVu Sans Mono-medium-normal-normal-*-13-*-*-*-m-0-iso10646-1 (#x20)

Character code properties: customize what to show
  name: EQUALS SIGN
  general-category: Sm (Symbol, Math)
  decomposition: (61) ('=')

There are text properties here:
  display              (space :align-to right)
  face                 (company-coq-goal-separator-face)
  fontified            t

[back]	[forward]
```

**Comment by cpitclaudel** [comment]
That's a company-coq issue.  The company-coq-goal-separator-face should have the strike-through property; can you click on it and see whether it does?

**Comment by siraben** [comment]
This is what I see.
<img width="556" alt="Screen Shot 2021-11-15 at 15 16 25" src="https://user-images.githubusercontent.com/8219659/141854959-64dce02c-6bfc-4849-8476-f8fdd016e363.png">

**Comment by cpitclaudel** [comment]
Interesting, and the strikethrough in the first line of that page appears fine.

I won't have time to debug this in the near future (:/), so I'd suggest customizing company-coq-disabled-features to disable the "Discrete improvements to Proof General." one.

If you want to debug it on your own, I'd reproduce the issue from a "clean" emacs config and see what introduces the problem.

**Comment by siraben** [comment]
Ok, disabling the feature fixed it. When I have some more time I can pin down the issue.

**Comment by siraben** [comment]
The issue has been resolved when I tested on https://github.com/cpitclaudel/company-coq/commit/382db93374380e5db56f02934ee32bbe39159019
