### ISSUE TITLE
Port pg-pgip-id timestamp hacking to future Emacs

### ISSUE THREAD

**Issue by eggert** [ProofGeneral/PG#634]
As part of timestamp maintenance I installed the following as [a patch to the Savannah copy of generic/pg-pgip.el](https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?h=elpa/proof-general&id=07755c54ac86df0c9e8bc915dfa12ef72b23e13a); could you please make sure this is propagated upstream? Sorry, I'm new to ELPA hacking and I hope I haven't done things in the wrong order.

```
From 07755c54ac86df0c9e8bc915dfa12ef72b23e13a Mon Sep 17 00:00:00 2001
From: Paul Eggert <eggert@cs.ucla.edu>
Date: Wed, 15 Dec 2021 10:23:19 -0800
Subject: [PATCH] Port pg-pgip-id to future Emacs

* generic/pg-pgip.el (pg-pgip-id): Do not assume a particular form for
Emacs Lisp timestamps, as that is slated to change in a future Emacs
version.  Instead, use time-convert when available (since Emacs 27)
to generate the desired form.
---
 generic/pg-pgip.el | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/generic/pg-pgip.el b/generic/pg-pgip.el
index fbcb444ab7..0954b50491 100644
--- a/generic/pg-pgip.el
+++ b/generic/pg-pgip.el
@@ -281,7 +281,7 @@ Return a symbol representing the PGIP command processed, or nil."
     ;; TODO: display and cache the value in a dedicated buffer
     ;; FIXME: should idvalue have a context?
     (pg-response-message text)))
-    
+
 ;;
 ;; Menu configuration [TODO]
 ;;
@@ -583,7 +583,10 @@ See `pg-pgip-assemble-packet' "
 (defconst pg-pgip-id
   ;; Identifier based on hostname, user, time, and (FIXME: possible?) ppid
   (concat (getenv "HOSTNAME") "/" (getenv "USER") "/"
-	  (let ((tm (current-time))) (format "%d.%d" (car tm) (cadr tm))))
+	  (let ((tm (if (fboundp 'time-convert)
+			(time-convert nil 'list)
+		      (current-time))))
+	    (format "%d.%d" (car tm) (cadr tm))))
   "PGIP Identifier for this Emacs Proof General component.")
 
 (defvar pg-pgip-refseq nil
-- 
2.33.1

```

**Comment by monnier** [comment]
> As part of timestamp maintenance I installed the following as [a patch
>  to the Savannah copy of
>  generic/pg-pgip.el](https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?h=elpa/proof-general&id=07755c54ac86df0c9e8bc915dfa12ef72b23e13a);
>  could you please make sure this is propagated upstream? Sorry, I'm
>  new to ELPA hacking and I hope I haven't done things in the
>  wrong order.

I just merged the change into `master` (the change is hopefully safe and
harmless enough), but please refrain from committing directly to
nongnu.git (or auto-sync'd package on elpa.git, for the same reason).

**Comment by monnier** [comment]
> I just merged the change into `master` (the change is hopefully safe and
> harmless enough), but please refrain from committing directly to
> nongnu.git (or auto-sync'd package on elpa.git, for the same reason).

Looks like the "Thanks" got lost in the subsequent edits, sorry ;-)

**Comment by Matafou** [comment]
don't see any reason to let this open. Thanks again.
