### ISSUE TITLE
Paragraph filling is no longer working

### ISSUE THREAD

**Issue by jwiegley** [ProofGeneral/PG#64]
With emacs-24.5 and proofgeneral-4.3pre, `M-q` does mostly what it does in `text-mode`.

In emacs-25.0.92 and the current proofgeneral, `M-q` does nothing at all, when it appears from the documentation that it should be filling within comments.

Even setting `fill-paragraph-function` to `nil` does not allow it to fill.

However, setting `fill-nobreak-predicate` to `nil` fixes the problem.

**Comment by jwiegley** [comment]
I think what's happening here is that I'm using `whitespace-mode`, so the very comments that I need to fill are those that are marked with a face indicating they are too long; because of this, `coq-mode` then refuses to fill them!  In those cases, `(get-text-property (point) 'face)` evaluates to a list:

``` elisp
(whitespace-line font-lock-comment-face)
```

Thus, I believe the fix is:

``` elisp
  (set (make-local-variable 'fill-nobreak-predicate)
       (lambda ()
         (pcase (get-text-property (point) 'face)
           ('font-lock-comment-face nil)
           ((pred (lambda (x)
                    (and (listp x)
                         (memq 'font-lock-comment-face x)))) nil)
           (_ t))))
```

**Comment by cpitclaudel** [comment]
Thanks for the report, John (and thanks for the analysis!). Is there a reason to look at the face instead of using `syntax-ppss`?

**Comment by jwiegley** [comment]
Probably not.  I don't know about `syntax-ppss` yet!

**Comment by Matafou** [comment]
Thanks for reporting. Let us use syntax-ppss (I didn't know about it when I wrote this code).

**Comment by cpitclaudel** [comment]
I think that commit is wrong :/ Don't you want something more like `(nth 4 (syntax-ppss))`?

**Comment by Matafou** [comment]
oops yes sorry.
