### ISSUE TITLE
Melpa package short description says `PG init file for package.el and ELPA compatibility`

### ISSUE THREAD

**Issue by dominique-unruh** [ProofGeneral/PG#641]
The one-line description of proofgeneral is `PG init file for package.el and ELPA compatibility`, both in the package selection in emacs:
![image](https://user-images.githubusercontent.com/9913676/157261424-f76d3d37-c844-4bee-a410-664c84722a4e.png)
and [here](https://melpa.org/#/proof-general).

I believe it takes this from the first line of `proof-general.el` which is:
```
;;; proof-general.el --- PG init file for package.el and ELPA compatibility -*- lexical-binding: t; -*-
```

I suggest replacing this by `A generic front-end for proof assistants (interactive theorem provers)`, for example, which is the summary from ELPA.

**Comment by erikmd** [comment]
@dominique-unruh good catch; I'll open a PR to fix this then.

**Comment by monnier** [comment]
> The one-line description of proofgeneral is `PG init file for package.el and
> ELPA compatibility`, both in the package selection in emacs:

Indeed, the same applies for NonGNU ELPA, as can be seen at:

    http://elpa.nongnu.org/nongnu-devel/proof-general.html
