### ISSUE TITLE
proof-extend-queue: Wrong type argument: overlayp, nil

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#65]
Reproducing steps:

1. Set `proof-prog-name-ask` to `"non-nil"`
2. Open `foo.v`
3. Type `Goal True.` then `C-c C-RET RET` (in `foo.v`; the second `RET` is to actually start Coq)
4. Type `C-x C-f bar.v RET`
5. Type `Goal True.` then `C-c C-RET yp RET` (that is, yes, retract the buffer, and then give it an invalid binary name) (in `bar.v`)
6. Note that it says `Wrong type argument: number-or-marker-p, nil`
7. Type `C-c C-RET p RET` (give it an invalid binary name a second time)
8. Type `C-c C-RET RET` (a valid binary name, this time)
9. Note that it gives you `*goals*` and `*response*` but says `Wrong type argument: overlayp, nil`.  Every subsequent `C-c C-RET` will give you `Wrong type argument: overlayp, nil`

**Comment by Matafou** [comment]
Hi, thanks for reporting (and the nice reproducing steps),

I can reproduce this, except that at step 6 I don't see the warning. But I do see the bug at the end.

Will have a look at it.

P.

**Comment by cpitclaudel** [comment]
Should be fixed :) Let me know if problems remain.

**Comment by JasonGross** [comment]
Thanks!
