### ISSUE TITLE
Interference with org-mode leads to buffer-save prompt of ephemeral buffers

### ISSUE THREAD

**Issue by haselwarter** [ProofGeneral/PG#668]
When an org source block gets fontified, this happens in an ephemeral buffer with the major mode associated to the language of the block. `proof-config-done` at https://github.com/ProofGeneral/PG/blob/master/generic/proof-script.el#L2819 overzealously sets `buffer-offer-save` on such buffers. Upon exiting Emacs, this leads to the user being prompted whether they want to save the ephemeral fontification buffer, which they certainly don't want.

    #+begin_src coq
    mixin_cmra_extend n (x y1 y2 : A) :
      ✓{n} x → x ≡{n}≡ y1 ⋅ y2 →
      { z1 : A & { z2 | x ≡ z1 ⋅ z2 ∧ z1 ≡{n}≡ y1 ∧ z2 ≡{n}≡ y2 } }
    #+end_src

Why `proof-config-done` sets `buffer-offer-save` in the first place, I don't know. Temporary buffers don't get saved in Emacs; presumably a proof-general user got bitten by this once and decided to change the behaviour of Emacs by patching proof-general rather than changing their own config. I suggest the removal of that line unless there is a good reason to set `buffer-offer-save` here.

**Comment by cpitclaudel** [comment]
I agree with your analysis.  Could you prepare a patch?
It might also be good to make an org-mode patch to set this variable to nil.

**Comment by haselwarter** [comment]
Thank you for the quick response, @cpitclaudel . I don't know what an org-mode patch would look like; in particular, the buffer name used for fontification does start with ` *` (space-asterisk), which is the Emacs convention for temporary / background buffers. If there are other mechanisms to indicate a buffer as temporary, it would make sense to apply them, but I'm not aware of them.

**Comment by monnier** [comment]
> I agree with your analysis.  Could you prepare a patch?

Agreed.  If we want to try and preserve the former behavior, we would do
it conditionally as in:

    (unless (or buffer-file-name (string-match "\\` " (buffer-name)))
      (setq buffer-offer-save t))

After all, we already tested `buffer-file-name`.

> It might also be good to make an org-mode patch to set this variable to nil.

AFAIK, Emacs's handling of `buffer-offer-save` doesn't distinguish temp
buffers (with a leading SPC in their name) from others: buffers without
an associated file are just not saved by default.

So, you might be right that it can make sense for a major mode to set
`buffer-offer-save` based on the kinds of buffers where it'll be used
and hence for Org-babel to override this choice.


        Stefan

**Comment by haselwarter** [comment]
Thanks for weighing in Stefan @monnier . Gnus for instance sets `buffer-offer-save` in `message-mode`. I think it's preferable for `save-some-buffers` to keep the handling of `buffer-offer-save` simple, as it is now, and let the user deal with it.

The change you're suggesting would be more conservative. Maybe some PG users have grown accustomed to PG's behaviour and frequently start scripting in a new buffer without file and then close Emacs without saving. Seems unlikely, but I also can't see it doing any harm at this point.
