### ISSUE TITLE
Proof General overrides Emacs icon

### ISSUE THREAD

**Issue by jeanas** [ProofGeneral/PG#672]
![image](https://user-images.githubusercontent.com/37271310/193457373-229739b5-611b-478c-ba4e-1151cb665bbc.png)

I am using Proof General installed from Melpa on Fedora 36. The Emacs version is "GNU Emacs 28.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-07-15" (from the Fedora repos). When I launch Emacs on any file, not just a file written for a theorem prover, the Emacs window does not display as associated with the Emacs application on the dash, but with a logo of Proof General that appears temporarily on the dash.

**Comment by Matafou** [comment]
Hi. Thanks for reporting. I am not familiar with macOS but this looks very surprising! I wonder how a melpa package can even do that in the first place.
@erikmd any idea?

**Comment by Matafou** [comment]
Ok that is a good news(for us). Thanks!
