### ISSUE TITLE
`coq-accept-proof-using-suggestion 'always` incorrectly believes that `proof` is a proof directive

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#674]
The replacement should be case-sensitive, to avoid diffs like
```diff
-  Lemma r'_correct : ((2 ^ (width) * r' ) mod M = 1)%Z. (*Not very elegant proof...*)
+  Lemma r'_correct : ((2 ^ (width) * r' ) mod M = 1)%Z. (*Not very elegant proof using M_eq check_args_ok using M_eq check_args_ok using M_eq check_args_ok using M_eq check_args_ok...*)
   Proof.
```

**Comment by Matafou** [comment]
Ouch. Thanks Jason. I will have a look at it soon.

**Comment by Matafou** [comment]
Hi Jason, I can't reproduce this bug on current PG (master). Could it be possible that you have an old version? Or maybe the bug is more subtle and I need to test on your file exactly. 

```coq
Require Import ZArith.
Section Sect.
  Variables width r' M:Z.
  Hypothesis hyp: ((2 ^ (width) * r' ) mod M = 1)%Z.
  Lemma r'_correct : ((2 ^ (width) * r' ) mod M = 1)%Z. (*Not very elegant proof...*)
  Proof using hyp. (* <- added automatically at the right place *)
    apply hyp.
  Qed.
```

**Comment by Matafou** [comment]
Ping @JasonGross: is it still reproduceable with current PG? It looks already fixed to me.

**Comment by JasonGross** [comment]
It's plausible this is already fixed, especially if that fragment works for you.  I'll reopen if I see it again
