### ISSUE TITLE
Feature request: sparate commands for jumping to current point with/without omitting proofs

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#682]
I absolutely love the "omit proofs" feature! However, I find myself having to go to the quick settings all the time to turn it on and off, since I keep switching between "just get me to the proof state at this point as fast as possible" and "please ensure that all proofs in this file keep working". I wonder if there is a way that switching between these situations could be made easier.

For instance, if there was a command that behave almost like C-c C-Enter, but with skipping proofs, then I would leave the "omit proofs" flag off usually (so that C-c C-Enter, C-c C-b, and so on all do not omit proofs), and then when I am in "get me to this proof state as quickly as possible" mode, I would use the other command. I am not sure which shortcuts are still free and could be used for this. Also it is entirely possible that there is a better way to cater this usecase. :)

**Comment by erikmd** [comment]
> if there was a command that behave almost like C-c C-Enter, but with skipping proofs, then I would leave the "omit proofs" flag off usually (so that C-c C-Enter, C-c C-b, and so on all do not omit proofs).

Thanks a lot @RalfJung for your testing and feedback!

Good news: in proof-general 4.5, there's already (almost!) the feature you are interested in:

* You can enable the "omit proof" feature by default,  
  manually by the menu or doing `M-: (proof-omit-proofs-option-toggle 1) RET`
* and then, add a prefix argument at the time you want to disable the feature and run all opaque proofs,  
  i.e. just run `C-u C-c C-RET` or `C-u C-c C-b`

However, I realize that having the prefix argument the other way around (disabling "omit proofs" by default) could be nice.

→ I just opened PR #683, hopefully this can be integrated in master soon if this looks good as well to @hendriktews (the author of the omit proofs feature)

**Comment by RalfJung** [comment]
I didn't know about `C-u`, that already works very nicely. :)  I haven't thought deeply about which one I want to be the default (C-c C-RET), so for now I will see how "omit by default, C-u for full checking" works for me. Thanks!

**Comment by hendriktews** [comment]
> I didn't know about C-u, that already works very nicely. :) I

This was documented from the very beginning, see
https://proofgeneral.github.io/doc/master/userman/Coq-Proof-General/#Omitting-proofs-for-speed

Ralf, if you, as one of our power users, have a suggestion on how we
could communicate these kind of things to Proof General users in a
better way, we would love to hear about it! Seriously. For some time
already, I have the suspicion that the Proof General user manual is
a write-only medium.

**Comment by RalfJung** [comment]
In terms of the documentation itself:

> With a prefix argument, both proof-goto-point and proof-process-buffer will temporarily disable the omit proofs feature and send the full proof script to Coq. 

Maybe it is my lack of emacs knowledge, but this tells me nothing. I have no clue what a "prefix argument" is. Quick googling helps, but it would also be good to just say that this means one has to do `C-u C-c C-RET` etc.

**Comment by erikmd** [comment]
FWIW @RalfJung, here is the documentation of `C-u` (`C-h k C-u`):

```elisp
universal-argument is an interactive and byte-compiled function
defined in simple.el.gz.

Signature
(universal-argument)

Documentation
Begin a numeric argument for the following command.

Digits or minus sign following C-u make up the numeric argument.
C-u following the digits or minus sign ends the argument.
C-u without digits or minus sign provides 4 as argument.
Repeating C-u without digits or minus sign
 multiplies the argument by 4 each time.
For some commands, just C-u by itself serves as a flag
that is different in effect from any particular numeric argument.
These commands include C-SPC and M-x start-kbd-macro.

Key Bindings
global-map C-u
```

To sum up, it is useful to:
* repeat some characters (try `C-u 64 *` or what it amounts to the same, `C-u C-u C-u *`, as 64=4×4×4)
* pass some arguments to functions, see also https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html for details.

**Comment by erikmd** [comment]
@RalfJung Cc @ProofGeneral/core
just FYI, the implementation addressing this feature request is now available in MELPA,
and I tweeted an announcement: https://twitter.com/ErikMartinDorel/status/1620037817660473344
