### ISSUE TITLE
Coq compilation assumes that coqdep only returns .vo files

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#69]
Hey @hendriktews,

I'm having trouble compiling projects that contain plugins (.cmx files). Coqdep is reporting them as dependencies, and since PG doesn't filter dependencies to look for `vo` files only, it passes them through `coq-library-src-of-obj-file`, which turns them into files with extension `.cm` instead of `.cmx`, which causes a compilation error.

Would it be enough to filter the output of coqdep at the end of `coq-par-analyse-coq-dep-exit`?

Clément

**Comment by hendriktews** [comment]
Apparently yes - Sorry for the late answer.
