### ISSUE TITLE
Request to add keystroke for Coq's "Print Assumptions" command 

### ISSUE THREAD

**Issue by DavidAspinall** [ProofGeneral/PG#7]
I received a request to add a keystroke, calling this code:

    (defun coq-Print-Assumptions ()
       "Ask for an ident and print the assumptions it depends on."
       (interactive)
       (coq-ask-do "Print Assumptions" "Print Assumptions"))

**Comment by cpitclaudel** [comment]
Shouldn't we just add a small guide in the README on creating custom bindings? It's not obvious to me that this is a common need :/ PG makes it very easy to define them, so I'm not certain we need to reserve even more keys than we already do on every machine.

**Comment by Matafou** [comment]
I would agree with Clement.

What has been your answer to such request in the past David?

P.

2015-11-03 15:53 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
I'm going to close this: it should be trivial for users to add such a binding manually.
