### ISSUE TITLE
Destructuring let breaks coq-Check et al.'s default suggestion

### ISSUE THREAD

**Issue by wilcoxjay** [ProofGeneral/PG#71]
Consider the following file 
```
Record foo := Foo { bar : nat }.
Definition x : foo := Foo 3.
Eval compute in let 'Foo b := x in b.
```
which uses a destructuring let on the third line. Placing the cursor over "Foo" on the third line and running `coq-Check` produces a suggested search term of `""` (i.e. the empty string). The correct behavior can be demonstrated by placing the cursor over "Foo" in the second line.

Presumably the apostrophe that is part of the syntax of destructuring let is confusing some of the parsing code somewhere.

**Comment by cpitclaudel** [comment]
Fascinating. Never saw this syntax before.
It does work with Company-Coq's M-f12 though, right? Maybe I should merge that code in Proof General.

**Comment by cpitclaudel** [comment]
The probem is with the implementation of `coq-id-at-point`, but I don't really understand why it does what it does :/ I'll defer to @Matafou

**Comment by wilcoxjay** [comment]
Yes, it does work with company-coq's M-f12 for me. (Side note: thanks for reminding me of this feature!)

**Comment by cpitclaudel** [comment]
Ok, thanks for testing. Btw, if you have a <menu> key on your laptop, it's available on that key too.

**Comment by Matafou** [comment]
Hi, thanks for reporting.

@cpitclaudel the reason why coq-id-at-point is based on symbol-at-point (emacs builtin function, deals with utf8 letters etc). Problem is that this function uses char classes to detect word constituent, and ' can be a word constituent except if at the beginning of a word. I will try to fix this soon.

**Comment by Matafou** [comment]
Should be fixed. Thanks again!

**Comment by cpitclaudel** [comment]
Neat, thanks for the fix Pierre! I know about `symbol-at-point`; I don't use it in company-coq because I need symbol boundaries, too,

**Comment by Matafou** [comment]
Yes I see that you use a special regexp to distinguish first character. I
do the reverse: first ask symbol-at-point (which is unicode compatible +
user configurable via char classes) and then remove trailing or heading
characters if needed.

P.

2016-05-02 17:18 GMT+02:00 Clément Pit--Claudel <notifications@github.com>:

> don't use it in company-coq because I need symbol boundaries

**Comment by cpitclaudel** [comment]
Do you have a good way to get start and end positions of the symbol, though?

**Comment by Matafou** [comment]
No I don't. indeed. Maybe going back with backward-sexp and then re-search-forward?

Something like:

(defun symbol-at-point-bounds ()
  (save-excursion
    (let* ((s (symbol-at-point))
	   (re (regexp-quote (symbol-name s))))
      (when s
	(unless (looking-at re) (backward-sexp))
	(let ((srch (search-forward re)))
	  (list s (match-beginning 0) (match-end 0)))))))

**Comment by cpitclaudel** [comment]
Thanks. I'll consider this :)

**Comment by cpitclaudel** [comment]
Actually, looking into this further, there's also `bounds-of-things-at-point` :)

**Comment by Matafou** [comment]
Ho, I thought this one was part of an external library but it is actuall standard lib.
