### ISSUE TITLE
Library more.v is required

### ISSUE THREAD

**Issue by YaZko** [ProofGeneral/PG#75]
Hello,

I just setup my emacs on a new machine and seem to encounter a puzzling bug with PG. I get systematic failure with proof-process-buffer and (extremely) frequent failure with company-coq-proof-goto-point while proof-assert-next-command-interactive seems to never fail. Once the failure happens, nothing can be processed anymore.
The error message is the following (note that I do not have any file nor module names more in my development):

-*- mode: compilation; -*-

echo "Require more." > /tmp/ProofGeneral-coq257328H.v coqdep -I /path/to/my/dir /tmp/ProofGeneral-coq257328H.v
*** Warning: in file /tmp/ProofGeneral-coq257328H.v, library more.v is required and has not been found in loadpath!
/tmp/ProofGeneral-coq257328H.vo /tmp/ProofGeneral-coq257328H.glob /tmp/ProofGeneral-coq257328H.v.beautified: /tmp/ProofGeneral-coq257328H.v

I installed the latest version for both PG and company coq, am on emacs 24.5.2, use Coq 8.4pl4.

Would anyone see what I might be missing?

**Comment by Matafou** [comment]
Hi, do you have a _coqProject file somewhere in the parents directories? It
looks like pg tries to compile some file before starting coqtop.
Best
P

**Comment by YaZko** [comment]
Hi Pierre,

Thanks for the answer. However I did suspect a forgotten _coqProject at first too, but after doing a triple check I cannot find any. The same repo works fine on my other machine.

Note that it is hard to be positive but the crash seems to happen when I ask him to compile too much code at once. That would be coherent with next-line never crashing, goto-point sometimes and buffer everytime.

Best,
Y

**Comment by Matafou** [comment]
Did you check the parent directories of you files too? PG looks for a
project file all along the parents directories.

P.



2016-05-16 14:41 GMT+02:00 Yannick Zakowski <notifications@github.com>:

**Comment by YaZko** [comment]
Damn I got it, it is quite stupid in definitive. I definitively did not have any project file. The problem is that I have a comment in the file I was working on containing the string «(...) require more (...)». When processed, PG therefore tries to find this more.v file...

The problem hence happens whatever command is used to process the line in question, it simply indeed always happened when going all at once, and simply did not reach it line by line.
Note that this bug must have been introduced fairly recently since it works on my other computer whose PG must be a couple of months old I think.

One additional bit which might be relevant: the comment is inside an Inductive definition, explaining a case, it therefore get processed simultaneously with the inductive.

It therefore is easy to fix on my side, thanks for the help! I dunno how hard/worth it is to fix on PG's side however?

Y

**Comment by cpitclaudel** [comment]
Thanks for the diagnosis. Do you think you could post a code sample?

**Comment by Matafou** [comment]
Nice catch! This reproduces the bug (with compile before Require set).

Inductive foo : Type :=
  C1: nat -> foo (* Require dfgdfg etc. *)
| C2: foo.


2016-05-17 19:24 GMT+02:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by YaZko** [comment]
Thanks for the minimal example!
