### ISSUE TITLE
Why do we call proof-locate-executable on coq-prog-name (et al)?

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#76]
This is the definition of `coq-prog-name`:

```
(defcustom coq-prog-name
  (proof-locate-executable "coqtop" t '("C:/Program Files/Coq/bin"))
```

Why do we need the proof-locate-executable part?

IIUC this computes an absolute path. The problem is that this prevents us from running PG in Tramp. 

Currently, running Coq remotely in Tramp only works when Coq isn't installed on the local machine, because coq-prog-name ends up being set to just `coqtop` in that case. But if Coq is installed, then we pass the full path of the local Coq binary to the remote server via tramp, and of course that doesn't work (the Coq binary isn't in the same location on the remote machine).

Just setting `coq-prog-name` to "coqtop" seems to work fine, though. Maybe we could do that?

**Comment by Matafou** [comment]
This the default setting, but you can set this variable via local variable
or .dir_locals.el file. It will overwrite this setting. So just putting

(* Local Variables: *)
(* coq-prog-name: "coqtop" *)
(* End: *)

will do the trick.

The proof-locate-executable is maybe useful on windows system (does the win
installer set the path variable?).

Would something like this be better (return "coqtop" if it is found in the
path, then try some extra dirs):

(defcustom coq-prog-name
  (if (executable-find "coqtop") "coqtop"
   (proof-locate-executable "coqtop" t '("C:/Program Files/Coq/bin")))

P.

2016-05-20 0:29 GMT+02:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
>  The proof-locate-executable is maybe useful on windows system (does the win installer set the path variable?).

If it doesn't, that's probably a bug, right?

>  Would something like this be better (return "coqtop" if it is found in the path, then try some extra dirs): 

This could be a neat trick, actually! it will work if Coq isn't installed, since we'll keep returning just "coqtop" in that case, and in the case where a local and a remote Coqtop are both available, it could work as well.

Question: is there a way we could add these extra directories to the search path just around the actual calls to coqtop? So that it works even in the windows case?

**Comment by JasonGross** [comment]
When I set `proof-prog-name-ask` to `t`, I like that I get an absolute path to coqtop; this makes it easier to switch it to other Coq binaries which are located in similar directories.

**Comment by cpitclaudel** [comment]
Good point. Should be easy to support though.

**Comment by hendriktews** [comment]
I believe I wrote that already: My impression is that proof-locate-executable was inserted to make Proof General work for Isabelle for those users that simply unpacked the Isabelle archive in their home directory.

I would like to summarize the discussion here: the call to proof-locate-executable is harmful for Trump, it should better be omitted. The only positive side effect is that it causes Proof General to show a complete path when proof-prog-name-ask is t.

@cpitclaudel @JasonGross @Matafou Would you agree?

**Comment by Matafou** [comment]
Tried to make something satisfying all use cases in this PR: #132.

P.
