### ISSUE TITLE
File mode specification error: (void-variable coq-cmd-force-next-proof-kept)

### ISSUE THREAD

**Issue by DaKnig** [ProofGeneral/PG#775]
Steps to reproduce:
- `package-install RET proof-general`
- `package-install RET company-coq`
- open a coq file ending with `.v`
- get the error in the title

this error is reported again when re-enabling coq-mode

**Comment by erikmd** [comment]
Hi @DaKnig, thanks for your report!

Could you give more details on your configuration? (OS and (if applicable) Linux distribution, `emacs --version`)

@hendriktews could you take a look? the reported error mentions the custom you had introduced in: https://github.com/ProofGeneral/PG/commit/0a793dbbe55c58348e581f828e77e651e195ed5d

**Comment by erikmd** [comment]
@DaKnig can you also run the following code and paste its output?

`ls -dl .emacs.d/elpa/proof-general-*`

**Comment by hendriktews** [comment]
Can you retry without company-coq?
I only see two occurrences of `coq-cmd-force-next-proof-kept`, one in coq.el and the declaration in coq-syntax.el. And coq.el loads coq-syntax.el. Therefore my suspicion is that the problem comes from copany-coq.

**Comment by hendriktews** [comment]
If you need a workaround, put
```
(setq coq-cmd-force-next-proof-kept "Let")
```
in your `.emacs`

**Comment by Matafou** [comment]
What is the status of this issue pls?

**Comment by Matafou** [comment]
Does it disappear if company-coq is unstalled.

**Comment by DaKnig** [comment]
no

**Comment by Matafou** [comment]
Sorry my question was badly spelled so your answer is now ambiguous :-). Are you saying that when you remove company-coq the bug was still there?

**Comment by DaKnig** [comment]
the bug is still there without company-coq yes. if you want to do faster back-and-forth I am available on libera and matrix so just tell what room to join.

**Comment by hendriktews** [comment]
Additionally, I tried:
- adding melpa as described on the company-coq page
- installing proof-general and company-coq from melpa
Again, the error does not appear.

**Comment by hendriktews** [comment]
@DaKnig : I am closing this issue now on the assumption that it was a problem in your personal emacs configuration. Feel free to reopen to continue the investigation if this is incorrect.
