### ISSUE TITLE
 PG does not position to error

### ISSUE THREAD

**Issue by Matafou** [ProofGeneral/PG#781]
This bug appeared because of PR #774. Backtracking it is not satisfying because #773 shows a good reason for it.

Example:
```coq
Require Import Utf8.
Definition trois := 3. (*test-definition*)
Definition β := 3. (*test-definition*)
Definition β' := 3. (*test-definition*)
Definition β'' := 3. (*test-definition*)
Print trois.
Eval compute in (λ γγ:nat, γγ)
                       4 +
                       (λ a:nat, a) 4
                     + ααα * trois * trois.
```
the error is not positioned on `ααα`. This has nothing to do with utf8, but any fix should check that it works ok for this.

**Comment by Matafou** [comment]
original issue by Vadim Silva on [zulip](https://coq.zulipchat.com/#narrow/stream/304019-Proof-General-users/topic/PG.20does.20not.20position.20to.20error/near/447874951).

**Comment by MackieLoeffel** [comment]
A simpler testcase that does not require Utf8 is the following:
```
Lemma test :
  Truea.
```
PG shows an error on first line for me, but it should be on the `Truea ` in the second line. Setting `proof-shell-strip-crs-from-input` to `t` (i.e. undoing https://github.com/ProofGeneral/PG/pull/774 ) works as a workaround.

**Comment by Matafou** [comment]
Thanks for the reduced case. I am planning a fix for the end of the summer. We need `proof-shell-strip-crs-from-input` for other reasons (#773). FTR, this is also slowed by a [bug in error location info from coq](https://github.com/coq/coq/issues/19355) now fixed in coq master.

**Comment by MackieLoeffel** [comment]
I am currently using the following in my `.emacs` file to automatically set `proof-shell-strip-crs-from-input` to `t`:
```
(add-hook 'coq-shell-mode-hook '(lambda () (setq proof-shell-strip-crs-from-input t)))
```
(`custom-set-variables` does not work since the configuration of `coq-shell-mode` overrides it.)

**Comment by monnier** [comment]
> (add-hook 'coq-shell-mode-hook '(lambda () (setq proof-shell-strip-crs-from-input t)))

Side note: please don't quote your lambdas.

**Comment by MackieLoeffel** [comment]
> Side note: please don't quote your lambdas.

Indeed, thanks! I edited my message above in case someone copies it to their .emacs file.

**Comment by pedrotst** [comment]
I just bumped my PG from a 2 year old config and was driving myself nuts to find why the error wasn't working properly (hence got myself here). Thanks for the workaround, it worked here.
