### ISSUE TITLE
enhancement: easy way to colorize solution tactics that have some common regexp.

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#82]
I have many solution tactics that all start with "solve_", and write more all the time.  Is there, or could there be, an easy way to declare "^solve_" as a regexp that triggers the whole tactic name to be colored red like other solution tactics?

**Comment by cpitclaudel** [comment]
Can you try this? 

```elisp
(font-lock-add-keywords 'coq-mode '(("\\_<solve_\\(\\sw\\|\\s_\\)+\\_>" 0 'coq-solve-tactics-face prepend)))
```

You may need to call `M-x font-lock-fontify-buffer` to see the results.

(I'm a bit scared of PG's vast array of wrappers around Emacs functionality, so I wouldn't be too strongly in favor of adding a custom feature.)

**Comment by jonleivent** [comment]
I had to re-visit the buffer to get it to work, but it works!  I'll put that into my .emacs in my coq-mode-hook.

Thanks!

**Comment by jonleivent** [comment]
Doesn't work in coq-mode-hook on the first buffer.  So I moved it to with-eval-after-load 'coq, and it works there.

**Comment by cpitclaudel** [comment]
That's right. you'd need to use `nil` instead of `coq-mode` if you wanted to put it in `coq-mode-hook`. Using with-eval-after-load is perfect.
