### ISSUE TITLE
PG not compiling with emacs 24.4

### ISSUE THREAD

**Issue by b1rd1e** [ProofGeneral/PG#89]
But proof-easy-config.el file is present in generic folder.

admin@uname /cygdrive/c/uname/Softwares/PG-master/PG-master
$ make

---

 Byte compiling...

---

make elc
make[1]: Entering directory '/cygdrive/c/uname/Softwares/PG-master/PG-master'
emacs -batch -q -no-site-file -eval '(setq load-path (append (mapcar (lambda (d) (concat "/cygdrive/c/Chandrika/Softwares/PG-master/PG-master/" (symbol-name d))) (quote (acl2 ccc coq hol98 isar lego hol-light phox pgshell pgocaml pghaskell generic lib contrib/mmm))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn nil))' -f batch-byte-compile acl2/acl2.el

In toplevel form:
**acl2/acl2.el:14:1:Error: Cannot open load file: no such file or directory, proof-easy-config
make[1]: **\* [Makefile:121: acl2/acl2.elc] Error 1**
make[1]: Leaving directory '/cygdrive/c/uname/Softwares/PG-master/PG-master'
make: **\* [Makefile:87: compile] Error 2

admin@uname /cygdrive/c/uname/Softwares/PG-master/PG-master
$ emacs -version
**GNU Emacs 24.4.1**
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

**Comment by cpitclaudel** [comment]
I'd say skip compiling; I don't have a copy of Windows handy to test this with, and compiling isn't needed to run PG.

**Comment by b1rd1e** [comment]
Yes, Thank you for replying. I had figured out that I don't need to compile to run PG. But figuring that out, ate a lot of my time.

**Comment by cpitclaudel** [comment]
Sorry about this. Did you install Emacs through Cygwin?

**Comment by cpitclaudel** [comment]
Otherwise, my guess would be that Emacs isn't cygwin-aware, and is getting confused by paths like `/cygdrive/...`.

**Comment by b1rd1e** [comment]
No, I did not install Emacs using Cygwin. 
Okay, if we assume that your guess is right, could you please suggest some way to make Emacs cygwin-aware?

**Comment by cpitclaudel** [comment]
Ah, I see. I have no idea how Emacs works with cygwin, but I can try to fix the Makefile instead. Let me have a look.

**Comment by cpitclaudel** [comment]
Ok, can you try replacing the BYTECOMP line in the Makefile with this?

```
BYTECOMP = $(BATCHEMACS) -eval '(setq load-path (append (mapcar (lambda (d) (expand-file-name (symbol-name d))) (quote (${ELISP_DIRS}))) load-path))' -eval '(progn (require (quote bytecomp)) (require (quote mouse)) (require (quote tool-bar)) (require (quote fontset)) (setq byte-compile-warnings (remove (quote cl-functions) (remove (quote noruntime) byte-compile-warning-types))) (setq byte-compile-error-on-warn $(ERROR_ON_WARN)))' -f batch-byte-compile
```

The line before is

```
ERROR_ON_WARN = nil
```
and the one after is

```
EL=$(shell for f in $(ELISP_DIRS); do ls $$f/*.el; done)
```

**Comment by ejgallego** [comment]
This seems stale.

**Comment by hendriktews** [comment]
We discontinued support for emacs 24, the earliest supported version is now 25.1, see README.md. Therefore we are not going to investigate of fix this issue.
