### ISSUE TITLE
Retracting to a point with multiple overlays fails

### ISSUE THREAD

**Issue by tchajed** [ProofGeneral/PG#97]
I can reproduce this in Spacemacs by attempting to make any change starting at an open parenthesis, which fails with "wrong type argument: number-or-marker-p, nil", and nothing is backtracked. (This is due to smartparens in particular, nothing Spacemacs-specific.)

I tracked down the error to coq-find-and-forget, https://github.com/ProofGeneral/PG/blob/master/coq/coq.el#L729, where the check `(= proofdepth 0)` fails since `proofdepth` is nil.

Furthermore, this occurs because the wrong overlay is being passed to this function (the span argument). This is due to proof-retract-until-point using `(span-at (point) 'type)` to get the span, when it should really search `(spans-at-point-prop (point) 'type)` for one that is a ProofGeneral span. For reference, here's what `(mapcar 'overlay-properties (spans-at-point-prop (point) 'type))` evaluates to on a paren for me (with some spacing adding for readability):

```
((type show-pair priority 1000 face sp-show-pair-match-face)

(proofnum 0 proofstack nil statenum 51 pg-helpspan #<overlay from 1 to 25 in test.v>
isearch-open-invisible-temporary pg-open-invisible-span isearch-open-invisible pg-open-invisible-span
span-delete-actions ((lambda nil (pg-remove-element (quote command) (quote command-9))))
rawname nil name "command-9" id command-9 idiom command
cmd "Definition foo := (1+1)." type vanilla))
```

The first span belongs to smartparens, while the second is what PG is looking for. I'm not sure what the best overlay property to filter for is among all these.

**Comment by tchajed** [comment]
Looks like issue #8 is the same thing

**Comment by cpitclaudel** [comment]
Let's look at this together later today :)

**Comment by Matafou** [comment]
I was not aware that spans were used for something else than pg. We should
indeed robustify this.

**Comment by psteckler** [comment]
Would the solution be simply to change the `type' property to something
like `pg-type'?

Also, it might be useful to attach these property names to variables, so
it's easy to modify all uses with just one change.

-- Paul

**Comment by tchajed** [comment]
Looks like I made a critical typo in the description. To clarify, there's nothing Spacemacs specific going on here. You can reproduce this issue using just smartparens and retracting to any paren.

There's some simpler, dependency-free way to reproduce the problem by creating an overlay with a property "type" and trying to retract to a point covered by this overlay. I can work that out if desired.

**Comment by cpitclaudel** [comment]
No need; I think the bug is clear :)
