### ISSUE TITLE
Set Implicit Arguments is out of place in the options menu

### ISSUE THREAD

**Issue by tchajed** [ProofGeneral/PG#99]
I'm not sure why among all these printing options in the Coq > Options menu (`Printing All`, `Printing Coercions`, `Printing Synth`, etc) there is `Set Implicit Arguments`, which changes the automatically determined implicit arguments for definitions and should be stored in the file.

Was this intended to be `Set Printing Implicit`?

**Comment by erikmd** [comment]
Thanks for your report! Indeed `Set Printing Implicit` would be much more appropriate for this menu... I'm going to update this.

**Comment by erikmd** [comment]
Done, thanks for having reported this issue.

**Comment by tchajed** [comment]
Awesome, thanks!
